### ISSUE TITLE
Site maintenance rchain.coop

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#10]
Involved section:

Add a links to:
- Github/Members https://github.com/rchain/Members/#boards?repos=84472896
- Google membership registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform

**Comment by patrick727** [comment]
@lapin7 I added the members section into a contextual link. 

I still have feelings about requesting that much info upfront and like gregs idea of tiers.

Once we confirm minimal KYC and AML info, I will go ahead and link to the form as a pre-registration.

**Comment by lapin7** [comment]
@patrick727 I will split the form into sections.

**Comment by lapin7** [comment]
@patrick727 The form is now much better with logical branched sections (standard feature) 
https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform

**Comment by patrick727** [comment]
OK thankyou, 

What do you think the copy should say. 

"Membership Registration"
 Pre-register to become a member of the RChain Cooperative by filling out the google form.

**Comment by lapin7** [comment]
For me it's fine. Let's try it out. If it's not good we will see it in
Slack or in the "Remarks"

"Membership Registration"
[Pre-register](
https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform)
to
become a member of the RChain Cooperative.


--
HJ

**Comment by patrick727** [comment]
ok taken care of@lapin7

**Comment by lapin7** [comment]
Great !
We're going fine.
I expect a lot of comments on the membership form.
"HJ !!!, what are you doing??? You ask for money from people. We're not
ready yet."

Anyway we will see how it goes ;-)

--
HJ
