### ISSUE TITLE
M> Translate White Paper or other documents

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#100]
It's important to attract people from different cultures and with different languages. This is easiest when the English version is translated into local spoken languages.

**Comment by jeamick** [comment]
Hi, there I could for the translation of the whitepaper in French.

I already made some translations such as The yellow paper of Ethereum.

**Comment by lapin7** [comment]
Hi @jeamick 
Great that you could do a translation in French.
But there's first some investigation to do, because there's no language policy at the moment. In fact we need first a plan. Maybe you feel like helping with that, since you have experience with translation of Ethereum documentation.
It's all about self-organisation. So you have to set up your own team, set your goals and define your USD budget needed, which will be converted in RHOC.

There's a few things to do first:
[] fill out the [Activist registration form](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform)
[] reply to the [rchain/Member repository](https://github.com/rchain/Members/invitations) in order to become a collaborator
[] use the form [Budget allocation and - spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform) in order to set first the budget of this issue and later to decide about the rewards for yourself and your collaborators.
[] you can take a look at the issues going on in [Pub Activist Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=0)


Link | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/100 | New | Translate White Paper or other documents | Marketing | 0 | $ - | $ - | $ - |  



To get the feel of it, here's for example the [RChain Platform Architecture](http://rchain-architecture.readthedocs.io/en/latest/) and other doc's you will find in the [rchain/reference](https://github.com/rchain/reference). The editor is @JosDenmark . Please try to contact him.

Or you can contact @dckc about his try-outs.  He's interested to work on the rholang spec. I put a toe in the water: https://github.com/stprior/rholang-spec/pull/2 

If you have any questions/remarks or whatever, please ask.

**Comment by lapin7** [comment]
Hi @jeamick 
Please post here some links of your translations of Ethereum Documents. So we can see what you've done so far.
Regards,
HJ

**Comment by jeamick** [comment]
Hi, @lapin7 
 Here is the link to the translation:  I work with Asseth a French association working on the development of Ethereum.
[](https://www.ethereum-france.com/yellow-paper-ethereum-livre-jaune-traduction-complete/)

**Comment by lapin7** [comment]
Salut @jeamick 
Thx, but the link is missing. Nice that you work with [Asseth](http://www.asseth.fr/). Maybe this could be the start of a great cooperation. 

Le mois d'Octobre je suis en France. Donc peut-etre nous pouvons se fixer un RDV d'intro?

A+ HJ

**Comment by jeamick** [comment]
Oui bien sur !

**Comment by lapin7** [comment]
Merci. Merveilleux :-)
Do you think you could make such a site for RChain?
A kind of third party clone but then in French?
It could probably serve as a template for other languages. In that way it would become a whole project under your supervision and of course in cooperation with the site manager of the rchain.coop

**Comment by jeamick** [comment]
Yes , I could traduce it in french sure.

I will create my own translation repo and after submitting it to you yes.

I do not know who is in charge of the site manager of the rchain.coop ...

Should I also ask for a budget nope?

Could someone explain it to me about this?

**Comment by lapin7** [comment]
Hi @jeamick 
We're a bunch of people who are interested in getting the platform RChain up and running. We are all member of the Cooperative RChain. Development is going fine, but all business functions have to be developed by the members of the Coop.
We can also try to branch off per country and make a translation of the site, white paper, etc. But as soon as that happens, then members in that language have to be on boarded and do the support of that language.

So try to fix a budget for this issue, and say what you're going to do.

When there are at least 3 members to support that budget, then it will be allocated. It's just the average of the 3.

During each month, the members of that issue can decide about how to distribute the budget. Each member needs at least 3 opinions of percentage of work done. The average per member is then the individual reward.

So please try to find 2 of your friends and them so far that they become a member of RChain. After that they can support your issue and you can go ahead.

BTW. Are you on the app Telegram?

**Comment by sportshark** [comment]
I can translate the website of Rchain and News to Chinese and also build a  Rchain-fans pub website to pubulish news about Rchain in Chinese

**Comment by sportshark** [comment]
Well, I have bulilt a blockchain explorer for Asch ,you can see it http://asch.pub and http://aschd.org

**Comment by sportshark** [comment]
What shuold I do next?

**Comment by lapin7** [comment]
@sportshark @jeamick @mbein
I think we should start with the most important pages of the website.

@mbein is in charge of https://rchain.coop. He told me that everything is configured for translating the website in several languages.

So we have to create first a Gsheet [website items](https://docs.google.com/spreadsheets/d/1jYQ9bOZpe26-3aApH9XCmTU4C2rar5ttVoH5_vQ95Rg/edit#gid=0) with items to translate.

After that we can translate a list of documents that explain RChain. I've created a new folder [RChain/Member/Translation](https://drive.google.com/drive/folders/0BwX0krsxHncTLWc5eU1qaEkyR2c)

In the mean time you can tell your friends that everything will be translated into local languages and that it goes faster when the audience, for reading about RChain in local languages, is increasing.

Let's also create a document to define in a Gdoc a [Translation policy](https://docs.google.com/document/d/1xSXK4DAVwcc-OnrvRm4KP-LOSwWKnAxVOWIpFcCAYaw/edit).

The translation is all blank at the moment, so it's up to you all to define "how we go forward".

Please don't forget to add a budget for this item.

When there are at least 3 members to support that budget, then it will be allocated. It's just the average of the 3. You can propose the budget by writing a comment under this issue. For example:
@jeamick >> $600

During each month, the members of that issue can decide about how to distribute the budget. Each member needs at least 3 opinions of percentage of work done. The average per member is then the individual reward.

@jeamick >> 75%
@lapin7 >> 5%
.....

**Comment by lapin7** [comment]
@sportshark here you can coordinate with @jeamick and @patrick727

**Comment by sportshark** [comment]
What is the first I should to translate to chinese?The official website or the official blog or newsletter?

**Comment by lapin7** [comment]
I suggest to start with the official website. But we have to talk with
Branko Gvoka how to do translations for regular items and so.
I assume the Chinese website is a 1:1 copy of the English one? Isn't it?

--
Cheers,
HJ

**Comment by sportshark** [comment]
@lapin7 aggree that the Chinese website is a 1:1 copy of the English one

**Comment by sportshark** [comment]
I am translating Newsletter 11.16 to Chinese.We are so lack of Chinese docs

**Comment by sportshark** [comment]
@lapin7 
I have translated the Newsletter 11.16 to Chinese,you can view the draft 
https://docs.google.com/document/d/1f1lTdmFOC5Ng4qI1rQ24nDFV0LByrQvBIJZZ4LTzaUQ/edit
and the original Newsletter 11.16 is here
https://drive.google.com/open?id=1Oo6TFDRqp8aS9gAzxWAmOSdmF6wbvM2U4b9-vOuqRRY

**Comment by patrick727** [comment]
@lapin7 

its actually @Rafkraft and @ValeBF working on rchain.coop

branko is tasked for member.rchain.coop
dan and steve are tasked for developer.rchain.coop

**Comment by Rafkraft** [comment]
Let's resume here:
As @patrick727 wrote, we are working with @ValeBF on the **rchain.coop** website. I18n is already implemented, when the design/integration is ok or 90% ok, I will contact you both @sportshark and @jeamick to get translations in chinese and french (je suis français aussi @jeamick  au passage ;) ).

I'll give you a list of all the sentences and text of the website, and you'll just have to traduce it.

I'll then integrate it. I cannot send you this document right now simply because as you can see on https://rchain.fabco.tech , lots of translations are still missing (loreum ipsum texts).

Cheers

**Comment by sportshark** [comment]
@Rafkraft Great work! Glad to work on it!

Next, I'm going to translate RChain's FAQ. Because too many Chinese are asking RChain questions again and again. If anyone thinks the translation work is necessary, please vote for me in the budget allocation  this month.Thank you !
You can see it https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit?ts=59e46ec5#gid=2052218093

**Comment by kitblake** [comment]
That would be great @sportshark! Please wait a bit before you start because there are big changes checked in that haven't been merged yet. 
We have – again – a queue of pull requests @patrick727, and some of them are probably going to conflict with each other.

**Comment by patrick727** [comment]
So these are the people that we can ping about accepting pull requests
Ian 
Hj - member not owner
Ed 
Greg
Joe denman 
Navneet
Rchaintravis
Mike stay

**Comment by lapin7** [comment]
For inspiration, you might want to see https://www.w3.org/Consortium/Translation/ --@dckc
see also https://www.w3.org/Consortium/Translation/
And please edit the [translation policy](https://docs.google.com/document/d/1xSXK4DAVwcc-OnrvRm4KP-LOSwWKnAxVOWIpFcCAYaw/edit?ts=5a1a68e7) doc

**Comment by dckc** [comment]
A queue of pull requests? I'm struggling to find them. Help, @kitblake?

**Comment by kitblake** [comment]
@dckc I was referring to https://github.com/rchain/reference/pulls
This is a friction point. The FAQ has been updated for awhile but not merged. I will ping again in #60.

**Comment by sportshark** [comment]
Hello,I have translated the FAQ to Chinese,You can see it here
https://docs.google.com/document/d/1nXAMWJg9nCkHRfFBXt0JiunjWnT0m4v90WFxNq0d_os/edit?usp=sharing

If there is no problem, I will release it to the Chinese Web site in 2 days. It is convenient for Chinese to understand RChain

**Comment by kitblake** [comment]
I can't read Chinese but it looks great. The Chinese users will really appreciate it. @sportshark, can we store the Chinese FAQ in Github? The public URL of the English FAQ is:
https://github.com/rchain/reference/blob/master/faq.md
We could create a doc, for instance faq_cn.md, and publish it at:
https://github.com/rchain/reference/blob/master/faq_cn.md
Then in the future, if we have the FAQ in other languages (faq_fr.md, faq_de.md, etc.) they'll all be in the same place.

There's a tool called MarkItDown at http://markitdown.medusis.com/
I tried pasting the Chinese FAQ content to convert it, and it sorta worked. Probably it'll require some cleanup but I could help with that. 

Managing the content is much easier in a GDoc, especially when people are collaborating, so we probably should wait before converting until the Chinese FAQ content is final.

**Comment by sportshark** [comment]
@kitblake Good idea!
The chinese faq that I wrote is part of the faq.md,and I add some othe things what Chinese people care about.So it is not exactly the same as faq.md
According to your proposal, Next,I'm going to write a Chinese FAQ, which is exactly the same as FAQ in English.

**Comment by kitblake** [comment]
@sportshark Ok, if you wish. But imho it's fine if the Chinese FAQ is slightly different from the English FAQ because it has a different audience. So you don't need to maintain two documents that have a lot of overlap.

**Comment by sportshark** [comment]
@kitblake Yes，you are right !I will follow your opinion

**Comment by kitblake** [comment]
Yeah, the FAQ is a constantly evolving document so minimizing maintenance will pay off :)

The /reference location is a different repository than /Members. So when we think we have an iteration ready we'll do a pull request and somebody with permissions in /reference (usually @n10n) will review and merge. @sportshark, if you don't know Github don't worry, it's pretty simple.

**Comment by sportshark** [comment]
@patrick727 hello,I have translated the Newsletter December 14th 2017,
https://docs.google.com/document/d/1vVxpWZrJq463Gs9WHtCf-PYKSAKuyJocESu2EWABsWk/edit
You can find the Chinese Newsletter here
https://drive.google.com/file/d/1nvMSGD-7-sBvCG2RZnYufhPKaHm8m2Vk/view?usp=sharing

**Comment by sportshark** [comment]
hello All I have translated the News
https://www.reddit.com/r/RChain/comments/7lo003/rchain_prealpha_hellonode_v01_software_released/
You  can find the Chinese news here
https://docs.google.com/document/d/1exmlAmlu43TGoPpCWhdF8M5lTlwLnvB9zdtkKLRl2i4/edit?usp=sharing

**Comment by sportshark** [comment]
@kitblake hello I have finished the FAQ translation you can find it here
https://drive.google.com/file/d/1a1VAdLxpWyzUR5tJ7NPeunk1rlhVZIav/view?usp=sharing
plz review it ,if all is ok I will do a pull request

**Comment by kitblake** [comment]
@sportshark Looking good! Really cool to see this content in Chinese. I'm not sure where the "Members" section is (but I can only read URLs and things with English, and I don't see a link to CONTRIBUTING.md).

Let's both change the description of the Discord server. ok? There is only one now, so I've removed the word 'private' from any descriptions. The only link should be: https://discord.gg/fvY8qhx

Why don't you first create 'faq_cn.md' in: 
https://github.com/rchain/Members/tree/master/projects
This is in the Members repository, and we can edit until we're satisfied with the presentation. Then you can move it to /reference and do a pull request. 

You can use the http://markitdown.medusis.com/ tool for the initial conversion. Just copy the text from your Google doc and paste it.

**Comment by sportshark** [comment]
@kitblake Good idea! I will follow your advice

**Comment by sportshark** [comment]
@kitblake @lapin7 I have create 'faq_cn.md' in github,you can see it here https://github.com/rchain/Members/blob/master/projects/FAQ_CN.md
And I re-translated FAQ, this version is a complete and accurate translation of FAQ. while I find an independent third person to proofread the translation.

**Comment by kitblake** [comment]
@sportshark Looks great! :)
If it's ok with you, I will do some format editing to bring the faq_cnin line with the faq_en. I'll change things like headings, which right now (due to the simple conversion) are just bold text, while they should be level 1, 2, 3 etc. I don't think it will get in the way of the proofreading.

**Comment by sportshark** [comment]
@kitblake no problem！

**Comment by patrick727** [comment]
Great stuff @sportshark! this is great work
Thanks @kitblake for helping things move forward

**Comment by kitblake** [comment]
Ok @sportshark, I marked up the doc. If you edit you'll see the Markdown syntax. It's pretty simple. 
https://github.com/rchain/Members/blob/master/projects/faq_cn.md

Change anything that doesn't jive with Chinese presentation. 

I also renamed the file to lowercase for consistency. 

There's one stylistic detail: in the English faq there's no line space between questions and answers. I didn't change that in faq_cn yet but will do so if you think it works. Your call :)

**Comment by sportshark** [comment]
@kitblake I have reviewed the doc!  great work!  I think it's very good now

**Comment by kitblake** [comment]
@sportshark Ok, thanks. So we still want an "independent third person to proofread the translation", yes?

@n10n Fyi, the Chinese FAQ is almost done. @sportshark will move it into /reference and do a pull request when ready. Then we'll have these URLs for the FAQs:
https://github.com/rchain/reference/blob/master/faq.md
https://github.com/rchain/reference/blob/master/faq_cn.md

Please review the content now while it's still in /Members:
https://github.com/rchain/Members/blob/master/projects/faq_cn.md

**Comment by sportshark** [comment]
@kitblake I have found an independent third person to proofread the translation before I uploaded the doc. I mean that other members can also proofread translation,Thank you for your great work!

**Comment by kitblake** [comment]
@sportshark Gotcha, so we're almost ready to publish. I realized that we didn't have the QQ group in the FAQ, so I added it and the Telegram chat group and channel too. Can you translate those?

**Comment by sportshark** [comment]
@kitblake thank you  I will do it

**Comment by sportshark** [comment]
hello ,In December,the translation budget is 1600USD,but I fogot to vote for me in the translation work. So the reward for this month's translation work is 0. next month. please vote for my translation work,Thank you very much!

**Comment by sportshark** [comment]
Hello,I have pull request the faq_cn.md to the reference @patrick727 @kitblake 
https://github.com/rchain/reference/pull/29/commits/5996a8d4a0f85cf729513df899777b2f23a2d31b

**Comment by kitblake** [comment]
Nice! Will be great to have a Chinese FAQ.

**Comment by patrick727** [comment]
I doesnt look like I can merge the pull request.

@n10n or @lapin7 please see https://github.com/rchain/reference/pull/29 and merge the china reference page.

**Comment by dckc** [comment]
The translation work is great, but it's getting hard to see what's going on. I would prefer to see a separate issue for each translation. Collecting lessons learned on the process in a wiki page would be good.

**Comment by lapin7** [comment]
Please go ahead and make separate issues. Define them in a SMART way. ;-)

--
Cheers,
HJ

**Comment by dckc** [comment]
Ok... anyone who is doing translation, please open a separate issue.

I suggest "French translation of XYZ" as the form of the title.

**Comment by Keaycee** [comment]
Now we've got a France community on telegram https://t.me/rchain_fr , it would be great have the white paper and other document been translated to french as well. @dckc @lapin7

**Comment by dckc** [comment]
Please open a separate issue with a clear scope.

It's not at all straightforward to set a budget for translating "... or other documents."

**Comment by lapin7** [comment]
I think reopening closed issues will mess up the spreadsheet "PUB ...."
You can open a new issue with a reference to a closed issue.
Please make the issue SMART not just a brain dump.
Specific, Measurable, Achievable, Realistic, Timely.

--
Cheers,
HJ

**Comment by rjl493456442** [comment]
Dear @lapin7 Where is the write paper link?

**Comment by lapin7** [comment]
[Pub Activist Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=0)
Look for TAB: "201801 Budgets" and "201801 Rewards"

**Comment by sportshark** [comment]
In December, I fogot to vote for me in the translation work. So the reward in December's translation work is 0. Can you vote for my translation work? It is at row 121 "M> Translate White Paper or other documents" in Rewards 201801. and I have voted for you .
@Rafkraft @n10n 
Thank you

**Comment by JieL314** [comment]
Excuse me, @lapin7 .
We have completed the translation work for whitepaper Chinese version. Which format will be better when I upload to Github, PDF or docs or Markdown? 
The tencent QQ is not the unique useful channel in China. The Wechat group, Wechat public account, weibo(similiar to Twitter) are also useful channels. By which are easy to spread rchain cultural and update the latest news to Chinese people. Some projects have already done, such as Wanchain. This is my  second suggestion. Thank you.

**Comment by lapin7** [comment]
@JieL314 I've added a column for #100 in ["Rewards 201801"](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=950224463&range=AX121:AY133) 
So @JieL314 can add percentages for rewards

**Comment by yyh1102** [comment]
Hope to seed the Chinese version of the white paper. : )
