### ISSUE TITLE
M> RChain Presentation

### ISSUE THREAD

**Issue by jbassiri** [rchain/Members#102]
I'm making a presentation with a goal of having it be useful for a wide range of presenters and venues -- evangelist, members, leadership @ meetups, conferences, online -- in front of a diverse audience most of which will be new to RChain. Here's an outline:

1. Technical Team
2. Problem - scalability
3. The challenge 
    a) technical - concurrency (at the VM level) & consensus 
    b) contextualizing the challenge in the frame of 40 years of comp programming, mathematics, distributed computing and cryptography
4. Current solutions (serialized chains, non-concurrent)
5. Governance - Cooperative slide
6. Impact on Business and Society
    a) new org forms and business models
    b) legal and accounting industries
    c) money, transactions, finance
    d) distributed computing and decentralized apps (dApps)
7. Contact info - links for more info

I've reached out to Nash for input on content and "speakables" on the first slide since we've been discussing the commitment Pyrofex has made to RChain. What I've told him is "It's meant to be short, effective, punchy. You may be able to help with the content and "speakables" around the '1. Technical team' slide in particular. If you could send me information in addition to what I will gather on my own from the web it would help with the Pyrofex and RChain stories. The goal is to feature 
a) team caliber
b) complementary strengths 
c) history in the making - a component of working through time and space 
d) serendipity (like how you met Stay on the first day in Google) 
e) overcoming the odds to save the world. 

Any info, factual and anecdotal, will help this marketing effort."

Everyone's input is welcome as the outline, content, and speakables to each slide are nailed down. Only then will we have someone create the short punchy deck

**Comment by patrick727** [comment]
cool stuff see #70 where this is linked https://drive.google.com/file/d/0B89Hsy8OYAnUN1h5STJha2kzbms/view 

also can refer to youtube presentations, this is the holdings one for pencil works in ny https://www.youtube.com/watch?v=KzhXqpKicYc

**Comment by lapin7** [comment]
@jbassiri that's great that you are working on a presentation.
Please upload your current work (no matter how unfinished it is at the moment) in this folder: [RChain/Activists/Marketing-Community Dev/Content/Presentations](https://drive.google.com/drive/folders/0BwX0krsxHncTdEhSUjZNZkpKTlU)

This issue has no budget allocated to it yet.
And no rewards have been distributed. Although @jbassiri  has been working on it already. 
Please go ahead and use form [Budget allocation and - spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform) to fill it out 👍 

The sheet [Pub Activist Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1168839067) is constantly updated.

**Budget Allocation**

Issue # | Link | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
102 | https://github.com/rchain/Members/issues/93 | New | RChain Presentation | Marketing | 0 | $ - | $ - | $ - |  

**Budget Spending**

Github Issues | URL | Description | Category | Set | State | ⍴ Budget | ⍴ To Pay | Activist | AVG work | Votes | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | dckc | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | jimscarver | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | drbloom | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | kennyrowe | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | jbassiri | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | kdvalentine | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | patrick727 | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | kemihu2011 | 0% | 0 |  
102 | https://github.com/rchain/Members/issues/102 | RChain Presentation | Marketing | 0 | New | ⍴ - | ⍴ - | lapin7 | 0% | 0 |

**Comment by jbassiri** [comment]
@lapin7 can you share the privilege for me to add documents into here:
[RChain/Activists/Marketing-Community Dev/Content/Presentations](https://drive.google.com/drive/folders/0BwX0krsxHncTdEhSUjZNZkpKTlU) and then I will paste the presentation into there @kitblake @tgrospic -- it's currently available in the #business-development channel of Discord if you have access

**Comment by jbassiri** [comment]
Presentation is there now

**Comment by lapin7** [comment]
Great.

--
Cheers,
HJ
