### ISSUE TITLE
O> Update Readme.md

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#103]
[Readme.md](https://github.com/rchain/Members/blob/master/README.md) page is pretty out of date - governance link is 404, for example.

Update needed :-)

**Comment by lapin7** [comment]
This issue has no budget allocated to it yet?
And no rewards have been distributed. Although @dckc has been working on it already. 
Please go ahead @dckc and use form [Budget allocation and - spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform) to fill it out :+


Issue # | Link | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
103 | https://github.com/rchain/Members/issues/93 | New | Update Readme.md | Marketing | 0 | $ - | $ - | $ - | $ - | ⍴ - |  




Github Issues | URL | Description | Category | Set | State | ⍴ Budget | ⍴ To Pay | Activist | AVG work | Votes | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
103 | https://github.com/rchain/Members/issues/103 | Update Readme.md | Marketing | 0 | New | ⍴ - | ⍴ - | dckc | 0% | 0 |

**Comment by dckc** [comment]
ok... maybe I should have gotten more review first, but I kinda pulled the trigger: https://github.com/rchain/Members README and CONTRIBUTING 4685732

**Comment by lapin7** [comment]
Your edits are fine, because it's really an improvement :-)

--
Cheers,
HJ

**Comment by Ojimadu** [comment]
[Made a commit here]
 (https://github.com/rchain/Members/commit/e9be194b88b0e547764f9842a910c9fdb70a6cae)

**Comment by patrick727** [comment]
is this issue done to close?

**Comment by Ojimadu** [comment]
I think  it's done.
