### ISSUE TITLE
Member Voting

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#106]
A mechanism is needed for member voting

**Comment by jimscarver** [comment]
We are looking into a mechanism to have ethereum signed messages indicating the proposal and vote that could be on or off the blockchain. @kennyrowe should we continue on this?

A web3 app
* binary votes on proposal.
* list of alternatives ranked
    * group rank algorithm? tigman?

User experience?
Admin role?
Reporting?

**Comment by jimscarver** [comment]
Prior to today's meeting  I deployed a very simple voting contract on ropson https://ropsten.etherscan.io/address/0x5bcd0088aacc6e39d7506fed06606db358bb19be#code
The idea was that we could tally the votes for whitelisted member ids later for free.
The vote itself would have cost members about 28 cents each on the mainnet.
Using the signed message approach seems preferable.

**Comment by kitblake** [comment]
It's important to define – in advance – exactly what will be voted on and what sort of vote type it'll be.

**Comment by lapin7** [comment]
@jimscarver @kitblake Please don't forget to add a budget through form [Budget allocation and spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform)


URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/106 | New | Member Voting | Marketing | 0 | $ - | $ - | $ - | $ - | ⍴ - |  

And please distribute the budget over the assigned collaborators.


https://github.com/rchain/Members/issues/106 | Member Voting | Marketing | 0 | New | ⍴ - | $ - | $ - | $ - | Activist | 0% | 0 | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/106 | Member Voting | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @jimscarver | 0% | 0 |  
https://github.com/rchain/Members/issues/106 | Member Voting | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @kitblake | 0% | 0 |

**Comment by jimscarver** [comment]
I added a budget for $5000. If that enough to get this in production before oct 24?

**Comment by kennyrowe** [comment]
@jimscarver I think we should take the path that is most straightforward. My guess would be that would be to complete the work already started on github voting. 

Since the agenda will be posted prior to the meeting, proxies can be delegated as well.

**Comment by kitblake** [comment]
Imho the path of least resistance is a signed Ethereum message. No RHOCs.

The github voting requires Metamask/Parity, a custom RChain Chrome extension, and RHOCs. However we ( @Jake-Gillberg and @jimscarver ) can use what we learned from that project and create a voting contract for the Members meeting.

**Comment by kennyrowe** [comment]
That sounds right @jimscarver. A signed message from a whitelisted address should work. We might also be able to assign proxies in this manner.

For reference here are a few other ways to sign messages in Ethereum:
 - [helpEth](https://github.com/ethereumjs/helpeth), 
 - [MyEtherWallet](https://www.myetherwallet.com/signmsg.html)
 - Geth console `eth.sign("0x123...", web3.sha3("text"))`

**Comment by lapin7** [comment]
**Budget update**
**1 more Activist votes needed for setting the budget** (please find one :-)


URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/106 | New | Member Voting | Marketing | 2 | $ - | $ - | $ 5,000.00 | $ 5,000.00 | ⍴ 50,000.00 | @jimscarver @kitblake

**Comment by jimscarver** [comment]
We might have a page listing issues linked to a page like a modified MEW
signer <https://www.myetherwallet.com/signmsg.html> having a submit button
to post the issue and signed vote message.

To start simple the post can read a file containing the whitelisted
addresses, verify the address, and store the signed message in a file
having the name of the account address under a directory for each issue.

A tally script could count the votes for each issue.

For transparency the directory of issues could be browsable.

Thoughts?

**Comment by jimscarver** [comment]
@lapin7 do we have eth addresses for all members? We need to get address to be whitelisted from everyone. Suggestions.

**Comment by jimscarver** [comment]
[notes from byoid meeting]https://docs.google.com/document/d/1OVUGmxv4q1ywcxDG-V926lrXpkQNDs7n2eO2R5OJdOk/edit#heading=h.msn4vw3867m7) 
[video](https://youtu.be/BwM9b56xBfA)

**Comment by jimscarver** [comment]
I suggest we start with a clone of myetherwallet for the browser based code and flat files on the server side to keep it simple. What do you think @Jake-Gillberg ?

**Comment by jimscarver** [comment]
In the meeting yesterday we scrapped the plan to use signed messages for voting as it was determined that voting is best put on the member registration site. Thanks @drbloom .We need to engage with @kennyrowe and navneet as to what help if any they would like. https://youtu.be/Z0K_f5p7miw

**Comment by lapin7** [comment]
Sergey Ivliev of Lykke.com was so friendly to give insight in their voting process of their meeting in June,2017.

Citation:
_Hi HJ, we did a very simple open voting, identifying coinholders by sending the unique link to their email and/or login to web-site page with the credentials they use to access Lykke Wallet. We published all the results so that everyone could check that his voice was counted correctly https://report2016.lykke.com/VotingProtocol.pdf_

​Hope that helps

**Comment by jimscarver** [comment]
The two choices given Lykke voters are good. We need at least one choice

We do not have an rchain wallet but we do have all members registered at
the admin site. That why we can add the voting to the admin site.

Emailing a unique link is another good choice we could implement. A login
to the admin site could be enhanced to provide the members unique link also
so one solution could work for both mechanisms.

I have begun looking for open source voting solutions we might be able to
leverage. https://github.com/mdipierro/evote is one we could evaluate.

**Comment by jimscarver** [comment]
If there will be live voting at the meeting we need to be mobile friendly.

We should also be prepared to enter votes manually on request of the member.

**Comment by pythonical** [comment]
can i get the discord invite resent to my member email 'get9@pythonical.com'
i didn't realize i was logging in with different email address...

**Comment by entropee** [comment]
Pythonical, How many times did bitbay time out on you at 15 minutes? I tried twice and ran out of bitcoin.

**Comment by drbloom** [comment]
Kenny Rowe is organizing the annual meeting and vote.
The Co-op has very tight control of the Member Registration website and associated database. It makes sense to me that voting is done through that website.

**Comment by pythonical** [comment]
@entropee once. then payment went through but i then created the discord account with different email address.

**Comment by pythonical** [comment]
my thanks! that worked.

**Comment by jimscarver** [comment]
Good. I am glad to hear @kennyrowe is on top of it. Time is short. I hope we can begin testing soon. I'll stand by is any help is needed.

**Comment by vishyim** [comment]
@jimscarver I paid but I guess I did not get an option for the collective
crowdsale . I guess I missed it?

**Comment by jimscarver** [comment]
You missed the sale @vishyim  If you have other questions ask in discord or enter a new issue rather that clutter the member voting issue. Thanks.

**Comment by kennyrowe** [comment]
@jimscarver @lapin7 @drbloom lets get a call scheduled asap to sort this out. From what I can see I think a solution using the member's site will be the easiest to implement in the time available.

**Comment by jimscarver** [comment]
I am free after noon NY time tomorrow.

**Comment by n10n** [comment]
@kennyrowe Agree. @jimscarver @lapin7 @drbloom,  Today, talked briefly about integrating with SurveyMonkey using API and making the end user experience easy for voting without going outside of membership site. This would be a good topic for Wednesday Activist meeting.

**Comment by kennyrowe** [comment]
This would likely be a short-term solution as we need something in place very soon for the meeting on Oct 24th. The other benefit of using something like SurveyMonkey is that voting can also be done in person with a mobile device at the meeting. More info to come.

**Comment by lapin7** [comment]
Hi Navneet,
I'm in the process of banning the term "activists". It was a nice word and
it was meant to move on. But now I prefer to talk about members.
So activists are now treated as members. Activists don't exist anymore.

If you prefer we can talk about Active Members :-)


--
Cheers,
HJ

**Comment by kitblake** [comment]
About voting and timing: apparently the Member meeting will take place from 6-9pm Pacific Time. That is 3-6am Central European time so it's unlikely that many votes from Europeans will come in during the meeting. Voting in advance, perhaps given an international time zone, would be cogent.

**Comment by kennyrowe** [comment]
@kitblake yes online voting will begin in advance of the meeting. The goal is to open voting a week prior to the meeting and conclude online voting at 00:00 UTC Oct 25 (roughly an hour before the meeting starts)

**Comment by kitblake** [comment]
@kennyrowe Great. I'll be up for beta testing the voting mechanism.

**Comment by kennyrowe** [comment]
@all here's is the draft agenda https://docs.google.com/document/d/1uyoOYPu2PLAy32Vxs0xmMlOvao6IFvgWU2p8SIovqfU/edit?usp=sharing
