### ISSUE TITLE
Faulty link to "DRAFT COOP MEMBERSHIP AGREEMENT"

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#109]
There have been two persons that asked for access to [DRAFT COOP MEMBERSHIP AGREEMENT](https://drive.google.com/open?id=1iqhimjR38h-5mgv_km54wXrJkIK9PD7wzp_sXXOPIus). This doc is maybe referred to in the Coop Sign Up process.

The link has to be [Coop Membership Agreement](https://github.com/rchain/legaldocs/blob/master/Coop%20Membership%20Agreement.pdf)

Please repair that ASAP. Or give more details about where the link exactly is.

**Comment by lapin7** [comment]
You can set the budget here with a remark.

URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/109 | New | Faulty link to "DRAFT COOP MEMBERSHIP AGREEMENT" | Marketing | 1 | $ - | $ - | $ 40.00 | @lapin7
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by Ojimadu** [comment]
The link can be found at the coop website. Here precisely https://www.rchain.coop/coop-information-1#more-information under reference linlks at the bottom of the page.

**Comment by lapin7** [comment]
@Ojimadu that's great. Thx a lot. And please claim your reward by setting a % of work done for yourself and the other collaborators. Like:

@Ojimadu 90%
@lapin7 5%
@patrick727 5%

@patrick727 @drbloom Please repair this link !!
The link has to be [Coop Membership Agreement](https://github.com/rchain/legaldocs/blob/master/Coop%20Membership%20Agreement.pdf)

**Rewards**

URL | Description | Category | Set | Set | ⍴ To Pay | Activist | AVG work | Votes | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/109 | Faulty link to "DRAFT COOP MEMBERSHIP AGREEMENT" | Marketing | 1 | New | ⍴ 380 | Activist | 95% | 2 | Voters
https://github.com/rchain/Members/issues/109 | Faulty link to "DRAFT COOP MEMBERSHIP AGREEMENT" | Marketing | 1 | New | ⍴ 20 | @Ojimadu | 5% | 1 |  
https://github.com/rchain/Members/issues/109 | Faulty link to "DRAFT COOP MEMBERSHIP AGREEMENT" | Marketing | 1 | New | ⍴ 360 | @lapin7 | 90% | 1 | @lapin7 0.9

You can see the overview at [Pub Activist Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=0)

**Comment by patrick727** [comment]
@Ojimadu good catch, @lapin7  it's fixed now

**Comment by Ojimadu** [comment]
I think the reward has been set. It needs an extra vote to be claimed right?

**Comment by Ojimadu** [comment]
This is fixed and should be closed right?

**Comment by patrick727** [comment]
yes thank you
