### ISSUE TITLE
Site maintenance: rchain.io

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#11]
At section: Innovators of http://www.rchain.io/#new-page-2

The url to the Rchain Slack channel is http://slack.rchain.coop/

We will have now 2 slacks:
ourchain.slack.com
and 
rchain.slack.com

Let's kill ourchain.slack.com and move everybody to rchain.slack.com

**Comment by lapin7** [comment]
Everything relates to ourchain.slack.com
So there was no problem.

**Comment by jimscarver** [comment]
it is very strange, rchain.slack.com has the same number of active users as ourchain but I can't login or recover my password for it.
"You asked us to send you a password reset link for rchain.slack.com. It turns out the email address jimscarver@gmail.​com doesn't have an account on that team yet."

**Comment by lapin7** [comment]
Rchain.slack.com is not used by the coop. 
Only ourchain.slack.com works. The URL is different then the name 
It's confusing, indeed. 
I think Rchain has been taken by somebody else. 
Maybe a rebranding is necessary. Rchaincoop?

Hendrik Jan Hilbolling
lapin7@gmail.com
+31650291532
