### ISSUE TITLE
Newsletter - October 16th

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#112]
Here is the draft document for the newsletter October 16th

https://docs.google.com/document/d/1Orkm59F4VPGxIKIf_jBZhLTabEVufXsI21MFQNgCHKo/edit?usp=sharing

**Comment by Ojimadu** [comment]
You may want to add the official website to the newsletter.

**Comment by patrick727** [comment]
@Ojimadu yes will add that, but in order to sign up for the newsletter you would have had to land on the hp. But i see your point.

**Comment by patrick727** [comment]
Did the summaries and added them to the draft guys, will start to draft the wording tomorrow and this weekend, lots of new things happening in anticipation for the members meeting and any input is welcome!

**Comment by kitblake** [comment]
You can quote #124:

Beers, Brats, and Blockchains  
In preparation for our first member meeting, those of us who are not locked in meetings will get a chance to meet face to face for the first time and have conversations over the finest German beers. This is an open event so bring whomever you want. The location is a short 3/4 mile walk or cab to the Washington Hall.
http://evite.me/5pw4qcPXdW

**Comment by kitblake** [comment]
There are a bunch of tweaks in the Gdoc @patrick727, added a few of my own. This is a complex but exciting edition.
