### ISSUE TITLE
Annual meeting planning

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#116]
[Meeting adgenda doc](https://docs.google.com/document/d/1uyoOYPu2PLAy32Vxs0xmMlOvao6IFvgWU2p8SIovqfU/edit)

[Meeting Github project](https://github.com/rchain/Members/projects/5)

**Comment by kennyrowe** [comment]
Thanks @jimscarver 

A few more details for everyone.

**Location:**
Washington Hall Lodge Room
153 14th Ave, Seattle, WA 98122

**When**
October 24, 2017 at 6pm Pacific Time

**RSVP**
http://evite.me/HWdMTbZYx6

**Comment by dckc** [comment]
That google doc meeting agenda is helpful but I think it's not authoritative and it's increasingly out of date. As Greg discussed in the Oct 11 and 18 [weekly debrief][1], items to be voted on

  1. have been assigned ethereum addresses which have been posted in discord
  2. are in a surveymonkey

I suppose I should add a comment on the google doc too...

[1]: https://github.com/rchain/Members/wiki/Weekly-Debrief-Index

**Comment by dckc** [comment]
What should we expect by way of meeting records? Written minutes? Informal notes? An audio recording?

**Comment by dckc** [comment]
What's the duration of the meeting?

**Comment by jimscarver** [comment]
re surveymonkey: provisional ballot from @kennyrowe: : https://www.surveymonkey.com/r/Preview/?sm=1GMx476HqTZ70o7gbp3LQbDH7oMr4XMYoDF7esqH7bt4bJ_2B0NWXX9qHnpExCwjP_2B

The member committee elections are missing from the survey @kennyrowe 
Who are the candidates?

**Comment by kennyrowe** [comment]
@jimscarver committees are not elected see comments from https://github.com/rchain/Members/issues/118

**Comment by dckc** [comment]
I see the duration is 3hrs (6-9pm).
