### ISSUE TITLE
MEMBER COMMITTEES

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#118]
MEMBER COMMITTEES

Executive Committee
Nominating and Governance Committee
Compensation Committee

**Comment by kdvalentine** [comment]
@jimscarver @kennyrowe When will the committee responsibilities be posted?

**Comment by kennyrowe** [comment]
@kdvalentine yes I will post that son

**Comment by kennyrowe** [comment]
If you are a member and interested in serving on a committee please use this form.

https://docs.google.com/forms/d/e/1FAIpQLSdH1XjJcZw2g8JZdyB6KtTaza4mrpiadqdwFAezAkcTAXL78A/viewform?usp=sf_link

**Comment by patrick727** [comment]
Yes wondering the responsibilities as well.

**Comment by patrick727** [comment]
Was thinking about another committee called "Curation Committee" which essentially is a branch of Research but cleverly leverages the research for content. Example being the Identity EBook.

**Comment by patrick727** [comment]
@kennyrowe I dont remember if I had expressed interest in the executive and governance committee but Id like to make that clear. I think @kitblake and @ian would also serve well together along with me.

**Comment by kitblake** [comment]
@kennyrowe Yes, we discussed this in today's Member Meeting. FYI, I just filled out the form with executive committee checked.

**Comment by kdvalentine** [comment]
@kennyrowe I also have an interest in serving on the governance committee.

**Comment by jimscarver** [comment]
I signed up for governance committee last week. Is it true that the deadline for nominations was yesterday?

**Comment by patrick727** [comment]
@jimscarver yes the deadline was yesterday and @kennyrowe we should publish the list of interested members so that everyone can have an idea before the vote

**Comment by kdvalentine** [comment]
@jimscarver @patrick727 I was not aware of the deadline, though of course I assume there was one. I didn't see that information published in the membermeeting2017 channel. Where was this information shared?

**Comment by kdvalentine** [comment]
Or at least I would expect that information to be posted here.

**Comment by kennyrowe** [comment]
Member Committees are a volunteer position. The meeting is meant to facilitate the formations of the committees, not an election of members. Once the committees are formed they will self-govern. Each committee will have a few task assigned by the board, but they committees will also have the freedom to approach the board on their own.

Here is a working description of the committees.

**Executive Committee:**  [Proposed Chair: Evan]

The role of the Executive Committee is to implement the Board's fiduciary, strategic, and generative plans, policies, and decisions consistent with the Cooperative's vision, mission, and guiding principles.

**Nominating and Governance Committee:**  [Proposed Chair: Greg]

Identification and selection of directors, officers, and other important roles in the Cooperative, subject to Board approval. Oversee selection of Executive Committee general membership. 

**Compensation Committee:**  [Proposed Chair: Kenny]

Draft and negotiate compensation packages for directors, officers, and other important roles in the Cooperative. The compensation committee is solely responsible for director compensation. All other compensation packages are subject to Board approval (i.e. officers, other roles).

**Comment by kitblake** [comment]
@kennyrowe I think everybody, myself included, thought that people who volunteered to serve on a committee using the form would end up on a ballot. Then the seats on the committee would be filled  via voting. 

How do people who aren't physically at the meeting participate in the facilitation?

**Comment by kennyrowe** [comment]
@kitblake If someone who is not at the meeting filled out the form, the chair of the committee will follow up with them.

**Comment by kitblake** [comment]
I was hoping to participate in the decision about the proposed chair. 
Will everybody who volunteered end up on the committee?

**Comment by kennyrowe** [comment]
@kitblake the chairs are only proposals. At the meeting, a chair can and should be appointed. Yes everyone who volunteers will probably be on the committee, but keep in mind that as soon as the committees are formed they are self-governing. This means they will be responsible for creating their own rules about membership in the committee.

**Comment by kitblake** [comment]
@kennyrowe Thanks for the clarification. Self governance in such a group is a good thing.

I would gently suggest (vote?) that we make that form deadline a soft one, as some motivated players like @kdvalentine didn't hear about it.

**Comment by kennyrowe** [comment]
@kitblake I always intended the deadline to be soft. Deadlines help get people motivated though :) 

@kdvalentine (and other motivated members) will be welcome for sure

**Comment by lapin7** [comment]
I cannot imagine that such deadlines are very strict. It depends as always on new insights ;-)

Best,
HJ

**Comment by entropee** [comment]
After the discussion in the emails about not serving on more than one committee. I choose the Compensation committee. It has the fewest members, also.
