### ISSUE TITLE
Maximum Number of Tokens for Circulation

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#119]
Token Governance
Maximum Number of Tokens for Circulation
200m / 220m / 300m / 500m

Date is needed?

**Comment by djrtwo** [comment]
These suggestions are not including any future inflation, correct?

**Comment by jbassiri** [comment]
How is this different from a burn?

If tokens are not in circulation (and they are not burned) then they are in the Coop. 


-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by lapin7** [comment]
All tokens should be available for market circulation. The idea is simple. The token get's only USD value when there's enough market cap and market volume. So we have to find ways to distribute all the tokens to as much persons possible. If possible in a way that makes sense, like rewards for: work or investments made for running a node.
