### ISSUE TITLE
Use Docusign for signing documents.

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#120]
We have now several documents that need a signature of either one person or more persons:
- [SoW](https://docs.google.com/document/d/1MH-wHbLy_4KSjQeyd5bJNwCS6mGYsuXEA8q4GyooAwY/editP)
- [W9 tax form](https://www.google.com/url?q=https://www.irs.gov/pub/irs-pdf/fw9.pdf&sa=D&ust=1507471167994000&usg=AFQjCNEbXCPjmkmAvOiIrgH8trSWW0zE4Q)

So we don't have to paste a Signature.jpg in documents anymore.
Evan is in takes care of the process

**Comment by jimscarver** [comment]
You do not need to use Docusign to sign documents. You can sign in a google
doc by Insert Drawing, and Line, Scribble tool before exporting as PDF or
using Adobe acrobat, Tools, Sign.

**Comment by Ojimadu** [comment]
Don't you think signing documents digitally would be easier to verify?
