### ISSUE TITLE
User Stories - Exercise

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#121]
It would be awesome and effective to do a 10 Minute exercise with all the attendees and have everyone fill out(can be anonymously) there idea for Persona's and Stories for people that will use RChain. 

Also, It seems like it be a cool way of getting the juices flowing to at the beginning of the meeting.

**Comment by Ojimadu** [comment]
Can you explain this a little? Does it involves writing a draft?

**Comment by patrick727** [comment]
@Ojimadu it involves drafting up something like another survery on survey monkey to send out and print out for people to fill in at the meeting.

**Comment by Ojimadu** [comment]
I earlier thought this activity would be for those physically attending the meeting. It's kind of late but here is something https://goo.gl/forms/TEDRnDKIUe1LQLvo2

**Comment by patrick727** [comment]
@Ojimadu I like this form and it could prove useful. 
I also wanted to see stories written like a paragraph or two explaining a user experience.
