### ISSUE TITLE
Sync Community Process

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#123]
It would be nice to block off a bit of time to get everyone in sync with some of the community process and intial boost to get them going. 

this could include the budget voting and allocation sheet that @lapin7 has done such a good job initiating as well as the social ledger trial that I shamefully have not spent enough time on lol.

 @jimscarver @kitblake @kdvalentine @lapin7 will you be in Seattle for the members meeting?

**Comment by lapin7** [comment]
@patrick727 
Please don't forget to set a budget and to set rewards for this issue.
You can do that through the Gsheet [Pub Member Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=2052218093)

**Comment by patrick727** [comment]
@lapin7 I apprecate your dilligence but this is a proposal for the members meeting. I dont see how it would need a budget, maybe I can just set the budget to 0

**Comment by kdvalentine** [comment]
I will be there. What are you thinking in terms of timing?
