### ISSUE TITLE
M> RChain fans website in chinese

### ISSUE THREAD

**Issue by sportshark** [rchain/Members#126]
As we all know,China is a big market ,well we should build a Rchain fans website in chinese and publish news on the website  in Chinese.

**Comment by sportshark** [comment]
I am planning to do it

**Comment by patrick727** [comment]
@sportshark nice! yes please do, @Rafkraft and I are working with a designer right now for website redo we could coordinate on that issue

**Comment by sportshark** [comment]
@patrick727 Great! where are you from? and How can I add the issues to the buget?

**Comment by lapin7** [comment]
​Thanks for adding Issue #126 Rchain fans website in chinese
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fissues%2F126&si=5281391242641408&pi=da4a9b9d-3af2-4d04-e77c-64fa68600bf6>
I will add it to the spreadsheet Pub Member Budget Allocation-Spending
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o%2Fedit%23gid%3D2052218093&si=5281391242641408&pi=da4a9b9d-3af2-4d04-e77c-64fa68600bf6>
And then you can allocate a budget to #126. Please note that you have to be
at least 3 members to set the budget.

--
Cheers,
HJ

**Comment by sportshark** [comment]
@lapin7 what is the meaning of "Please note that you have to be
at least 3 members to set the budget.",doese it means "The budget should be finished by 3 persons at least"? But as you konw ,there are no chinese to help me in the rchain members. So,do I have to find other 2 chinsese members together?

**Comment by jbassiri** [comment]
Andi I like this project and I will vote for it don't worry. Between you, me, and HJ that's 3 (I'm sure there will be others too)

-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by sportshark** [comment]
@jbassiri Thank you very much!Hope to cooperate with you happily!

**Comment by sportshark** [comment]
I have bought the domain name "rchain.vip" as the chinese fans website domain name

**Comment by jbassiri** [comment]
I like the sound of that a lot. Bravo


-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by lapin7** [comment]
Probably we have to choose an scheme for translated sites, like:
cn.rchain.coop  China
fr.rchain.coop  France
de.rchain.coop Germany
nl.rchain.coop  Netherlands
or 
rchain.vip has to recognized as an official site of rchain.coop
or
rchain.vip is just a individual initiative.

We also need to know if there is a local population that is interested in reading rchain-stuff in local languages. It could be measured like the number of Chinese on discord. See for example the conversation in channel #chinese : @sjcare, @kumavis seem to understand Chinese, 

@sportshark you can try to contact on github: @npk 

There are a few other Chinese persons, but they didn't accept the invitation for Github/Members.

These things have to be clear before we start translating. And the goal is to get a team together, because translating can not be a one-person-effort.

**Comment by sportshark** [comment]
There are so many domain names.eg.rchain.cn,rchain.info,rchain.top.So do not care of it.
@lapin7 well many people just want to invest the project , so they do not care what to do next.
After that, I will set up QQ group, WeChat group and so on for Chinese Fans

**Comment by patrick727** [comment]
@sportshark great thanks, i also backed the issue so thats 4 and your definitely going to be rewarded once the work is done. 

That does not mean that you need 3 other people to complete the task, its only to determine the budget. 

Awesome so if you do a good job and feel like engaging with the chinese community more through those channels, i suggest also checking out the "community drivers" issues and working out an SOW for that. 
https://github.com/rchain/Members/issues/115#issuecomment-334952062

**Comment by sportshark** [comment]
I am a newer for RChain Members ,Great Thanks to @patrick727 @lapin7 @jbassiri ,I will learn how to wolk with other members to get the job done.
I've added a working folder to record the work progress and work status,you can see it [Fans website](https://drive.google.com/drive/folders/0B4unBXRXuKesQ09iVDRvcE43YzA?usp=sharing)
One of these files is used to record weekly work reports,you can see it here.[Chinese website](https://docs.google.com/document/d/1TNIuydQ79Y2EcUWroYDIVuzPR8dTl86qnp8rSfZktp8/edit?usp=sharing)

**Comment by lapin7** [comment]
Great.

Please move the folder Fans Website to Translation
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F0BwX0krsxHncTLWc5eU1qaEkyR2c&si=5281391242641408&pi=00c22417-6fe2-4f48-8701-6db6d5c53811>

Thx.

--
Cheers,
HJ

**Comment by sportshark** [comment]
@lapin7 OK ,I have moved the folder to Translation

**Comment by sportshark** [comment]
**Weekly report(October 9, 2017---- October 15, 2017)**
(1)	Familiar with the workflow, read RChain related documents, participated in GitHub, Google group and other organizations
(2)	Put forward the idea of establishing Chinese fans website and communicated with some members
(3)	Designed website architecture and evaluated NODEJS technology solution.
(4)	Based on nodejs, built and test the Ghost, Keystone, DoraCMS technology framework.
**Weekly report(October 16, 2017---- October 22, 2017)**
(1)	Bought domain name “rchain.vip” for website
(2)	Designed website architecture and evaluated JAVA technology solution.
(3)	Based on JAVA, built and test the JFinal, EmpireCMS technology framework.
(4)	Evaluated PHP technology solution, test the Wordpress technology framework.
(5)	Set up webchat group for Chinese fans.Manager:Eason.Webchat Num:chenlee1116.

**Comment by patrick727** [comment]
@sportshark  awesome work Andy I look forward to seeing your continual work on this.

**Comment by sportshark** [comment]
@lapin7 I agree with you about domain names. So if need, I can get RChain officials to use "rchain.vip"".

**Comment by sportshark** [comment]
**Weekly report(October 23, 2017---- October 29, 2017)**
(1)	Bought a VPS as the website server
(2)	Through testing and comparison, the final decision was based on PHP, using WordPress as template to build website.
(3)	Configured VPS server environment
(4)	Installed PHP7 running environment
(5)	Installed FTP tool and configured environment
(6)	Installed Nginx server and configured environment
(7)	Added a working folder in Google Docs to record the work progress and work status
(8)	Installed Mysql sever and configured environment

**Comment by lapin7** [comment]
Great.
Is the budget high enough?

URL | Status | Project / Issue | Category | Votes | Last month | Left over | $ Oct Budget | ⍴ Oct Budget | Current Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[126](https://github.com/rchain/Members/issues/126) | New Issues | Rchain fans website in chinese | Marketing | 4 | $ - | $ - | $ 2,050.00 | ⍴ 10,250.00 | $ 2,050.00 | @sportshark @kitblake @lapin7 @patrick727
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Maybe you can send me the invoices/receipts of your expenses.

**Comment by Rafkraft** [comment]
Very cool news in here :)

It has been said earlier, I'm currently working with the designer to build the alpha public website (rchain.coop). I'll take in consideration the fact that it must be multi-lingual.

We do not necessary have to handle multiple domains (fr.rchain.coop, en.rchain.coop etc...). We could have a toggle in the upper-right corner and the user switches from one language to another (of course it will be stored in localStorage, user wont have to set it up everytime).

**One important note:**
I'll be working on the public, static website, in general the blog resides on another url (blog.rchain.coop for example), I'm not working on the blog at the moment, but it could be a wordpress blog (or another CMS, @sportshark seems to know that stuff ), and I think there are some modules that handle multi-lingual content.

On my side, I'll work on easy multi-lingual support for the public static website.

**Comment by sportshark** [comment]
@Rafkraft Thank you for your encouragement! I will use Wordpress in chinese fans website ,maybe I can help you.
@lapin7 Thank you for budget! I'm going to set up this website in November. In order to save costs, only one low performance server is currently purchased. After more users access, we can spend money to purchase high-performance servers.

**Comment by Mervyn853** [comment]
@sportshark Hi Andy, I've created the  RChain Coop Chat Group at 
https://t.me/RChain_Official_Chat and an RChain Coop Announcements Channel at 
https://t.me/RChain_Official.

I'm based out of Singapore and am fluent in Mandarin too. I've created a Mandarin telegram channel here : https://t.me/RChain_Official_Chat_CN for public communications and would like you to join me in managing the community. 

Also, I would like to check if you will be having a official Chinese language term for RChain or will we be using RChain consistently across all the different language communication channels?

**Comment by kitblake** [comment]
Actually there's a discussion going on in Discord that isn't clear yet. Sorry, I should've said something. I wanted to wait until the monday workday to get consensus.

One of our goals is to have all the social media channels use the same characters. Each network has one or more 'punctuators' that are allowed. On Twitter you can use an underscore but not a hyphen. Since the underscore is a given, we should use it everywhere. So on Medium, which also accepts hyphens, we use the underscore.

Then we have:
Twitter: https://twitter.com/rchain_coop
Medium: https://medium.com/rchain_coop
Telegram: https://t.me/rchain_coop
etc.

We will also want to have RChain_Official on certain platforms like Reddit:
https://www.reddit.com/r/RChain_Official/

@Mervyn853 created an RChain Coop Announcements Channel at:
https://t.me/RChain_Official
which will be useful. 

For community activity I think we should use https://t.me/rchain_coop. We might use RChain_Official_Chat for some future purpose too, but it's important to be consistent in the naming, keep it short, and have names that are easily pronounceable and typeable.

**Comment by sportshark** [comment]
**Weekly report(October 30, 2017---- November 5, 2017)**
(1)	Installed WordPress and configured environment.
(2)	Learn how to use WordPress.
(3)	**Set up QQ group for Chinese fans.QQ group num: 530718666, By November 1st, there were 185 people.**
(4)	There were too many WordPress Themes, and about 16 themes were downloaded for testing and comparison.
(5)	Use BEGIN as the website theme finally.
(6)	Get the picture resources of RChain.
(7)	Bought domain name “rchain.site” for website
(8)	Configured DNS of domain name for the website

**Comment by sportshark** [comment]
@Mervyn853 @kitblake 
So far, the Chinese community has established QQ group, there are currently 187 people, group members are rchain enthusiasts and investors, Ethan and I are responsible for management. Webchat group has been established, there are currently 23 members. Eason and I are responsible for management.
--------------------------------------------------------
Chinese QQ group num: 530718666
Chinese Webchat : chenlee1116 
--------------------------------------------------------
I think the official media needs a unified design. In addition, communities of different languages need to have their own fans websites that can be used to publish unofficial and interesting information. Similar to all of the Ethereum fans websites. At the moment, what I've built is a fans site, and it's rich in content. 

I will assist with the Chinese interface of the RChain official website and meet the requirements of the official design.

**Comment by kitblake** [comment]
@sportshark Yeah, a unified design is a must. Currently work is being done on a new website design (ref #156 and the #rchain-websites-dev channel on Discord). We will probably be able to use elements of that. 

@patrick727 This is something to keep in mind with the design. We'll need assets, like backgrounds and images, that can be used on these co-operator driven platforms. We already have logos and such in https://github.com/rchain/style_guide_and_files. So (approved) assets should be checked somewhere into Github too.

**Comment by lapin7** [comment]
@sportshark I saw that RHOC can be exchanged also at:
https://ex.singularx.com/exchange/RHOC/ETH

Nice.

**Comment by sportshark** [comment]
@lapin7 hello，My friend 毛壮壮list RHOC on the https://ex.singularx.com/balance, and he has a very good relationship with the management organization of this website.The manager of the website has joined our private QQ group.

**Comment by kitblake** [comment]
@sportshark That's really positive. I posted about Sx in #29 which is linked from the FAQ.

**Comment by sportshark** [comment]
**Weekly report(November 6, 2017---- November 12, 2017)**
(1)	Learn how to use WordPress
(2)	Added website top menu, uploaded website icon and LOGO
(3)	Designed the sidebar, home page, menu and bottom page of the website.
(4)	Classified the website column content.
(5)	Finished the home page style design and coding
(6)	Finished the main menu design and coding.

**Comment by sportshark** [comment]
**Weekly report(November 13, 2017---- November 19, 2017)**
(1)	It took some time to move the site from rchain.vip to rchain.site., and solved several bugs in migration
(2)	Installed BBR for VPS server, BBR (Bottleneck Bandwidth and RTT) is a new congestion control algorithm which is contributed to the Linux kernel TCP stack by Google. With BBR in place, a Linux server can get significantly increased throughput and reduced latency for connections.
(3)	Finished the text page design and coding
(4)	Finished the sidebar design and coding
(5)	Finished the bottom page design and coding
**(6)    Now you can view the draft of website Http://rchain.site**

**Comment by sportshark** [comment]
**Weekly report(November 20, 2017---- November 26, 2017)**
(1)	Completed contact details, animation effects and other details.
(2)	Completed SEO settings.
(3)	Added exchange links for RHOC
(4)    Published Newsletter 11.16 in chinese.
(4)	The first version of the website can run now. Now chinese fans are getting info from it.
Http:// rchain.site

**Comment by sportshark** [comment]
Hello All, 
So far, the site of rchain.site has been running and serving Chinese people. Thank everyone for help. The next step is the operation and maintenance of the site. Please see https://github.com/rchain/Members/issues/173
If everyone has no opinion, I'm applying for closing the Issue and running http://rchain.site on the line.

**Comment by Ojimadu** [comment]
We can close the issue and focus on #173

**Comment by yuhuanmocmoc** [comment]
I'm a little confused, what's the different between #126 and #173? They all have been existing for several months.

**Comment by sportshark** [comment]
@yuhuanmocmoc  #126 is for buliding the website ,#173 is for the operation and maintenance of the website. The #173 is started  after the #126 is closed on Dec 2017. Since February 2018, both #173 and #126 will run free of charge.
