### ISSUE TITLE
automate google group addition

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#14]
The member form should tigger addition to the google group. Google script needs to be written or email generated for processing by a mailbot. [form processing](https://developers.google.com/apps-script/quickstart/forms), [Admin SDK Directory Service?](https://developers.google.com/apps-script/advanced/admin-sdk-directory), [mostly free forms addons](https://ctrlq.org/)

**Comment by lapin7** [comment]
I will take a look at the Google scripts. Maybe I can program something.
HJ

--
Hendrik Jan Hilbolling
lapin7@gmail.com
+31.650.291.532

**Comment by jimscarver** [comment]
I stubbed out group member addition in the script editor minus the oauth2 client authentication.
```javascript
function addGoogleGroupMember(group_email, user_email)  {
  client = gdata.apps.groups.client.GroupsProvisioningClient(domain=settings.DOMAIN)
  client.ssl = True
  client.auth_token = gdata.gauth.OAuthHmacToken(settings.OAUTH_CONSUMER_KEY, settings.OAUTH_CONSUMER_SECRET, access_token.token, access_token.token_secret, gdata.gauth.ACCESS_TOKEN)
  client.AddMemberToGroup(group_email, user_email)
  // client.RetrieveGroupMember(group_email, user_email)
}
```
It looks like we may need a google organization domain for this to work. 

This would be triggered on form submission. We may have an issue dealing with multiple submissions.

**Comment by lapin7** [comment]
This "GroupsProvisioningClient" has a lot links:
Like https://github.com/google/gdata-python-client/commit/8a7a9289801d10eff78b7d9226488a31ad70bc55
I don't know really what do with it.

**Comment by jimscarver** [comment]
I invited the first 10 members who filled out the membership form to our google group https://groups.google.com/forum/#!forum/rchain manually.  I probably should have done a "direct add" instead. I also set an initial welcome message.

**Comment by kitblake** [comment]
HI, I'm one of those first 10. 

When you accept the invitation you get sent to a simple Google page confirming that you joined (made a screenshot in case anybody's curious). Clicking the Group name in a text link takes you to the Group. Which has an inspiring welcome message..

Kit Blake

**Comment by jimscarver** [comment]
I have continued inviting members to the google group manually. HJ has added them here in github. We need some javascript/googlescript learners to automate these things. I can coach them. I think learning to work together is important. Alternatively we can just put bounties on these things and hope somebody bites.
We can have a separate issue for adding to gitlab but both are enhancement to the processing of a google prereg form submission.

**Comment by lapin7** [comment]
Good idea Jim,
Please make an issue on Github for this.
Also can we through the Google group make a general message to stimulate
people to take up tasks for solving Github issues?

--
Cheers,
HJ

**Comment by jimscarver** [comment]
I have added all the emails in the activist registration sheet which has been retired and replaced with the new member registration process.
I have received a request to join the group but cannot confirm they are a member.

The group has been underutilized but I suggest it should be maintained. Having an email alternative for members to reach out to one another is an important channel to have as a compliment to discord and the only way members communicate not active in discord outside officiel coop bulk emails. Email connections are important for working together.

We need a new process @lapin7 to get members in the google group.

**Comment by lapin7** [comment]
I agree.
Email is essential.
And we will (sometime) find a way to get the group operational.

--
Cheers,
HJ
