### ISSUE TITLE
M> rchain.coop v.3 - cooperator feedback

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#156]
This is to aggregate comments from the cooperators about https://rchain.fabco.tech/ which will be the next website iteration. 

Goal: Re envision the rchain.coop to include new information funnels for beginners edu, developer edu, events, and membership.

**Comment by patrick727** [comment]
The top graphic has a past-(present)-future look. A switch from mechanical age to network age. (I put present in parens because unless it's that cylinder I don't really see a present, just past-future). I like the green-orange colors.

The "Key Value Proposition" level is kinda white and weak. The borders and text needs to be darker to be better legible. Maybe an image in each box. Something....

The images in "Dive Into the Tech" are mixing mechanical and network effects. Assuming that's a theme we want, I think it works. The image for Multi-chain might be overly mechanical. 

The "Roadmap" level also needs enhancement imho.

Before I dig further, this site is meant to replace rchain.coop, yes?

**Comment by patrick727** [comment]
More feedback from discord
"Will there be a website redesign before the main launch?
Don't have access to post in the website-dev channel. So here is some feedback, if someone could please relay this to the right channel. On https://rchain.fabco.tech/  :

Don't like the green-orange gradient at the top. Also not clear what the main image represents. Old to new tech? Middle white section, value proposition, is weak. Lots of dead space. Lack of cohesiveness overall. A strong cohesiveness in a website can be developed by utlizing a strong color scheme which uses one overall hue with a few complimentary accent colors. This further enhances the message you want to convey to the audience. A great example of  a clear and cohesive website design (in my opinion) is https://iohk.io/"

**Comment by patrick727** [comment]
Hello @ValeBF you're in now!!!

@Rafkraft, and Valeria keep in mind that we don't necessarily need to follow all feedback, just read through the comments and we can meet about any points that we consider to be change-worthy.

**Comment by Rafkraft** [comment]
Today I uploaded the new /about page i worked on with Valeria, and some updates on the footer and home page.

https://rchain.fabco.tech/about

I also set up the structure to handle multi-language properly, when all texts are ok, it will be easy to set up a chinese version, accessible with an argument **?lng=cn** (for example) at the end of the URL.

**Comment by patrick727** [comment]
@rafkraft great work thank you!

I will make it a point in the near future to start working on content for you to use in the website. 
Shouldn't take much time.

**Comment by patrick727** [comment]
@Rafkraft and @ValeBF  this is Steve @bjornagain!

he has been contracted by pyrofex to work on rholang.rchain.coop so we should keep in the design loop as well. 

Cheers

**Comment by patrick727** [comment]
The nav on the site should be updated as follows

"Home | About | Dev Portal | Documentation | Join Now"

The first call to action may need to be changed from whitepaper but either way we will need it "above the fold" meaning that the person should not need to scroll down at all on there device to see it

**Comment by patrick727** [comment]
The bottom under "social media" we could change to "Quick Links"

and put the following

FAQ - icon with a ?    Medium -
Youtube -                  LinkedIn -
Twitter -                    Telegram - 
Reddit -                     Github - 

possibly hackernews

**Comment by Rafkraft** [comment]
I worked on general design issues on https://rchain.fabco.tech today.
https://rchain.fabco.tech

@patrick727 I'll work on your last remarks very soon !

**Comment by Ojimadu** [comment]
I think the 
1. RChain logo should be clickable and lead to the home page
2. The colour combination is rather too simplistic. Just a dark (black?) colour and white produces a stark contrast which imho is too bold. A play of three to four colours blending into each other would create a better flow (a colour wheel might help here). Also I'd recommend this read http://www.vandelaydesign.com/the-psychology-of-color-in-web-design/
3. The website is quite too static, I think a little gamification like hover text, scroll spy, carousel and some unique animation would be make the site look fluid and interactive.
4. The website does look nice on mobile. It is not fully responsive.
5. I thinks there should be a kind of news and media section on a part of the homepage where stuffs like videos and rchain related news can be uploaded/embedded.

**Comment by Rafkraft** [comment]
Modifications:
- Top logo is now cliquable and leads to the home page (@Ojimadu ). Moreover I put it on the top left corner as @patrick727 guesses, I think it's a good idea.
- Sections have been renamed/added.
- Footer: "Social Media" -> "Quick links".
- @Ojimadu I added some animations on some content (team members, grey square on home page).

Regarding the colors, I find it harmonious now and wont give any modification (only three colors, we had four at first) that hasn't been approved by @ValeBF .

Regarding the twitter feed / dynamic content section, it is planned of course, I asked about it and was replied that we will add it later.

https://rchain.fabco.tech/

**Comment by patrick727** [comment]
Thanks @Rafkraft for moving to in progress. 

I like where it is going.

I think we can make the first tile shrink some though, so that the image links to it top to bottom(right now there is space between the top and where the image begins)

also the rchain cooperative needs "cooperative" and could be aligned up more, which goes with the tile 1 being a bit smaller.

does that make sense? 

thanks for the great work

**Comment by bjornagain** [comment]
Hey folks nice to make your acquaintance! 
I'll be working on http://developer.rchain.coop/, as well as some other web work for pyrofex. I am also available to help out here with https://rchain.fabco.tech/.

Can someone tell me if we're going to be using the styling from the new site in progress, or what is currently live at rchain.coop?

**Comment by ValeBF** [comment]
Hi there ! 
I have worked on some design editions for rchain.coop I been approaching all your comments in order to build a better site that follow a global stethic that we are trying to usea across the brand elements. Also I did some editions on the graphics in order to follow some suggestions from  #145 issue.

I would like to know your thoughts and get the approbal on this desing to give @Rafkraft green light to complete the development and avoid waste of his work and time... building and edditing (bis)....

Here is the mock up link

https://preview.webflow.com/preview/rch-35ecec-60ff624c600ad0-19929651c1568?preview=dcefe7e5fde1fbd916ce9ab08c7f34b2

You should click on the little eye on left- top
<img width="179" alt="screen shot 2017-12-04 at 1 23 24 pm" src="https://user-images.githubusercontent.com/33433916/33566439-6641932a-d8f6-11e7-8838-1ed3ef9cb5b4.png">



I will remain attentive.Thanks . VBF

**Comment by patrick727** [comment]
Thanks for this @ValeBF 

Tile 1

- can you lift the RChain logo and call to action of whitepaper up about 10-15 points so its a bit more center. 
- its "white paper" you have "withe paper"
- can you have the background mesh art faded into the background a bit more, and also will you make the size of the circles vary sum. maybe experiment with some different colors to demonstrate different size nodes connecting. 

see this simulation of how the nodes will actually interact. 
![casper](https://user-images.githubusercontent.com/26626639/33566939-6cb34430-d8d6-11e7-8c10-b2ed3ba7da98.gif)


Tile 2
- Also the background can you experiment with different size/color circles for he meshnet and make it fade a bit more into the background

Tile 3
- please have the title and description higher up on the tile(i.e "Rholang + description" closer to "dive into the tech")
- i really like how you can scroll between the different tech specs, great work.

Tile 4
- Roadmap looks great to me, maybe different sized circles for the background and will double check on the milestones

Tile 5
- LinkedIn is one word. 

Really great progress thank you!

**Comment by ValeBF** [comment]
Sorry for my  bad spelling .... 

I edited what you pointed thanks.  I left out the mesh net graphic edition, I will work on it... thanks for sharing that simulation, great visual reference to use.

Did you check the ABOUT page ? there are some changes too.

**Comment by patrick727** [comment]
Thank you and I didnt, but I will and get back to you. thankyou

**Comment by Rafkraft** [comment]
I everyone, I read the last post

As @ValeBF I'll wait for green light from @ValeBF and @patrick727 to get this coded.

Today I worked on social integration of the website (for facebook and twitter). I added every facebook and twitter metatags (basically title, image and description).

You can have a look here -> https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Frchain.fabco.tech%2Fabout

At the moment we have just one image for every page, we can totally have one for each page (dimensions must be 1200x600 for facebook, and another image at 600x314 for twitter). I chose arbitrary some titles and descriptions to appear on facebook and twitter, I guess it will change too.

**/about page**
https://rchain.fabco.tech/about
I copied some team member descriptions from https://rchain.coop, the missing ones are still Loreum ipsum...

**About translations**
@patrick727 if you whish we can totally have a document where every translation of every part of the website is written, this way, when translations in english are ok, we just send this document to the translators and they send us back the translations. Do you think I can work on this document template ?

**Comment by patrick727** [comment]
@Rafkraft great work  on the social and about page. 

under Cooperative Governance, we will need to clarify the profile and descriptions are the "Board of Directors"

I will start focusing on copy for website soon and provide you with those wordings. 

That's a great idea for the documentation page. 

Let's create a separate issue for that within this "website" project for that.

**Comment by patrick727** [comment]
quick side note: @Rafkraft I can create another issue if this is works out, but would there be a way to do a similar plugin translation option for the RChain Developer wiki https://rchain.atlassian.net/wiki/spaces/CORE/overview ???

**Comment by Rafkraft** [comment]
The translations document has been done. 😃 Now we'll just have to fill it 😄 

Concerning the wiki website and dynamic translations, I don't really know how this atlassian wiki works... If a wiki will be developped like rchain.coop (wiki.rchain.info for example), I guess the developper will figure out how to handle dynamic translations.

**Comment by patrick727** [comment]
@Rafkraft I inputted a bunch of content to the doc and still awaiting some confirmations for other portions. 

[The latest website preview can be found here. ](https://preview.webflow.com/preview/rch-35ecec-60ff624c600ad0-38511c9c61961?preview=a090150234e29526c189d1e0a418907d)Note the color pallete will change, think more about the layout and what color pallets you'd like to see.

**Comment by kitblake** [comment]
The new logo looks superb in the website context! I think #3 is a keeper.

**Comment by Rafkraft** [comment]
Very cool stuff !

I'll work on these new designs and texts very soon, then I'll give an update here !

**Comment by Rafkraft** [comment]
Multi-language is now stored in cookies, and can be overriden with the URL parameter **lng=**
I added german support just to show how it works:

https://rchain.fabco.tech/index?lng=en
https://rchain.fabco.tech/index?lng=de

Visit the two, you'll see the language change (upper right corner with the flag), this happens on the server side (html page is initially loaded with the correct texts).
You can also change the language manually by clicking on the flag, this happens client-side (texts are changed dynamicaly when language changes).

At the moment we have no traductions in german, later you'll have the content changed of course !

Everything is setup for multi-lang support now ! So I'll put my efforts on the new design and carrying changes the texts too.

Have a good year,
Back to you very soon ;)

**Comment by kitblake** [comment]
Great news about the multi-language options!
Can anybody recommend a translation tool or site? By that I mean a website/service where you put up the English strings, and then others can translate them one to one. I've seen these in action but never used them, and  they're much more friendly than editing i18n files.

**Comment by Rafkraft** [comment]
I worked on a google doc that I called "tanslations document - EN", it contains all texts and sentences that appear on the website, when it's filled and finished we will create CN, DE and other documents to handle the translations.

I guess this document has not been shared with you since I don't have your mail address :/ (right now it's editable by @patrick727 and @ValeBF)

Maybe there is a better workflow but ATM we are working with this document to handle the changes and it's fine !

**Comment by Ojimadu** [comment]
Cool stuff @Rafkraft. You have a very good idea creating the "translation documents" it would come handy for translations and would ensure consistency.
@kitblake Peer translations or paid translation services offered by companies?

**Comment by kitblake** [comment]
I mean peer translations. But I just spent some time searching and I can't find the tool I once saw. It was a web-based service that made it easy to translate website or application text. You upload the English strings, then volunteer translators select a language to translate into, say French. 
In the UI the English strings appeared on the left, with textareas on the right for the French version of each string. 
Underwater the translations were saved in the proper (i18n .po file) format for use in the app.

**Comment by tet123** [comment]
You probably mean something like:
https://locize.com
or
https://www.oneskyapp.com

**Comment by dckc** [comment]
The body text font size is quite small. Chrome dev tools tells me it's 0.9em. Shouldn't it be 1.0em by definition?

**Comment by dckc** [comment]
What is the goal of this redesign?

**Comment by Rafkraft** [comment]
Yeah locize seems like a very good and powerful tool, on rchain.coop I'm working with **i18next** at the moment, this tool seems to be compatible and provide options for it. I'll check it more deeply and maybe open an account.

@dckc ok your remark about font-size is wise, I think I'll shrink default body text to 1.0em.

**Updates:**
- I brought some updates on https://rchain.fabco.tech/about , although some pictures are still missing.
- I also integrated https://rchain.fabco.tech with the rchain UI kit I worked on few weeks ago (https://rchain-ui.fabco.tech/).
- Next step is the homepage, some serious changes have been made to it, it'll be done soon.

Cheers all

**Comment by Rafkraft** [comment]
In order to track daily conversions/clicks on buttons/audience, we need to setup an analytic solution, the default one is Google Analytics, I've set it up on many website already and know how to work with it.

Has anyone ever used Heap ? https://heapanalytics.com/ Seems to be a great tool (and even easier than GA), maybe we could use it instead of google analytics.

@patrick727 any thought on this ?

**Comment by Keaycee** [comment]
Great work @Rafkraft and @ValeBF . I think we are making progress and things are really taking good shape. Accessing this site on a pc really look responsive but static. But on the mobile aspect, the web design is not responsive. The mobile view is also very important in this present age because individuals prefer to access site more on their cellphone because it's handy. The blockchain site is very responsive in both side and lots of individual access it through their cellphone because it's portable and handy.
I also think the website look too static and lack some elements that will help gamify the site so it could look more interactive. However it's a good work keep it up..

**Comment by patrick727** [comment]
@Rafkraft we could try heap, i've never used it as i'm used to the default GA and GTM's 
@Keaycee thoughtful points
@ValeBF coudl you share the latest preview here?

**Comment by dckc** [comment]
Whatever surveillance technology we employ, **be sure to disclose it plainly in a privacy policy**.

The current rchain.coop site uses google analytics without disclosing it. Very un-cool.

**Comment by Rafkraft** [comment]
@dckc You're refering to a small popup appearing on first visit _"We must inform you that we may track some events on this site to improve user experience, by staying on this website you accept to etc....."_ ?

**Comment by ValeBF** [comment]
Hey!  @Keaycee  here is the new design mockup https://preview.webflow.com/preview/rch-35ecec-60ff624c600ad0-8019ad6dae9fd?preview=87080441dc8fb8e15acae80e3f84e562
I have been working some editions and restyling 

I am attentive to any comments you guys have about this

**Comment by Keaycee** [comment]
@ValeBF @Rafkraft  You're doing quite a good job. But we would like to have a demo preview of your work. You need to include Privacy, Terms, Support (Help Center, Tutorials, Learning portal),  Company (About, Team, Career, Interviewing, Press, Blog & Faq), Product(wallet, Business, market) ETC. This is a good work in progress.  What do you suggest? @patrick727 @kitblake @Ojimadu

**Comment by Rafkraft** [comment]
Ok there are several changes, I'll build another UI kit (v1 is -> https://rchain-ui.fabco.tech/) since colors and general tone have changed (from **blue-green-pink** to **black-grey-pink**).

@Keaycee I guess @ValeBF and I are designing/coding two pages, and when we reach general agreement and agreement with the hierarchy, we'll do all the others. (in order not to re-code everything when the theme changes).

**Comment by patrick727** [comment]
@Keaycee the "dev portal" is the learning portal. 

"product" we will leave out for now as it may be a section in "about" for partners such as holdings, ventures etc and they can present their products. 

we can put a section at the bottom for "more" like status.im does and put "jobs" there but I dont believe it should be in the Nav or About because we do alot of outreach for jobs through our network and don't really need a flood of resumes at the moment, but that could change. 

@ValeBF , @Rafkraft this is looking really good, i'll have a couple more updates to the content soon and get back to you. much appreciated. 

I'll look more into how we can/should display that we are tracking cookies. ledger does a popup so maybe we will do the same.

**Comment by Rafkraft** [comment]
@bjornagain  https://rchain-ui.fabco.tech/ is just a UI kit, a styleguide in other words, this document explains how to use a CSS library I coded. Some other devs at Pyrofex will probably use it. (for developper.rchain.coop for example).

The problem is that the colors changed, so I must do a UI kit version 2 ^^

**Comment by bjornagain** [comment]
Sorry I meant to use this link: https://rchain.fabco.tech/

Is there a tentative deadline to get the redesign live on rchain.coop?

**Comment by patrick727** [comment]
@bjornagain the goal is to have it ready along with the developer.rchain.coop portal, so end of the month is ideal, best would be end of this week but that's more pressure then I think anyone wants. 

@Rafkraft I like the UI kit and the styles derived from it. 
@ValeBF could you weight in the color schemes of the new mockup? Which I think is looking quite nice as well.

**Comment by Keaycee** [comment]
End of the month is ideal but there won't be need for a rush while working on the redesign. Take your time for a better result  @ValeBF @Rafkraft .  some suggestion were made by @patrick727 .  Your work is great @ValeBF @Rafkraft

**Comment by Rafkraft** [comment]
RChain UI Kit version 2 is online ! (maybe you'll have to clean your cache)
https://rchain-ui.fabco.tech/

This is a I said few posts earlier, a CSS library to be used in every rchain.coop related projects, so everyone use the same components and have the same visual identity.

Of course I used the mockups done by @ValeBF as a model.
https://preview.webflow.com/preview/rch-35ecec-60ff624c600ad0-8019ad6dae9fd?preview=87080441dc8fb8e15acae80e3f84e562

https://rchain-ui.fabco.tech/

Now I'm working on https://rchain.fabco.tech/ , updating everything to match with the new mockups !

**Comment by Ojimadu** [comment]
@Rafkraft The UI kit version 1 and 2 has a small typo 'developer' is spelt 'developper'. It occurs twice there (or is that a style?). 
Nicework on the UI kit.

**Comment by Keaycee** [comment]
@Rafkraft  also check the year at the footer of https://rchain.fabco.tech/ is outdated, still says 2017. It should be updated with a script that automatically updates the year without having to manually change it every time we enter a new year.

**Comment by bjornagain** [comment]
How will the new site be handled on the backend?

**Comment by Rafkraft** [comment]
Draft for v2 is online ! 😃 
https://rchain.fabco.tech/ (clean your cache)

Of course it now uses the new **RChain UI Kit** I developed earlier :) (which I updated too)

**What is lacking:**
- Proper test on responsiveness (small devices). I checked regularly that everything rendered the right way on small devices, but I must have missed some details.
- Proper checks on old browsers, even if we might skip support for IE < 10 (IE < 11 ?)
- Add backgrounds on big sections : Valeria sent me mockups and background images, I'll add them soon.
- Analytics: Add a heap javascript tag (https://heapanalytics.com/) and register and account on the website, just to see if this works.
- Redo the social media thumbnails and preview images (since the colors have changed)

This is on my side, for other things like texts (still some loreum ipsum), and other pages, I'm waiting for the staff to give inputs and directions :)

Cheers all, thanks for your returns

@Keaycee footer date is ok now !
@Ojimadu I fixed it (my mistake, that's because in french we write "developpeur" 😄 )

**Comment by ValeBF** [comment]
hey! @Rafkraft I saw the editions you did on the website it is nice, but I am a little worried about the design details we want to include, I am not sure if I am been premature on your dev process but I would like to see implemented the assets I sent to be sure everything is fitting properly or if there is needed any edition. Please let me know if I am a step ahead waiting for the frontend to be ready now.

**Comment by Ojimadu** [comment]
@Rafkraft Nice edits on the draft but looks like @ValeBF already has some work for you

**Comment by Keaycee** [comment]
@Rafkraft nice work @ValeBF keep it up. The site is already taking a good shape. Good collaborative efforts.

**Comment by Rafkraft** [comment]
Ok I added the background images and as always fixed some stuff too. We're setting up a video/audio meeting with Valeria to keep on with the integration.

I added the HEAP analytics tag, so I can follow how much people clicked on that button/saw this page.

**Comment by lapin7** [comment]
@Rafkraft is it possible to create a self service page for members that collects personal data? The idea is that members would be able to maintain their own data. See also
#203  O> Profile page for Member/Activists and KYC

**Comment by Rafkraft** [comment]
@lapin7 
- Sign up/sign in interface.
- "my account" page/form with all the fields.
- The back-end (database storing the users infos, an admin interface to see users's data). Is this what you describe, are there some other stuff/pages needed ??

**Comment by lapin7** [comment]
@Rafkraft 
Exactly. A "My account page" with different sections in order to get the functionality for:
- updating personal data
- contracts and tax forms
- reimbursement of expenses
- overviews of work done
- creating and sending invoices
- joining conferences
- providing links to useful work, video's or whatever

**Comment by makys** [comment]
@lapin7 are we considering appropriate security and privacy controls for storing personal data?

**Comment by lapin7** [comment]
@makys 
Of course appropriate security and privacy must be respected.
That mean access to that data is for:
- the account self
- some functional coop folks
- no one else

**Comment by makys** [comment]
@lapin7 sounds good. 
Maybe add encryption of data at the back end. 
Develop a Privacy notice, so it is clear how the data will be used.

**Comment by Rafkraft** [comment]
Ok, I had some email conversations about member.rchain.coop , the backendwill be written in scala, I said that I don't have the skills for it, is there the same scala expectation for the backend of rchain.coop ?
If not I can code a Node js backend service or even link the front to a DB cloud platform like firebase
- Comments on this / technical advices ??
- Is it really necessary to encryt the database entries ? Rchain servers won't be secured enough ??

**Comment by kitblake** [comment]
Imho using Scala is overkill and Node.js is perfectly suited. 

But I’m not a dev and don’t wanna make a call on encrypting db entries. 

Maybe we should use a blockchain. NO! Bad joke! Not serious..

**Comment by lapin7** [comment]
It's ridiculous to go on with Scala for website maintenance. Let's press for change to Node.js ASAP with @n10n and @leithaus

**Comment by lapin7** [comment]
@tet123 please send a msg to ops@rchain.coop in order to get access to documents

**Comment by Rafkraft** [comment]
Just to sum where we're at for rchain.coop:

- The design is having its final modifications
- We are still waiting from inputs from the coop to replace all the "Loreum ipsum" texts
- Preview images for social medias will be ready soon :)
- Still a lot a fake links ont the website (social media links in the bottom for example)
- And then of course the other pages must be filled and integrated
- When all the pages are ready, we'll see which language(s) must be added and we'll start working with the translators.

**Comment by patrick727** [comment]
Thank you everyone for this wonderful input on the design process. 

This is how we are going to proceed moving forward with branding/web design

1. We are going to aggregate all of this feedback into a clear document of "community input"
   - I believe @pmoorman and @AyAyRon-P are going to help with that

2. we are going to contract a branding/design firm in Seattle to help take this feedback, along with the input from our developing PR Narrative, RChain Holdings, Ventures, and Pyrofex to develop a congruent brand imagery that can span across all organizations. 

3. I've requested test instance's for all of the RChain sites moving forward so that we can demo what changes we would like to see as a community so that its simpler to get approval. 

If there are better ideas please let me know. 
I'm going to close down this issue for now just to clean things up.
