### ISSUE TITLE
M> rholang.rchain.coop

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#159]
updated verzion of rholang.rchain.coop to be consistent with total brand imagery

**Comment by lapin7** [comment]
Development Progress

- The scala port of the Rosette VM is underway [here] (https://github.com/rchain/Rosette/tree/dev/rosette-scala/src/main/scala/coop/rchain/rosette)
- There's C++ code for the virtual machine under rchain/Rosette and the current grammar for the language is [here](https://github.com/rchain/Rholang/blob/source-to-source-rosette/src/main/bnfc/rholang.cf)
- There's a [Wiki](https://rchain.atlassian.net/wiki/spaces/CORE/pages/13992034/Open+Questions+-+Namespaces) on Atlassian, but it has no public access.

**Comment by dckc** [comment]
I would expect this to be part of dev.rchain.coop #177

Is it cost-effective to have a separate site?

**Comment by lapin7** [comment]
dev.rchain.coop #177 is better

**Comment by dckc** [comment]
Meanwhile, https://rholang.rchain.coop/ actually exists. So if we aim to merge them, there's work to do here.
