### ISSUE TITLE
Get Rholang Presentation video from Devcon3

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#166]

**Comment by Mervyn853** [comment]
https://www.youtube.com/watch?v=7tW1fAWg6s8  This was just published by the Ethereum Foundation and I have shared it through all the channels I'm in control of.

**Comment by Ojimadu** [comment]
You got your hands on it pretty quick. The video is a nice introductory video to Rho-lang smart contracts, explains some basic concepts. It is be worth adding to rholang.rchain.coop page.

**Comment by dckc** [comment]
@Mervyn853 nice! What are some of those channels, by the way? (I don't see any from your github profile.)

@patrick727 is this done now? Or should we follow up on putting it on https://rholang.rchain.coop/ ? Who is in a position to do that?

**Comment by Mervyn853** [comment]
@dckc Hey Dan, I have shared it to the following :   

https://www.reddit.com/r/RChain/
https://www.reddit.com/r/RChain_Official/
Telegram RChain Official Chat Group: @rchain_coop [Telegram Chat Invite Link: https://t.me/rchain_coop]
Telegram RChain Official Announcements Channel : @RChain_Official [Telegram Announcement Channel Link: https://t.me/RChain_Official]

Feel free to join us. I will be setting up a new Bitcointalk ANN thread soon.
