### ISSUE TITLE
Get platform.coop presentation video from from NYC conference

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#167]
Video Link to all presentations - http://isoc-ny.org/p2/platform-coop-2017 

Would be nice content to get a summary and a specific clip from gregs talk

as good faith and relationship building someone could clip the whole thing and add titles and descriptions to send out to there team for use. More work but more value generated

**Comment by dckc** [comment]
bio: [LUCIUS GREGORY MEREDITH](https://platform.coop/2017/participants/lucius-gregory-meredith)
session: [BREAKOUT PANEL - NEXT MONEY: NEW TECH FOR NEW FINANCE](https://platform.coop/2017/schedule/breakout-panels-next-money-new-tech-for-new-finance)
Sat, November 11 
01:30 PM - 03:00 PM

[livestream video](https://livestream.com/accounts/9198012/events/7768901/videos/166029144); Greg starts aroud 6:00.

Summary of Greg's intro:

 - quick facts:
   - 300 members. founded Jan 2017
   - capitalized to about $20M
 - why RChain? governance and blockchain can't be separated; I felt compelled to connect them.
 - My coop experience:
   - West Virginia grocery as a teen
   - Oberland college co-op
   - shop at REI, PCC
 - not sure "1 member 1 vote" is the right model all the time... fluidity...
 - want to hear more from the rest of you...

**Comment by dckc** [comment]
FWIW: I think Ian mentioned making contact with the https://www.buytwitter.org/ effort at this Platform Co-ops conference.
