### ISSUE TITLE
Edit board meeting agenda 2017-11-14

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#168]
Edit the agenda of [2017-11-14 Board Meeting](https://docs.google.com/document/d/1GQm3iZCMEf3Z4AxX52tmBT_WDSp43TE7e1rCUZpFIEc/edit#heading=h.mrpd2jj9w2q3)

**Comment by dckc** [comment]
surely this is as done as it's going to get; is there some reason not to close this?

**Comment by lapin7** [comment]
Yep it can be closed
