### ISSUE TITLE
How to add an image to a file in .md format on Github.

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#171]
- Make a screen copy
- Create an issue
- Paste the screen copy in the issue body
- below '[' is '{' for text displaying purpose
- !{Uploading image.png…}() This text will appear a short moment
- and it will be replaced by  
!{image}(https://user-images.githubusercontent.com/1913335/32751185-35e61f0c-c8c5-11e7-96b8-47a4e13cd7ff.png)
- the result is here under
![image](https://user-images.githubusercontent.com/1913335/32751185-35e61f0c-c8c5-11e7-96b8-47a4e13cd7ff.png)
- above line you can paste anywhere in your .MD file

Ain't that nice :-)

**Comment by dckc** [comment]
Nice.
