### ISSUE TITLE
Coop Membership Agreement plagiarism

### ISSUE THREAD

**Issue by kemihu2011** [rchain/Members#175]
Hey fellow members,

I skimmed our docs and found this egregious error on the Coop Membership Agreement page, directly off a link on the main Holdings website. (https://github.com/rchain/legaldocs/blob/master/Coop%20Membership%20Agreement.pdf)

![image](https://user-images.githubusercontent.com/31378480/32872731-05a8d9b4-ca3d-11e7-8c7f-b8e1c56511d7.png)

That's not okay. A closer eye needs to be put at scrutinizing our work to grow as a major, professional network.

**Comment by kitblake** [comment]
Good catch. This needs to get passed on to the cooperative officers, i.e. legal counsel. 
It would be advisable to search all legal docs for '@' and 'http' and check the address.

**Comment by patrick727** [comment]
Great catch

**Comment by lapin7** [comment]
Hi Evan,

Could you please change the email address in the Coop Membership Agreement?
https://github.com/rchain/legaldocs/blob/master/Coop%20Membership%20Agreement.pdf

*Notice; Informal dispute resolution*

*.......legal@civic.com <legal@civic.com> .....*

Thx

--
Cheers,
HJ

**Comment by n10n** [comment]
Uploaded the correct version and thank for pointing it out.
