### ISSUE TITLE
M> developer.rchain.coop and  rholang.rchain.coop

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#177]
_edit: this is subsumed by https://developer.rchain.coop/ as of the [Jan 31 SDK 0.1 release](https://medium.com/rchain-cooperative/sdk-v0-1-5f6bc35bf3e9)._

work out dedicated landing page for developers that includes

getting started
bounties
documentation
how to contribute
api docs

**Comment by kitblake** [comment]
In what context/site will this landing page be? 

Getting this content created will also help the woefully spare Developers section of the FAQ #60.

**Comment by dckc** [comment]
We had a session on this at the developer retreat last week. Dan Grachanin presented his picture of how to go about it, which seems pretty good to me. The presentation was recorded and should be available in due course.

**Comment by patrick727** [comment]
this will be a landing page for essentially answering the question 

"how to contribute?"

audience is "interested open-source developers"

**Comment by patrick727** [comment]
@kitblake @dckc , yes getting those presentations shortly

**Comment by dckc** [comment]
The video is up:

 - [Rchain Retreat Day Four Part Three - Release Management &
Open Source Software Relations](https://www.youtube.com/watch?v=tjLGuvuc0dI&list=PLf2bbiic5ZjCPzin3gCSMGiBtbT8UO5o2&index=15)

**Comment by patrick727** [comment]
Mentioned in the Video
- [developer.riotgames.com](developer.riotgames.com)
- [firebase.google.com](firebase.google.com)

**Comment by patrick727** [comment]
most of those are ideas are already in progress. would be nice to have individuals engaging on these channels.

**Comment by lapin7** [comment]
There are some alternatives for development-blogs.
- https://rchain.atlassian.net/wiki/spaces/RCHAIN/pages
- https://github.com/rchain/Members/wiki
- https://rchain.github.io
- https://en.wikipedia.org/wiki/Draft:Rchain_Cooperative

I suggest to create just one.
https://rchain.atlassian.net/wiki/spaces/RCHAIN/pages
Because it's in the air and most developed.

**Comment by patrick727** [comment]
In the process of on-boarding marketing and community managers. 

See "co-operator" channel. 
Although more developer advocates we need, will follow up with jake.

**Comment by dckc** [comment]
I just discovered that https://rholang.rchain.coop/ already exists. I wonder who has write access.

And is that in addition to or instead of developer.rchain.coop?

Whee!
> From now on I'll be using the chaos theory of management. -- http://dilbert.com/strip/1998-03-05

**Comment by dckc** [comment]
@lapin7 I like using https://rchain.github.io as a way to build the site collaboratively, but I'd still give it a name under rchain.coop such as https://dev.rchain.coop (a) for branding purposes, and (b) so that we could move it to a different back-end if we choose to later.

https://help.github.com/articles/using-a-custom-domain-with-github-pages/
https://www.w3.org/Provider/Style/NoMechanics.html

**Comment by lapin7** [comment]
It's indeed becoming a mess and there's risk of double effort and inconsistency.
Find herewith an overview of the initiatives.


Site | Comment
-- | --
https://rchain.atlassian.net/wiki/spaces/RCHAIN/pages | Will be closed by @Mparlikar
https://github.com/rchain/Members/wiki | Just a start @lapin7 , can be deleted
https://rchain.github.io | Is an idea of the Utah retreat
https://en.wikipedia.org/wiki/Draft:Rchain_Cooperative | Created by Kvng but in conflict with "read the docs"
https://rholang.rchain.coop | managed by @MParlikar / Pyrofex team
http://rchain-architecture.readthedocs.io/en/latest/contracts/contract-design.html | @JosDenmark 
https://dev.rchain.coop | Is an idea of @dckc

**Comment by MParlikar** [comment]
https://dev.rchain.coop will be https://developer.rchain.coop - and will be managed by Pyrofex team.

**Comment by dckc** [comment]
gak! @lapin7 don't delete https://github.com/rchain/Members/wiki please! https://github.com/rchain/Members/wiki/Weekly-Debrief-Index is really handy and has momentum. Plus, it's a home for dictionary stuff (https://github.com/rchain/Members/issues/88#issuecomment-338495466 ).

**Comment by sportshark** [comment]
@lapin7 Hello,http://www.rchain.site/ is not under construction by @Mervyn853 but by @sportshark and My friend @jiangnanmei

**Comment by lapin7** [comment]
thx. sorry

--
Cheers,
HJ

**Comment by dckc** [comment]
Since https://rholang.rchain.coop/ actually exists, I think it's important to keep track of. #159 was closed, so I'm emphasizing it here.

**Comment by dckc** [comment]
Note discussion of an SDK release in [the Jan 10 debrief](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index#january-10th---community-debrief-59).

I expect it to largely address this issue.

I'm putting in some effort polishing #185, the web playground / sandbox that Kent and Navneet started.

**Comment by dckc** [comment]
This is subsumed by https://developer.rchain.coop/ as of the [Jan 31 SDK 0.1 release](https://medium.com/rchain-cooperative/sdk-v0-1-5f6bc35bf3e9).
