### ISSUE TITLE
M> Slack to Discord: Update all references.

### ISSUE THREAD

**Issue by momchilov** [rchain/Members#179]
All documentation, website etc., pointing to Slack, needs to be modified to point to the public Discord (https://discord.gg/fvY8qhx)

**Comment by patrick727** [comment]
thanks!

Will help if people point out those links

I've changed it on rchain.coop

**Comment by momchilov** [comment]
Submitted PRs for the reference repo.

**Comment by Ojimadu** [comment]
Good you created this issue. I wanted to create it. 
This link has outdated member meeting on the upcoming event page.
https://www.rchain.coop/coop-information-1/#more-information

**Comment by patrick727** [comment]
@Ojimadu thanks for the catch and I made those updates
