### ISSUE TITLE
What exactly are the benefits of being an Rchain member?

### ISSUE THREAD

**Issue by as1ndu** [rchain/Members#181]

**Comment by llerner** [comment]
You become a voting member of the organization that is building the RChain platform. Everyone’s vote is equal, there is a plan for equity disbursement. 



========================
Lawrence I Lerner
o/m: 630.248.0663
lawrencelerner@gmail.com

Blog: lawrenceilerner.com
 <http://www.lawrenceilerner.com/>twitter: RevInnovator <https://twitter.com/#!/RevInnovator>

**Comment by as1ndu** [comment]
Ok cool Thanx!

**Comment by Ojimadu** [comment]
You become a voting member and help shape governance on the coop
You are able to contribute to the coop and earn RHOCs 
You can stand as a candidate for elections

**Comment by dckc** [comment]
For reference, there is a [membership benefits][1] section on the [co-op information][2] page.

[1]: https://www.rchain.coop/coop-information-1/#member-benefits
[2]: https://www.rchain.coop/coop-information-1/

cc @pmoorman
