### ISSUE TITLE
Signing of commits

### ISSUE THREAD

**Issue by dckc** [rchain/Members#183]
@lapin7 for proposals, I think issues work better than wiki pages such as https://github.com/rchain/Members/wiki/dev-Signing-of-commits

Wiki pages work best when they document already-accepted community norms. See [DocumentMode](http://wiki.c2.com/?DocumentMode) in the original wiki.

I suggest you delete that wiki page (or agree that I may do so).

**Comment by lapin7** [comment]
@dckc Yes! Please go ahead as you see it fits best. You know much more about these things :-)

**Comment by dckc** [comment]
OK. I deleted it.

@kitblake or anyone who wants to follow up on a signature policy for  https://github.com/rchain/rchain , I suggest you raise an issue there.

Meanwhile, I opened #184 on representation of the core dev team to the `/Members` issue process.
