### ISSUE TITLE
representation of core dev team in member issue process?

### ISSUE THREAD

**Issue by dckc** [rchain/Members#184]
A few days ago, @lapin7 wrote:
> I suggest that the guys of Pyrofex and others of the retreat post all their issues on Github\Rchain\Members. 
 -- https://github.com/rchain/Members/issues/177#issuecomment-346898729

I was at the retreat and while `rchain/Members` seems like a reasonable forum for collaborating on the dev site (#177), Dan Grachanin is the main person funded to work on it and I don't know whether his SOW includes participating here.

Other devs at the retreat have put stuff in JIRA, which seems perfectly reasonable. Much of that was recently made world-readable. If feedback or collaboration with the larger github community is important, https://github.com/rchain/rchain/issues and/or https://github.com/rchain/rchain/wiki would be more convenient. But I wouldn't expect to find all the core dev issues from the retreat under `rchain/Members/`.

(somewhat tangentially: The core dev team have the option to turn off github issues for `rchain/rchain` and they have not done so, which suggests they intend to be responsive to issues raised there. But it could be that they just didn't consider it.)

@MParlikar, @nashef, @patrick727 have you given this any thought?

**Comment by lapin7** [comment]
The difference between [rchain/issues](https://github.com/rchain/rchain/issues) and [rchain/Members/issues](https://github.com/rchain/Members/issues/) is for me that I can invite "collaborators" on members/issues and with rchain/issues one has to be a "member" of the organization rchain. Members and Collaborators can be assigned to issues.
_BTW I don't know how @ValeBF got there. Apparently she can be assigned to rchain/issues._

A logical split would be that development issues go to rchain/issues and all business/operation issues go to member/issues. Or that development issues go straight into Jira.

Now it was amazing that we all can see the recordings of the retreat and it became to me clear that there's a kind of split between coop/pyrofex and coop/community. Apart from development there were issues like: 
- go to market
- marketing
- social media management
- recruiting
- community management
- etc.

So what I want to know is: Who has the lead in these domains? How is the governance organized? And how transparent is "work under construction"? I would like to avoid that the people who do things for RChain by working on members/issues are regarded as a sitting in the trailer. So in my view it's best that we cooperate and steer together.

I hope for example that Dan Grachanin is going to tell his plans with dev site #177 :-)

**Comment by patrick727** [comment]
Core devs are working out of Jira, with visibility through the wiki and it's bounties. right? 

In regards to #177 Dan doesn't need to contribute there, it just would be nice and a plus to our culture we want to foster.
 
That issue is for community input/feedback

I'll aggregate it and if any points are glaring I can pass them on to Dan and Steve.

**Comment by MParlikar** [comment]
Hi there,

You raise some good points, and I will try to answer them.  For the areas
that you have described above, with the exception of Recruiting, we do not
have a designated person that is working on these areas *full time as their
primary role*.  I believe that this role is needed.  The closest person we
have right now is Daniel G to fill some of this.  But he is only 1 person.

It became clear at the retreat, that some roles are needed for these
activities full time.  I think, once we have those roles defined and
staffed, then we will have a leader for those areas.  For the time being,
Daniel G is going to do his best for us, by working with Patrick and other
community members.

On the development issues, once we have releases available, I believe users
will file Jira issues.  Jira does support the creation of issues by
'anonymous user'

I hope this helps.

Medha

**Comment by dckc** [comment]
So we have one data point to suggest that @MParlikar represents core here from time to time. :) When you make sure you're not the only one with this responsibility, I'm sure you'll let us know who shares it.

**Comment by MParlikar** [comment]
It is reasonable to state that I represent 'core' here.  The rest of the
above statement also rings true.  :-)

**Comment by dckc** [comment]
That addresses the issue to my satisfaction.

Everybody is welcome to continue to add notes, of course.

**Comment by patrick727** [comment]
thanks @MParlikar and @dckc for helping to clarify
