### ISSUE TITLE
Google Form "Membership registration"

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#19]
[Membership registration form, VIEW](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform) is now in sections that follows logic branching.
[Membership registration form, EDIT](https://docs.google.com/forms/d/1BohlW_z9HgMbAaFaAZcwno7mbIB3KgFCsAzpqZbZf04/edit)
At each section you can add "sections to go to" pending the answer of a multiple choice.

**Comment by lapin7** [comment]
The form itself needs a better introduction. Something with the advantages and wishful duties of a member. It would be nice if new-members get RHOC back for the $10. 💯 
One question has to be added: "What is the Transaction ID of your payment of the membership fee of $10,00 in ETH or BTC"
The output could be something like a certificate of membership, with a referral link for boarding on your friend. Then again you would get $10 in RHOC 👍

**Comment by lapin7** [comment]
The membership form is on line. If there are any issues about it, those should preferably be mentioned here.

**Comment by jimscarver** [comment]
If they use the membership identity contract to pay their dues we already
have the transaction id. We could request their member id hash but the
email address can distinguish them.

I liked the one page form much better because you were aware of what would
be asked. A good intro will fix that. I suggest the introduction to form
should at least list all the fields that will be requested, whether
required and sample answer,  and told they will have opportunity to
update/complete the form until a version is accepted.

**Comment by jimscarver** [comment]
Ok, I see the form is modified already and does not use the membership contract for payment.

I am fine with that. My only concern is that payment transaction ids are public and could be used in nuisance submissions.

**Comment by lapin7** [comment]
These links I found useful:
https://developers.google.com/apps-script/overview
https://docs.google.com/document/d/13qHGIYNuaXkjPunr2uFmpQi0Xpe3pbVGVY0PbARHcDc/edit
https://sites.google.com/site/eduonair/branch-logic-for-google-forms

I will document some tricks later on and place it in the WiKi

**Comment by lapin7** [comment]
The feedback to the user when the form has been filled out has to be better and it needs a link to propose tasks/projects and to set up an [Statement of Work (SoW)](https://docs.google.com/forms/d/1VguDvSnz158grBoFwL-gEzwqpDbs0X82cU0qnvp4r8k/edit)

**Comment by lapin7** [comment]
[Membership registration form, EDIT](https://docs.google.com/forms/d/1BohlW_z9HgMbAaFaAZcwno7mbIB3KgFCsAzpqZbZf04/edit)
The BTC payment option is deleted, because Rchain just needs an ETH-address to be able send back the 100 RHOC.

**Comment by kitblake** [comment]
> My only concern is that payment transaction ids are public and could be used in nuisance submissions
> 
Jim, if you're referring to the payment addresses in the form, the only way to get to see them is to fill out the first subform (which requires a valid email address and a yes to get involved) and submit. So those addresses are not clear text on a web page.

**Comment by kitblake** [comment]
HJ, I slightly edited the feedback to the user after filling in the form. But I'm confused about the current link:
https://github.com/rchain/Members/#boards?repos=84472896 (with Chrome browser).

It ends up at /rchain/Members/ so I think it's not valid anymore. Does it need to be replaced? I have this (rather ugly) link for the SoW form: 
https://docs.google.com/forms/d/1VguDvSnz158grBoFwL-gEzwqpDbs0X82cU0qnvp4r8k/edit

AFAIK we don't have a task/project proposal interface yet.

**Comment by kitblake** [comment]
BTW, why does one need to use the Chrome browser? I prefer Firefox and I haven't detected any difference. Or am I missing all the fun.

**Comment by lapin7** [comment]
Oh I thought the KanBan board worked only on Chrome.

https://github.com/rchain/Members/#boards?repos=84472896 this link goes
immediately to the board but maybe the general link is better
https://github.com/rchain/Members/
or a view only address as Kit mentioned


--
HJ

**Comment by kitblake** [comment]
Oh, I haven't found any KanBan board yet. I tried that link with Chrome and I end up looking at rchain/Members (even though the link with arguments is visible in the location bar). Something's not right..

A KanBan board would be a great place to start for new members (better than suggesting a project that might already exist).

**Comment by lapin7** [comment]
I see a KanBan board with the Add on "ZenHub" in Chrome.

[image: Inline image 1]

--
HJ

**Comment by kitblake** [comment]
> I see a KanBan board with the Add on "ZenHub" in Chrome.

Ok, I installed the ZenHub extension:
- I had to click a "Request access" button for the Rchain board. Somebody should have an email. 
- This was within the Authorize ZenHub screen. Then I clicked "Authorize". 
- Github asked me to confirm with my password. 

So it takes a few steps. The upshot is we should be careful sharing links to the KanBan board and note that it requires both Chrome and the ZenHub extension.

Kit

--
Kit Blake • Exordior bv • Rotterdam NL • +31-10-243-7051

**Comment by lapin7** [comment]
Help suggestion: Getting the right ETH address
Ok, now I know what's going on. That first address, with 159k, is an exchange. I didn't have any Ether in MyEtherWallet, so I paid the fee from an exchange, and entered my MyEtherWallet address as my ETH address.

**Comment by lapin7** [comment]
Paying out RHOC:
- added "Merge and Mail Attachments" to Google Sheets
- created in the response sheet of Membership registration a Mail Merge template with: GithubName, ETH-address, Remark
- created a Draft email with fields to fill, for example {{GithubName}}
- send message to verify ETH address
- send 100 RHOC to repliers, [see](https://ethplorer.io/address/0x8b629a47c3c633dadc47d6f0d6f66882593817f3#pageSize=25) 
- send out second email to announce the transaction

**Comment by patrick727** [comment]
Process sounds good to me, silly question but what do you mean mail merge template @lapin7 lol?

**Comment by lapin7** [comment]
I've added an the add on "Mail Merge with Attachments" to Google
Sheets in "Membership
Registration (Responses)"
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1FU9SIwocJk2EXPqsx8x7vlORqul2WDnNs-nG0w3vbV8%2Fedit%23gid%3D1946935137&si=5281391242641408&pi=78c5f6e1-1d4e-45f3-8231-4f76fa4b9c41>
in
Tab "MailMerge" and a draft in my Google email box like this:

Subject: Member registration & 100 RHOC followup


Dear {{GithubName}},

​The RHOC's are on their way. That is to say if you have confirmed or
corrected your ETH-receive-address
​ {{ETH address}}​

I'm figuring out how to process a bunch of email through the Google add on
"Mail merge with attachments". You can follow the improvements on Epic #15
on Github\Rchain\Members
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fissues%2F15&si=5281391242641408&pi=78c5f6e1-1d4e-45f3-8231-4f76fa4b9c41>

​{{Remark}}

You will get soon an invite to collaborate on the Github/Members repository.

Cheers,

HJ


​The fields "{{GithubName}}" are taken from the spreadsheet, so it looks
like a personalised mail.

The style is "I'm trying to get things right" and it's personal so that I
take the whole responsibility of this action.
The replies are personal and very positive.

The follow up is the actual sending of RHOC to the verified ETH address.​


--
HJ

**Comment by patrick727** [comment]
Ahh ok I see, good job.

**Comment by lapin7** [comment]
I've been working again on the membership registration. Could you give it a new try. If you click this form then you can re-edit your once filled out data. Take care because a submit will overwrite the old data. 

You will also get an automatic standard email with your answers and an explanation of the process.
I also want to implement the RChain ID-creator of Jim in the process. And to integrate the form for [job application](https://docs.google.com/forms/d/e/1FAIpQLScJs4ea5G0Q3MRwuY3cSCfk9d8ZrkKUsUUq1jpX-m-5NhCfew/viewform) and creating an [SoW](https://docs.google.com/forms/d/e/1FAIpQLScI5HG_c4ISrlQgedcE_0rq27nMlrkfzzkib9XDcAvxM2hAlg/viewform).
I wil ask the same to @jimscarver @plantether @patrick727 

[Membership registration](https://docs.google.com/document/d/1Fp8JkaUixxh8in_JYRi5cOnsqTEsntJLVzzaLsWKURk/edit)

**Comment by patrick727** [comment]
@lapin7 made some edits to the email reply. Which form is that you would like for us to fill out again? could you link it here?

**Comment by jimscarver** [comment]
[Membership registration form, VIEW](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform)

**Comment by kitblake** [comment]
I did a re-fillin of the form and checked the spreadsheet before I submitted. Everything updated properly and some things were 'new and improved', like the date. 

When filling it out I did have to fill in my ETH address again. Probably something changed. Testing again, this time it's filled in, so that's working. 

Afterwards I made some edits to the form, mostly minor stuff, but I did add conditions to the "Proof of Identity" subform, Section 7, so if you don't want a contract you don't need to submit the extra identity docs and just go to Remarks.

**Comment by lapin7** [comment]
Great cooperation :-) thx.

**Comment by kitblake** [comment]
Glad to see the term "Activist" coming into play. IMHO it works. People who get involved are active, not passive. It also echoes "activist investor" which is perfectly appropriate because some people are doing so-called grunt work (à la "Slicing Pie", http://slicingpie.com/), investing time in the initiative.

**Comment by kitblake** [comment]
We can also do incremental registration for activists. If you don't think you'll earn more than $500 then we don't need KYC data. But later, if it looks like that will change, then we need more identity in order to comply with international law. The $500 threshold also depends on how successful we are establishing the RHOC as an exchangeable instrument. But even if it's value stays stable, we'll need an automated alarm that warns *before* an Activist exceeds the $500 limit.

**Comment by kitblake** [comment]
In the response text (Form Publisher Template) I made a bunch of minor English edits. Can we test it? I think there will be confusion with the inserted variable values. For instance, when this phrase gets rendered:

> You said: "<<Do you prefer to earn your rewards in (old-fashioned) US Dollars?>>" 

It will appear like this: 

> You said "Yes". 

But the reader will have no idea what the question was. So we probably need to make that clear each time we insert a value. I can forge ahead and do that, or maybe we want to test first.

**Comment by lapin7** [comment]
This is the template for creating a SoW. The text is OK now. But is it clear enough that the worker is an individual contractor??
https://docs.google.com/document/d/1ZlWPeICrkmL_GW5UwOuGZ4PJvcOb7uv7tBEm-6hhNkw/edit

**Comment by patrick727** [comment]
@lapin7 I don't think it is that explicit so i suggested a section in the above, besides that it is very comprehensive and clean. Good job
