### ISSUE TITLE
Get RHOCs on Cryptocompare 

### ISSUE THREAD

**Issue by Ojimadu** [rchain/Members#190]
This is issue is to get RHOCs listed on Cryptocompare.com This was suggested by a user in our Telegram group. I think it can give RHOCs more exposure. I already sent out an email awaiting response from them

**Comment by nikhil9865** [comment]
https://docs.google.com/forms/d/1jC5rzzOsK0Mwhlr9A4eRv01km9u5IeRZjmWTGPeddDE/viewform?edit_requested=true
I have submitted the form waiting for response

**Comment by kitblake** [comment]
Does Cryptocompare compare ERC20 tokens? I just took a look and don't see any that I recognize.

**Comment by nikhil9865** [comment]
RHOC is now listed on Cryptocompare i have received email and checked on their website.

**Comment by dmsn0067** [comment]
I got them on crypto compare. I emailed them and told em I been waiting for
months to add my stack to my portfolio, they just emailed me back a bit ago
to tell me they added it.

**Comment by lapin7** [comment]
@dmsn0067 
Great that you want to cooperate on RChain issues. Please read "[How to contribute](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md)"
And raise the budget for #190 in Gsheet "Pub...." https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=176786742
Please send your email address to ops@rchain.coop. Then I send you an invite for rchain@googlegroups.com. And then you have access to "Pub Member Budget Allocation-Spending"

**Comment by nikhil9865** [comment]
@lapin7  Thats my email id in response

**Comment by dmsn0067** [comment]
@lapin7 Email sent
