### ISSUE TITLE
M> Convert some of existing doc into md format and upload into github

### ISSUE THREAD

**Issue by n10n** [rchain/Members#195]
For example: https://docs.google.com/document/d/1sGlObhGhoEizBXC30Ww4h1KHKGkmcy4NiCKitIBqiUg/edit# and there are many more.

**Comment by kaka56** [comment]
I just joined but will give the issue a try". Please how do I become a collaborator?

**Comment by Kencode7** [comment]
I am willing to handle this. How do I get the doc.?

**Comment by Ojimadu** [comment]
The above document"Notes on the DAO re-entrancy bug and behavioral types" has been converted and added. More documents would be converted and added. Please documents should be added to this folder https://github.com/rchain/Members/tree/master/Docs

**Comment by lapin7** [comment]
@Kencode7  Awesome that you want to help getting the RChain platform on the rails. 
Please send your email to ops@rchain.coop
and because you seem to a new collaborator please read [How to contribute](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md)
thx

**Comment by Kencode7** [comment]
Already sent... Thanks @lapin7

**Comment by BelovedAquila** [comment]
I tried adding a document to the link pasted above but had no access. @lapin7 It seems like i would be needing an invitation to collaborate. I have sent my email and github id to you.

**Comment by Kencode7** [comment]
unable to upload converted files to the folder https://github.com/rchain/Members/tree/master/Docs

**Comment by Ojimadu** [comment]
What's the feedback you get?

**Comment by lapin7** [comment]
Please help him out. I don’t know how that works.

**Comment by Ojimadu** [comment]
@Kencode7 Do not use the 'upload files' button. Go to the folder posted above and click on 'Create new files' that should do the fix.

**Comment by dckc** [comment]
Why convert "Notes on the DAO ..."? What's wrong with the google doc as it is?

**Comment by dckc** [comment]
I appreciate the effort, but again, what is the purpose of [the converted document](https://github.com/rchain/Members/blob/master/Docs/Notes%20on%20the%20DAO%20re-entrancy%20bug%20and%20behavioral%20types) ? It wasn't converted to markdown; it was converted to plain text; and pretty messy at that. Are Jack Pettersson  and Lucius Gregory Meredith happy to have their work republished in this form?

I'm inclined to remove it and close this issue. I'll stand by for feedback for a few days.

**Comment by Ojimadu** [comment]
Same inclinations here @dckc. Perhaps, @n10n can put forward some clarification as he created the issue.

**Comment by dckc** [comment]
I deleted it in a12b00c .

Based on lack of response to my Dec 27 question, I'm closing this issue. (Interested parties can, of course re-open it.)
