### ISSUE TITLE
M> Newsletter - December 14th

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#196]
[newsletter draft - December 14th](https://docs.google.com/document/d/1vVxpWZrJq463Gs9WHtCf-PYKSAKuyJocESu2EWABsWk/edit)

**Comment by sportshark** [comment]
Great! Many Chinese are waiting for the newsletter,I will translate it as soon as possible when you're done

**Comment by Ojimadu** [comment]
The draft seems okay. Please post a comment here when you update with content.

**Comment by patrick727** [comment]
Thanks @Ojimadu will do!

I'd remove any links to slack, we are actively moving away from slack. 

Yes this draft isn't populated yet, Id encourage members to propose news topics for me to cover in there.

**Comment by Mervyn853** [comment]
@patrick727 I have created a official links page here : https://github.com/rchain/Members/blob/master/projects/Links%20to%20Official%20Channels.md as per  @kitblake suggestions. 

Please help to update the links in there if they get outdated and update them with the new ones. Going forward, anyone can reference that as a resource for all our official RChain Coop Channels.

**Comment by Ojimadu** [comment]
This should be fit for the "In the other news" section of the newsletter?
“The attention of the coop has been drawn to a fraudulent google form advertising a crowdsale/airdrop for RHOCs. 
DO NOTE THAT THERE IS NO CROWDSALE OR AIRDROP. PLEASE DO NOT SEND ETH OR FILL UP ANY FORMS RELATED TO RHOC CROWDSALE/AIRDROPS. 
Please help us to report this phishing scam by clicking the link below:
http://bit.ly/2klgwe4”

**Comment by patrick727** [comment]
Good idea will do!

**Comment by patrick727** [comment]
Here is the test draft of the newsletter drafted in archive 
[link to newsletter](http://archive.sendpulse.com/shc4c/2fbc7244/?_ga=2.53744744.1919355233.1513205746-85970949.1511818720)

**Comment by sportshark** [comment]
@patrick727 wonderful! I love this news letter!

**Comment by sportshark** [comment]
@patrick727 wonderful！ I love your newsletter!

**Comment by ResonanceXX** [comment]
Good job done. 
Just a few observations. 

The Latin sentence could be in italics. 
The word /procesess's/ is quite incorrect. Should be revised. 


**however if there's  a need for document accessing and proof reading. I can do further work.

**Comment by ResonanceXX** [comment]
I am willing to help make **minor** adjustments. Because the initial job done is marvelous.

**Comment by patrick727** [comment]
Thank you @sportshark , @ResonanceXX , and @Ojimadu.
Most of those changes got caught in the editing phase, I did miss the "exerpts" error.

The next newsletter we are planning for 1/3 so I will work on getting it qued up days in advance so that everyone has adequate time to review it. 

Cheers
