### ISSUE TITLE
O> Google Form scam circulating on Twitter

### ISSUE THREAD

**Issue by kitblake** [rchain/Members#201]
We have our first scam:

    Mervyn, [08.12.17 16:09]
    SCAM ALERT: There is a google doc circulating on twitter announcing a crowdsale and airdrop
    for RChain. 

    DO NOTE THAT THERE IS NO CROWDSALE AND AIRDROP. PLEASE DO NOT SEND ETH OR FILL UP ANY FORMS
    RELATED TO RHOC AIRDROPS.

On Telegram I've pinned this message and changed the welcome message to warn new users about it. 

Also: 

    ian, [08.12.17 16:40]
    Help us report this to Google by visiting the link and clicking the ❕in the lower left
    corner of the screen. Tell Google that this is a SCAM.
    https://docs.google.com/forms/d/e/1FAIpQLSeiaWH9L-h3oDeXWwBLzB-APVjmm_gHE90gbP3BFkVHu4MQ1g/viewform

Please do so!

sportshark commented a day ago:
    @kitblake Some Chinese are asking about the crowdsale!So I will tell them this is a SCAM as soon as possible via http://rchain.site and QQ group！

kitblake commented a day ago 
    [In reply to 北京之东--Andy Li]
    Good move @sportshark. The community needs to pounce on these scams and prevent anyone from getting hurt. So far there is no eth at the scammer's address, but the fake form is still online. 

If anybody hasn't reported the form yet, please do so, see the forward from @ian above.

**Comment by Mervyn853** [comment]
Looks like there are a lot of fake accounts on twitter spamming the same airdrop / crowdsale scam. Please stay vigilant and help to REPORT ABUSE on the Google form too. 

https://twitter.com/search?f=tweets&q=rhoc%20airdrop&src=typd

**Comment by nikhil9865** [comment]
report spam everyone bottom right on page of this form.

**Comment by kitblake** [comment]
@patrick727 Can you post a scam alert on the RChain account(s)?
Something like:
SCAM ALERT: There is a Google form circulating on Twitter announcing a crowdsale and airdrop for RChain. THERE IS NO CROWDSALE OR AIRDROP. It's a scam.

**Comment by Mervyn853** [comment]
Done on Telegram announcements channel, Reddit and Bitcointalk. Pinned message in Telegram chat has also reflected that.

**Comment by Ojimadu** [comment]
Lets use this links to report the doc as scam. http://bit.ly/2klgwe4 
The spammer maintains multiple accounts on twitter and is actively using them to spam. 
I've also sent a message with @kitblake text to patrick on discord. We need to be alert.

**Comment by ResonanceXX** [comment]
Ill keep sharing the word.

**Comment by dckc** [comment]
@kitblake and everybody, when would you consider this matter resolved?

 - [ ] now?
 - [ ] when the google doc has been taken down?
 - [ ] when the party that posted it is identified?
 - [ ] when the [RChain FAQ](https://github.com/rchain/reference/blob/master/faq.md) has been updated to say "Is there an airdrop? No. contrary to fraudulent reports in Dec 2017."?
 - [ ] when the RChain board has acknowledged the issue and decided how to address it?

**Comment by kitblake** [comment]
Since I see (Github-specific) markup to create checkboxes, I would check "when the google doc has been taken down". As of last week it was still circulating on Twitter. 

And since they're checkboxes, not radio buttons, one can check more than one. It'll be added it to the FAQ.

Thanks for 'making the rounds' :)

**Comment by lapin7** [comment]
Something like this????

Which of these *features* will you need?:
* [X] simplicity
* [ ] Don't know
* [ ] complete

[Source](https://talk.commonmark.org/t/introducing-markdown-extensions-for-form-input/432/2)

**Comment by Keaycee** [comment]
Well, i think i can take care of the airdrop & crowd sale scam on twitter.

This is a very serious issue because it's fraudulent. There are lot of ignorant people out there interested in RHOC and don't know how to purchase it legally. I believe we all can collaborate and broadcast the the Airdrop and crowdsale scam on social media. (Facebook, Twitter, Whatsapp, Telegram, blogs and others.

**Comment by Ojimadu** [comment]
IMO, We should just report it and not publicize it further. For now the scam seems to be dying off. Would need to review this again about two weeks time.

**Comment by dckc** [comment]
I see the FAQ was updated Jan 8: https://github.com/rchain/reference/commit/01ef40374dd1e0c9c1a1759568d8b7ece1261326#diff-4a1318da06786ac52626178ca960109e

Has the google doc been taken down? I never had a link to it. I don't see it in the first several pages of twitter search, so optimistically, I'm going to say yes. Somebody who finds otherwise will please re-open this.
