### ISSUE TITLE
M> Newsletter - January 3rd, 2017

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#204]
[Here is the template for the next newsletter to be published Jan, 3rd](https://docs.google.com/document/d/1iyLXDfiGDQsis_Ynz_ZHoo1TuxjVYF2dfB-aaWBPMYQ/edit#)

**Comment by ResonanceXX** [comment]
Should work commence? Would be  Willing to collaborate. 

Sent from Yahoo Mail on Android 
 
  On Sat, 16 Dec 2017 at 16:45, patrick727<notifications@github.com> wrote:   
Here is the template for the next newsletter to be published Jan, 3rd

https://docs.google.com/document/d/1iyLXDfiGDQsis_Ynz_ZHoo1TuxjVYF2dfB-aaWBPMYQ/edit#

**Comment by Ojimadu** [comment]
Sure, the earlier the better. :)

**Comment by patrick727** [comment]
@Ojimadu yes typically its every two weeks

but because of the holidays this next will go out on the 3rd

**Comment by patrick727** [comment]
@ResonanceXX the earlier we start on it the better, please add your suggestions

**Comment by ResonanceXX** [comment]
Yeah @patrick727 I am solidly in support of this initiative. I wish not to make wild guesses. Reviewing the previous Newsletter. Get back to you.

**Comment by patrick727** [comment]
Awesome,

so as to not make wild guess's look at the debriefs and then formulate information around the themes described in the debriefs. 

for example, the last hangout there was big news about the developer site, rholang .2 specs, and node.hello release all coming, so that would be good to expand upon.

**Comment by ResonanceXX** [comment]
Just to be completely precise. where can I access those?

**Comment by patrick727** [comment]
Sure, the releases arent going to be available until January but you can see the hangouts on Youtube. 
https://www.youtube.com/channel/UCSS3jCffMiz574_q64Ukj_w

Also see the timestamped summaries for easier searching.
https://github.com/rchain/Members/wiki/Weekly-Debrief-Index

**Comment by sportshark** [comment]
Great, I will translate it!

**Comment by patrick727** [comment]
We will also want to create the newsletters in markdown and upload them to github the same day they are released to the public.

**Comment by n10n** [comment]
Here is link to the last weeks version: https://github.com/rchain/reference/blob/master/newsletters/20171214.md

**Comment by Ojimadu** [comment]
I just added the news about Node.Hello release to the newsletter. It is an edited copy from a post of Nash foster.
@n10n Uploading to that repository would require some privileges to be granted to @patrick727 since he sends out the newsletters or if you don't mind doing the uploads yourself you can.

**Comment by patrick727** [comment]
@Ojimadu thanks

i also went back in and filled it up some, lets get the feedback into that doc so we can finalize it on New Year. 

wewh this one is packed, lots to look forward to in 2018

to mercury and beyond!!!

**Comment by ResonanceXX** [comment]
Good work guys. 
Let's go!  I'm good to proof read, make edits!

**Comment by patrick727** [comment]
thanks @ResonanceXX 

https://docs.google.com/document/d/1iyLXDfiGDQsis_Ynz_ZHoo1TuxjVYF2dfB-aaWBPMYQ/edit?userstoinvite=ns68751@gmail.com&ts=5a474adb&actionButton=1#

thats the latest draft, want to finalize copy by today and que it into the newsletter software tommorow

**Comment by ResonanceXX** [comment]
I've set out to make changes. 

Sent from Yahoo Mail on Android 
 
  On Mon, 1 Jan 2018 at 15:32, patrick727<notifications@github.com> wrote:   
thanks @ResonanceXX

https://docs.google.com/document/d/1iyLXDfiGDQsis_Ynz_ZHoo1TuxjVYF2dfB-aaWBPMYQ/edit?userstoinvite=ns68751@gmail.com&ts=5a474adb&actionButton=1#

thats the latest draft, want to finalize copy by today and que it into the newsletter software tommorow

**Comment by Kencode7** [comment]
Is anyone converting the newsletter into markdown format to be uploaded to github?

Also, the rchain medium link can be added to the list of important links. A lot happens technical information is carried on medium.com

**Comment by patrick727** [comment]
@Kencode7 the important links is just a refernce for the draft, but your right non the less. 

We are working out a process to add the newsletter in markdown @n10n was leading that. 

I believe he has a process down for a simple way to convert the google doc into markdown so its important for me to make sure any draft changes happen in the google doc. 

Great input all thank you a ton!

**Comment by patrick727** [comment]
[Drafted in sendpulse](http://archive.sendpulse.com/shc4c/6c82b012/?_ga=2.219459737.1476390129.1514922887-85970949.1511818720 )

please any edits use the suggestion feature in the google doc so that the doc remains consistent with the sendpulse for easy markdown.

**Comment by Ojimadu** [comment]
Really good inclusion @patrick727. The newsletter is really packed. It looks good to go.

**Comment by patrick727** [comment]
@Ojimadu very packed!!! Tons of good news. 

Thanks you all for your continued input, great cooperators. 

This newsletter is qued up now to send. 

On to the next thing!

**Comment by ResonanceXX** [comment]
Cheers team. 

Sent from Yahoo Mail on Android 
 
  On Wed, 3 Jan 2018 at 15:29, patrick727<notifications@github.com> wrote:   
@Ojimadu very packed!!! Tons of good news.

Thanks you all for your continued input, great cooperators.

This newsletter is qued up now to send.

On to the next thing!
