### ISSUE TITLE
Several Finance tasks

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#21]
Lykke account Rchain (ops@rchain.coop)
Distribution of Rhoc under members, Promise to Spend
Initial Budget proposal and single signature Rhoc wallet of 1 mln Rhoc
List of assets
List of expenditures
Rhoc current price
Membership Fee
Fiscal and legal advise
MyEtherWallet for Lisa

**Comment by lapin7** [comment]
Greg made a budget available to ops@rchain.coop (HJ) of 1 mln RHOC.
You can follow the transactions on the [token RHOC exlorer](https://ethplorer.io/address/0x8b629a47c3c633dadc47d6f0d6f66882593817f3)

**Comment by patrick727** [comment]
Sweet, thanks Greg. 
Looking forward to beginning some projects with that. 

Should we meet on this sooner then next Wednesday? 

Cheers

**Comment by lapin7** [comment]
Let's think first create a process for defining/approving a project:

1. define the objective and deliverables of a project; the objective has to support the mission of RChain
2. at least 3 active persons need to support the project
3. allocate a budget to the project
4. send the tokens to the project lead (all at once or in line with milestones)
5. the project lead sends an invoice and this expense will be registered in the books
6. the project lead does further distribution of the budget to the project members. this can probably be done without further invoicing.
7. if the project is a success then a bonus could be send, like 50% of the allocated project budget. This bonus is bound to a contract "Promise to Spend" and must be used to fund other projects. 

The goal is to stimulate decentralised decision making about project approvals.
if the project is a failure then the organisation has at least to learn from the mistakes
if the funds are abused then the involved people get a negative entry in their profile

The thing to remember in the Rchain case, is that 1 billion RHOC have been pre-minted out of thin air. Those RHOC only get value when they are in the hands of a lot of people. So the distribution policy has to be extremely generous and fast. If people are willing to do something fruitful for it, then they should be generously rewarded for it. The risk of losing 'money' is very low in this situation.
