### ISSUE TITLE
Brief but elaborate enlightenment of prospective collaborators on Github Rchain cooperative via a group or forum. 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/Members#211]
Good Day,
 
I (Beloved Aquila)  think Rchain needs more hands on deck for its issues to be effectively HANDLED, resolved  and managed. 
OBSERVATION AND PROBLEM :
Having observed that there are much issues to be resolve and little or not enough hands to handle them or storm on them till it's resolutions are ascertained. I resolved to think on the reasons, because "If there is a problem, there is definitely a cause and a prospective solution", so having seen a seemingly problem of our Rchain issues queuing with no much of it been settled,  firstly because they aren't enough hands to help out via a kind of division of labour process which assists in helping work to be covered and done in nice timing too (pardon me, I said it's seemingly a problem  because I think it is, don't know who else sees it so).
CAUSAL AGENT :
 I reasoned to know it's cause, and I could fetch that, so many are interested in collaborating, helping to resolve our Rchain issues and likewise boost its functionality  into  another great pedestal of balance and active impact,but they can't or let's say "they feel they can't"  because, they lack adequate information, directions or let's say  orientation on how to dot the Rchain "i's" and cross it  "t's" to make an impact and help resolve our matters /issues.
POSSIBLE SOLUTIONS :
 Much well as I thought on the reasons why our Rchain issues are not being resolved with efficacy,as  basically because of "lack of knowledge " perhaps "adequate knowledge", and little information or communication to the newbies of this cooperation on little little but effective pin points having to do with our Github Rchain cooperative, I also thought on what I think would be a  possible solution to it, which is creating a group or forum sort of, which would comparise of  every new Github Rchain members specifically and few old insightful  active members(volunteers though), who can enlighten the new members on "what is what and what is not", "what is up and what do not", the aim of this is basically to create enlightenment to new github members who really  want to be really involved, active and engulfed in resolving our Rchain issues, likewise helping it bloom. The platform would be on a cordial basics such that questions and answers can flow and be solved, it would aim at just spreading and spreading knowledge, light and infos on what a newbie ought know about this cooperative . Information is soo vital, many do wrong things or are misled because of no information was gotten to have helped them do things well, be better, calculative and creative. " 
No Man Is An Island Of Knowledge ". 
Not intending  to make this too lengthy, but I hope I was able to give little glimpse into what I mean and am trying to point out.  
REASON FOR CONSIDERING THIS A PROBLEM :
 Yes, evidently this  might not be so  much an issue to everyone, but it is a seemingly issue to me, mostly because I was faced with it and believe some present  active members face it then,  of which  I believe too that  they have, and was able to resolved, and it is more reasons why they need create a platform where they can help our newbies resolve such  "I am lost"  syndrome which one tends to have while trying to help resolve some Rchain issues or getting the  knowing on  how Github Rchain works and how to contribute.  
OTHER ISSUES OBSERVED 
looking at this our Github blog, i also thought our Github Rchain blog  needs a lot of modifications,upgrade and enhancements, to make it look more strategic, professional and marketable ( eye catching), it needs this touch of authenticity and clarity of access.
Also though  It should also have a page where, all general collaborators  can rapport , apart from the issue box, let communication and information  just keep flowing, it would go along way in raising intellectuals who would be able to confidently anywhere anytime stand to promote Rchain worldwide. 
 Thank you very much for finding time to read me.

**Comment by lapin7** [comment]
Nice observation. Now go ahead and change  things as you see fit. See what you can do yourself in solving issues. Invite also your friends. Organize yourself to be effective. Most things are not clear. They only become clear when people start doing things. New structures or platforms won’t help a lot.

**Comment by BelovedAquila** [comment]
Yes, very much helpful, thank you @lapin7 I think I do understand better now, thank you much.

**Comment by ResonanceXX** [comment]
Agree with Lapin7. Aquila try to solve problems, not see problems. The world is not good for anybody. 

Sent from Yahoo Mail on Android 
 
  On Tue, 26 Dec 2017 at 20:38, BelovedAquila<notifications@github.com> wrote:   
Yes, very much helpful, thank you @lapin7 I think I do understand better now, thank you much.

**Comment by BelovedAquila** [comment]
@resonance I understand, thank you.

**Comment by kitblake** [comment]
Thanks @BelovedAquila, it's always hard to know what newbies experience, and the first steps when joining a community are important. In the comm channels we send interested people to https://github.com/rchain/Members/blob/master/CONTRIBUTING.md. It's a long document but it needs to be complete. The intention is to ease newbies into the collaboration process. Its content should be continuously improved. Also we can link from this doc to other resources that help new contributors get oriented.

**Comment by BelovedAquila** [comment]
@kitblake yes yes yes, just saw it, it's OK, though it actually needs to be completed, how can one go about its completion please ?. Those links to are paramount to create broad understanding for newbies.

**Comment by kitblake** [comment]
Various people maintain the doc. You're welcome to edit. it's a collaborative effort.

**Comment by dckc** [comment]
Is this issue resolved? https://github.com/rchain/Members/issues/211#issuecomment-354005235 makes it look like yes, it is.

If it's not resolved, go ahead and reopen it and explain what the next step is.
