### ISSUE TITLE
M> Newsletter - January 18th, 2018

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#218]
Great job on the last newsletter team. 

[Here is the doc ](https://docs.google.com/document/d/1RYdHq3fh4Z5BXoavKvjtFNRZHhTHPavp7wi-HZUEMVc/edit#)for the next one, scheduled for January 18th

**Comment by ResonanceXX** [comment]
Again, again! Can't wait.

**Comment by kaka56** [comment]
Newsletter for  January 3rd - Community Debrief 58 updated

**Comment by Keaycee** [comment]
@kaka56 Good job. Have you seen the doc for the next one scheduled for January 18th?

**Comment by kaka56** [comment]
Newsletter for January 10th - Community Debrief 59 updated

**Comment by patrick727** [comment]
Hello all, please review and add suggestions to [the draft](https://docs.google.com/document/d/1RYdHq3fh4Z5BXoavKvjtFNRZHhTHPavp7wi-HZUEMVc/edit#) it will need to be qued up today. Thanks

**Comment by Ojimadu** [comment]
@patrick727 The link requires permission. Please have a look at it.

**Comment by TrenchFloat** [comment]
@patrick727 I can write the timestamps for Wednesday's community Hangout by Thursday afternoon.

I can't find the past 3 newsletters in the [archive](http://archive.sendpulse.com/shc4c/Aad65e732/). Do you need timestamps for those Hangouts too?
