### ISSUE TITLE
M> My request to Trebor Scholz to be an RChain collaborator

### ISSUE THREAD

**Issue by Viraculous** [rchain/Members#221]
Hello Collaborators greetings from my side. I sent an email this morning to Trebor Scholz requesting him to become a collaborator in the  RChain community. I realized his relevance in building a cooperative structure in the RChain platform. This was his reply  "We are already familiar with and excited about Rchain and Greg Meredith was a speaker at our last conference. We are planning to collaborate in 2018." What do you think?   About Trebor Scholz: https://www.newschool.edu/lang/faculty/Trebor-Scholz/

**Comment by kitblake** [comment]
Nice. Maybe we can get him as a speaker for one of our future conferences.

**Comment by Viraculous** [comment]
I think he is a prospect for RChain's adoption @kitblake . He is also a contributor at Open:2017 platform ( see link: https://2017.open.coop/contributors/ ) which  features people at the cutting edge of the cooperative, open source and collaborative economy.

**Comment by patrick727** [comment]
@Viraculous this is an awesome prospect. what is the intended outcome of this outreach? 

I say we ask him to write a guest post on his thoughts on governance, we can promote his book in it too, and then invite him to the conference. 

What do you think?

**Comment by Viraculous** [comment]
Exactly @patrick727  i will be requesting his opinion and thought on governance. Nice

**Comment by patrick727** [comment]
rchain.coop/events (please dont widely circulate as ill be making design edits today)

you can see slots for "guest speakers" maybe he is willing to do a spot? 

anyhow @Viraculous great stuff thanks

**Comment by Viraculous** [comment]
Thank you @patrick727. Although, I got a reply from him this morning after
requesting for his thought in blockchain governance and if he could
volunteer to speak in one of our conferences but this was his reply " We
are working with Greg Meredith already.
I don’t really have the capacity to engage in parallel collaborations." . i
was thinking maybe i could contact other open source and cooperative
platform influencers on OPEN:2017 (Open.coops) to see x-ray their thoughts.

**Comment by patrick727** [comment]
Interesting @Viraculous. 

Thank you for that effort. 

Please do that!

**Comment by Viraculous** [comment]
@patrick727 Thanks I will

**Comment by Viraculous** [comment]
@patrick727 Thanks I will

**Comment by BelovedAquila** [comment]
Impressive move @viraculous. the conference is getting closer by the day, any recent development on this issue? Has Trebor scholz contacted other open source and cooperative
platform influencers for their thoughts xray as intended? Or has he gave you any other feedbacks?
