### ISSUE TITLE
>M Extremely helpful Telegram interaction

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#223]
One of the more active 'helpers' on Telegram is YSGjay ( Github: @jplepel ). He answers lots of questions and provides links. He's on Discord but not on Github yet. He should get some RHOCs. The question is how.

Suggested Budget: $500

**Comment by ResonanceXX** [comment]
I forfeited, and directed my round number prize be used for registering a new member. Or could be the incentive for attracting one. Provided that is the only limitation. Human resource is a true resource. 
Cheers!

Sent from Yahoo Mail on Android 
 
  On Wed, 10 Jan 2018 at 15:22, HJ Hilbolling<notifications@github.com> wrote:   
One of the more active 'helpers' on Telegram is YSGjay. He answers lots of questions and provides links. He's on Discord but not on Github yet. He should get some RHOCs. The question is how.

Suggested Budget: $500

**Comment by jplepel** [comment]
Thanks! Who should I send my ETH address to? Also, is it possible to set aside $40 for two people I'd like to bring into the co-op?

**Comment by Viraculous** [comment]
First of all, welcome aboard the community of collaborators. I think @lapin7 is in a better position about your question.

**Comment by Viraculous** [comment]
Sorry that I couldnt reply you @jplepel (ysgjay:). I tried to but but was  typing way too fast and an icon popped up to requesting that i join chill zone, i could reply you. I am Victor on discord

**Comment by ResonanceXX** [comment]
@jplepel The person who I presume incharged is  @kitblake. Hopefully hasn't been changed. 
Welcome aboard

**Comment by kaka56** [comment]
@jplepel Welcome aboard .your efforts are indeed remarkable.

**Comment by Keaycee** [comment]
Thank you so far for your contribution @jplepel good to have you aboard. You mentioned about setting aside $40 for two new members who wants to join our community. You must know that each of them have to pay the registration fee of $20 solely. But if you do want to assist in paying both fees, i suggest pay using a credit card as it's more easier and faster to get a payment confirmation.

**Comment by Ojimadu** [comment]
@jplepel It would be easier paying for the membership yourself than to set aside a portion of the reward due to way the rewards are disbursed. Like @Keaycee said, it's easier to use a credit card when paying than to pay with bitcoin. It is quite ironic :) 
Welcome aboard.

**Comment by jplepel** [comment]
Thanks. Will do. Have some lawyer friends I would like to bring into the coop. Never hurts to have more of them.

**Comment by kitblake** [comment]
This was a nice onboarding episode. Hopefully many more to come. 
Done and closing.
