### ISSUE TITLE
A New Telegram Group - RChain Africa 

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/Members#224]
Although progressive modifications may be made to the final name. 
This group is a clear signal to the fine emergence of  RChain as a truly global entity. 
There are a lot of important pointers to encourage the inclusion of a very youthful African population in the RChain project. Expect a lot of enthusiasm. 

**Modalities on getting the Telegram group to take off.

**Comment by ResonanceXX** [comment]
@lapin7  First issue is this 1). RChain_Africa  or 2). RChain Africa. 


Kindly get your thoughts across.

**Comment by Keaycee** [comment]
This is the link on the new telegram group for Africa 

https://t.me/joinchat/HkeA-g9DExa8-6UOpAaC1Q

**Comment by ResonanceXX** [comment]
Yeah this is the link
https://t.me/joinchat/HkeA-g9DExa8-6UOpAaC1Q

**Comment by ResonanceXX** [comment]
Creating a responsive Bot for the group. Requires to be solved. Also a group butler would be necessary. 
@lapin7

**Comment by Viraculous** [comment]
Am truly impressed by the recent development which is a step towards a global identity of this community. Credit to @ResonanceXX  and @Keaycee for your observations and concern but I also think this #224 and #225 should be consolidated in one that accommodates a broader view of the idea.

**Comment by kitblake** [comment]
Please upgrade the group to a supergroup. Then you can create a memorable join link like:
https://t.me/rchain_africa

The others that we have are:
https://t.me/rchain_coop
https://t.me/rchain_official 
https://t.me/rchain_nl

**Comment by ResonanceXX** [comment]
It is now a super group. 

Sent from Yahoo Mail on Android 
 
  On Thu, 11 Jan 2018 at 19:41, kitblake<notifications@github.com> wrote:   
Please upgrade the group to a supergroup. Then you can create a memorable join link like:
https://t.me/rchain_africa

The others that we have are:
https://t.me/rchain_coop
https://t.me/rchain_official
https://t.me/rchain_nl

**Comment by Keaycee** [comment]
The link has been created, it can now be added to the other telegram channels as you have listed above.

**Comment by ResonanceXX** [comment]
@kitblake The memorable join link

t.me/RChainAfrica

Cheers. Thanks for the head's up.

**Comment by ResonanceXX** [comment]
@lapin7 Just that this has only began. I could add some more admins. Have I the right to do so?

**Comment by Ojimadu** [comment]
The group is supposed to be https://t.me/rchain_africa which is consistent RChain's social handles and nomenclature.

**Comment by ResonanceXX** [comment]
@kitblake t.me/rchain_africa was rejected after some consideration @lapin7 implied that you had a discussion about it. 
I'm just curious as to why there's a new group. And how necessary it is creating options for a single entity. 
If this is an error could it corrected for the greater good of RChain. 
Misleading information isn't all that good. 

- [ ]

**Comment by ResonanceXX** [comment]
That would be difficult to search out. Members may only come by sharing links. You could have weighed in on the discussion earlier. 


Sent from Yahoo Mail on Android 
 
  On Thu, 11 Jan 2018 at 21:29, Ojimadu<notifications@github.com> wrote:   
The group is supposed to be https://t.me/rchain_africa which is consistent RChain's social handles and nomenclature.

**Comment by Mervyn853** [comment]
I also think this #224 and #225 should be consolidated in one. I agree with @Ojimadu in using one that is consistent with the other social handles. We should close out the one that @ResonanceXX created to prevent confusion

**Comment by kitblake** [comment]
Yes, let's merge the conversation into one issue. Closing this one, I'll follow up in #225.

**Comment by ResonanceXX** [comment]
Why have @kitblake closed this so soon. A lot of effort has gone in to the Decided group. Will this all be waste.
@Mervyn853 I actually felt that the Former group would have been changed to reflect the nomenclature you desire. 
Going through the process of creating a new group. And projecting that before the explanation was given. 
That's a lot of confusion.
As much as possible since I was involved in the initial process to birth this idea. 
I relish the

**Comment by lapin7** [comment]
Yeah. Do as you seem fit.

--
Cheers,
HJ

**Comment by ResonanceXX** [comment]
I was able to get a graphic design software. I'm not artistic. So an fx  was invited  came up with this. 

Sent from Yahoo Mail on Android 
 
  On Fri, 12 Jan 2018 at 11:21, HJ Hilbolling<notifications@github.com> wrote:   Yeah. Do as you seem fit.

--
Cheers,
HJ

**Comment by kitblake** [comment]
@ResonanceXX Don't worry, there is no implication on budget and rewards. All the work you've done will be considered by everybody. That's how the system works, and it works really well. 

We simply don't need two issues for one task. Or in this case, one Telegram group. 

Because https://t.me/rchain_africa follows the RChain naming convention, we'll use that for the RChain Africa group. 

Closing this so we just have one issue.
