### ISSUE TITLE
F> create symbolic links between Payment Register & Personal Contractor folders

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#227]
Le résultat souhaité est qu'un "Invoice" apparait dans deux dossiers. Par example pour le "invoice": 2017-12-lapin7.pdf
Il doit apparaitre dans les dossiers de Google Drive:
My Drive \ RChainHJ \ Moved \ Contractors \ HJ Hilbolling \ Invoices
My Drive \ RChainHJ \ Moved \ Finance \ Payment Register \ 2018 \ 12_x Payment Register

**Comment by Viraculous** [comment]
The desired result is that an "Invoice" appears in two folders. For example for the "invoice": 2017-12-lapin7.pdf
It must appear in Google Drive folders:
My Drive \ RChainHJ \ Moved \ Contractors \ HJ Hilbolling \ Invoices
My Drive \ RChainHJ \ Moved \ Money \ Payment Register \ 2018 \ 12_x Payment Register

**Comment by kitblake** [comment]
@Viraculous Tu peux faire le symbolic link aussi ?

**Comment by lapin7** [comment]
This is a special job. I cooperate closely with @MargotCoul and @ChloeCoul to do this. 
It has secured access to these documents.

**Comment by lapin7** [comment]
@Viraculous Telegram Chat Invite Link for France: https://t.me/rchain_fr
Si tu as envie, tu peux joindre ce group :-)

**Comment by lapin7** [comment]
C'est un bon idée d'enregistrer les changements dans [ce tableur](https://docs.google.com/spreadsheets/d/1vZTg-97CCYRnodDqlOcaGlsyfXszWLJ-OT1azaZdnBc/edit#gid=0)

**Comment by kitblake** [comment]
On n'a pas les permissions @lapin7.

**Comment by lapin7** [comment]
@kitblake C'est correct. Vous n'avez rien à faire là bas. Seul le group rchainfin@googlegroups.com a besoin de travailler avec ce doc. ;-)

**Comment by lapin7** [comment]
@Viraculous please accept the invite for Github/rchain/Members. Then you are a real collaborator :-)

**Comment by Viraculous** [comment]
Merci beaucoup @lapin7 .

**Comment by BelovedAquila** [comment]
Even though am lost here, but I really love this collaboration, language has this interesting touch on things, I see RChain communicating in diverse languages around the world. Interesting.

**Comment by lapin7** [comment]
Les résultats sont saufgardé dans le doc [Symbolic links](https://docs.google.com/spreadsheets/d/1vZTg-97CCYRnodDqlOcaGlsyfXszWLJ-OT1azaZdnBc/edit#gid=0) 
L'accèss est limité!!

**Comment by MargotCoul** [comment]
@ChloeCoul et moi-même ont fini le dossier "01_08 Payment Register". 
Nous continuons avec les autres dossiers.

**Comment by lapin7** [comment]
Links have been created. When new registers are created then a specific ticket will be made for that month.
