### ISSUE TITLE
moderator of `/rchain/Releases` gitter channel?

### ISSUE THREAD

**Issue by dckc** [rchain/Members#228]
The [Node.Hello release][1] encourages feedback via https://gitter.im/rchain/Releases . I don't see that among our [moderated channels][2]. Who moderates it? @MParlikar ?

[1]: https://medium.com/rchain-cooperative/rchain-node-hello-v0-1-released-98d255a9567d
[2]: https://github.com/rchain/Members/wiki/Channels-Moderators

**Comment by Ojimadu** [comment]
RChain's developers manages the channel. I expect it to be so as most of the discussions that would be going on there would be very technical and questions would need direct answers from the dev team as they are in the best position to know the specifications of any certain release.

**Comment by dckc** [comment]
OK, when we hear from someone who speaks for the dev team, we can close this.

(@Ojimadu I'm not sure of your role in the organization; do you speak for the dev team?)

**Comment by Ojimadu** [comment]
@dckc No. I don't speak for the dev team but the text released by Nash Foster (founder of Pyrofex) on the release of the Node.Hello software contains the gitter link. So I suppose that should be under the control of the dev team. Also the [medium post](https://medium.com/rchain-cooperative/rchain-node-hello-v0-1-released-98d255a9567d) by Nash Foster indicated that they moderate the channel.

**Comment by dckc** [comment]
Ah. Right. Of course.

I updated https://github.com/rchain/Members/wiki/Channels-Moderators to list @nashef as the moderator.

**Comment by MParlikar** [comment]
I"m happy to be the moderator for the Gitter Releases channel.
