### ISSUE TITLE
Get ERC20 Token Rhoc verified

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#23]
At [Etherscan](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x5a0f67a337d8fafded3fa574e7546b529c96df89) the Coop Rchain Address: 0x5a0f67a337d8fafded3fa574e7546b529c96df89 shows that the RHOC is still unverified.

Who is going to verify this token at which institution?

**Comment by lapin7** [comment]
The RHOC can be verified at: https://etherscan.io/verifyContract

**Comment by jimscarver** [comment]
Anybody can verify the token given the source code, ABI and compiler
version that proves correct. No institution is associated with it. Someone
should do it right away having the correct info.

**Comment by jimscarver** [comment]
It is verified. Somebody took care of it.
