### ISSUE TITLE
O> Update information on RChain's website

### ISSUE THREAD

**Issue by Ojimadu** [rchain/Members#236]
- [x] The year at the footer of https://www.rchain.coop is outdated, still says 2017. It should be updated with a script that automatically updates the year without having to manually change it every time we enter a new year. 
For PHP, inserting this snippet would fix it.
```
<?php echo date("Y"); ?>
```
For Javascript
```
<script type="text/javascript">
  document.write(new Date().getFullYear());
</script>
```

- [x] The information on https://member.rchain.coop currently says 
"Thank you for your payment.

Please join the Discord server which is included in your confirmation email. To have full access to all of the Discord channels you must meet briefly appear on live video with a moderator who will verify that you are YOU."
Since there is no longer a 'member only' discord server, the information should be updated to include link to the [current discord server](https://discord.gg/fvY8qhx) on the page as well as the welcome email as a number of new members has complained of not been sent a link in their welcome email.

- [x] Fix newletter subscription link at bottom on https://www.rchain.coop/. The "Suscribe" button is not responsive.

Measure of Completion:  When the issues above get resolved.

Suggested budget: $200

**Comment by Keaycee** [comment]
Also there a new RChain logo ready to be lunch. [RChain new logo](https://github.com/rchain/style_guide_and_files/blob/master/rchain_style_guide_r1v2.pdf)

**Comment by BelovedAquila** [comment]
Yes @ojimadu, I observed that too in the contribution.Md, expecially with the year 2017, it needs to be updated to 2018

**Comment by Ojimadu** [comment]
@BelovedAquila  That was an example given.

**Comment by patrick727** [comment]
footer fixed! good catch!

**Comment by Viraculous** [comment]
I did the translation of "Invite Activists to become Member.md" to French only to be informed by a co-op member that its out dated. I wonder why it still remained in there. There is of necessity a need for updates on the Co-op website; replacing irrelevancies and out dated information on the website with latest innovations. Though never really felt it was a waste of effort doing the translation.

**Comment by lapin7** [comment]
Oops,
Yes this doc https://github.com/rchain/Members/blob/master/Invite%20Activists%20to%20become%20Member.md should be rewritten or deleted.

**Comment by BelovedAquila** [comment]
@lapin7 should it actually be deleted? Does there seem to be another membership invite to activist?, I don't think. I go with it being rewritten or updated. How do one access it for the rewriting or update please?

**Comment by Ojimadu** [comment]
I think the doc should be deleted @BelovedAquila @lapin7. Contributing.md doc cover what is on the Activist documents. 

@patrick727 and everyone, I updated the issue with a new problem. The subscription button for the newsletter on https://www.rchain.coop/ is not responsive and does not give any feedback when clicked.

**Comment by Ojimadu** [comment]
All issues raised here has been solved so am closing my first smart issue. Thanks everyone :)
