### ISSUE TITLE
D> Domain developer.rchain.coop is not working

### ISSUE THREAD

**Issue by as1ndu** [rchain/Members#245]
Any one mind sharing the server credentials  so we can fix the site?

**Comment by Keaycee** [comment]
@as1ndu Thank you for your observation, but there are assigned members on this issue. The Server credentials cannot be shared.

**Comment by n10n** [comment]
@as1ndu @Keaycee The site was moved recently and is prepared for a newer version, that is going to be rolled out by the end of this month or first week of Feb. Meantime, we are directing all traffic to https://rholang.rchain.coop (same as https://developer.rchain.coop/). Let us know if you still see the issue(s). If this is working then please close this.
