### ISSUE TITLE
M> Newsletter - February 1, 2018

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/Members#248]
I just put the [timestamps](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index) for Jan. 24th's RChain Debrief on the wiki page, so I'll go ahead and throw them in a [doc](https://docs.google.com/document/d/1etIyt4XoAsYQKaUG1nHuICSsRJzYPoL2MRhAYYVnsqw/edit?usp=sharing) and hand it off to @patrick727 to take it from there.

**Comment by TrenchFloat** [comment]
Oops - ownership can't transfer across domain names, so I can't make Patrick the owner. Anyhow, Patrick can copy/paste and put out a new doc in this issue in due time.

**Comment by Ojimadu** [comment]
@TrenchFloat Nice work. On the timestamp. I would let @patrick727 do the draft then we can continue working from there.

**Comment by patrick727** [comment]
[Here is the draft document](https://docs.google.com/document/d/1VDudBgr7Ei1pqFyb5Brc2v0G9z4Z3iY_EBs1guyCX7I/edit?usp=sharing), please use suggestion feature for edits and suggested content.

**Comment by Ojimadu** [comment]
The timestamp is in the draft is not correct. The timestamp filled in for January 17 was that of January 10. I've updated  the draft to the correct one. @patrick727 Please approve the suggestion.

**Comment by TrenchFloat** [comment]
Timestamps for today's (Jan 31) debrief are now in the [wiki](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index) and the [draft doc](https://docs.google.com/document/d/1VDudBgr7Ei1pqFyb5Brc2v0G9z4Z3iY_EBs1guyCX7I/edit).

**Comment by patrick727** [comment]
thank you @TrenchFloat !

**Comment by patrick727** [comment]
[Test draft in newsletter](http://archive.sendpulse.com/shc4c/891b879c/?_ga=2.26596477.1794896848.1517422498-85970949.1511818720)

What do you all think?

**Comment by TrenchFloat** [comment]
Looks good! If we're being picky, there are no "accompanying documents" with the timestamps for this issue.

**Comment by patrick727** [comment]
thanks I updated to this 

"Below are timestamps and any accompanying documents presented in the past two debriefing hangouts."

**Comment by Ojimadu** [comment]
Looks good.

**Comment by patrick727** [comment]
http://archive.sendpulse.com/shc4c/052b4773/?_ga=2.261939021.1794896848.1517422498-85970949.1511818720

**Comment by pythonical** [comment]
great job it looks fabulous!
