### ISSUE TITLE
Redemption explanatory video

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#25]
It would be great to have a video that explains what to do to redeem your AMP for RHOC.

**Comment by kitblake** [comment]
BTW, there are missing words in line 7 of the textual explanation:

"After confirmation of the receipt of the AMPs at the target address, the equivalent number of RHOCs in your ETH address."

Could be:
"After confirmation of the receipt of the AMPs at the target address, [you will receive] the equivalent number of RHOCs in your ETH address."
or:
"After confirmation of the receipt of the AMPs at the target address, the equivalent number of RHOCs [will appear] in your ETH address."

**Comment by lapin7** [comment]
The video I made misses the last part and it's too long. The last part is visible in this doc.
I can send you all the images and the iMovie project as well.

It just needs a voice over. And you can get rid of the back ground music.
Maybe the beginning is shit, because it uses a title role as introduction.
A short intro of what the video is about, would be much better.

Probably you can get more info from Patrick. He's more into marketing and communication stuff.

I suggest you just use your normal hour rate in USD. And then you get that converted into Rhoc. That's the coin of Rchain.

Please tell me what you think. And when you communicate with Patrick, please keep me in the loop.

The redemption process will take about 10 days more from now. So delay makes the redemption video less useful. Anyway it would serve as an example of what you're capable of.

I can make the video for you, not a problem.

Is the video you made exactly what you want except with a voice over and to be made looking professional?
And did you have a script or did you just want me to talk while I'm going through the process?

It may be useful to explain other important things while I'm going through the process so the user better understands the process.

Also, let me know your thoughts on budget.

Please take a look if you can make a video about the Redemption Process of Rchain.coop

I did this video before:
https://www.youtube.com/watch?v=Tcle23MbmQE

Here you can find some formally used logo's and such
https://github.com/rchain/style_guide_and_files
Here's a doc where we prepare messages to redeemers
https://docs.google.com/document/d/1zYIPF_awsiUkblUPdvvKGQIat5DLJCiVt3HmYXzIl0M/edit#heading=h.6ietsiobufwi
I don't know how to share the rough iMovie project with you but here is a mp4 version.
https://drive.google.com/open?id=0BwX0krsxHncTVjVJaFpiNU42Znc

In this folder I will dump all the pictures I've used:
https://drive.google.com/open?id=0BwX0krsxHncTZEFrUkxwSi1oUVk
Here's also an explanation of the process
https://medium.com/@hilbolling
If you could send all the images and the iMovie project that would be great.
Can you also send the youtube video?

I can make a better introduction but maybe if you could just write down here what the video is about just as I’m new to all of this and any information I can get is useful.

My normal rate is 50 USD an hour, does that work?

**Comment by lapin7** [comment]
@kitblake in which doc did you read that?

BTW, there are missing words in line 7 of the textual explanation:

"After confirmation of the receipt of the AMPs at the target address, the equivalent number of RHOCs in your ETH address."

**Comment by kitblake** [comment]
On the redemption page: https://redemption.rchain.coop/#!/
