### ISSUE TITLE
M > Translate 'A Rholang tutorial' into Chinese

### ISSUE THREAD

**Issue by Whisker17** [rchain/Members#275]
I've translate [this ](https://github.com/rchain/rchain/blob/dev/rholang/doc/rholangtut-mercury.md)into Chinese.Now I need some time to review it.
And I will upload the Chinese version to the [Chinese official website](http://www.rchain.site/) ASAP.

**Comment by jiyuxuan1944** [comment]
Good Job！

**Comment by yyh1102** [comment]
Maybe dup with #274 ? @lapin7 is this document a early version of tutorial?

**Comment by Whisker17** [comment]
@yyh1102 yes,I think it may dup with that issue,but I can't open the link there so that I can't check.
But I 've finished translation by myself a week ago,I think we should communicate with each other.
