### ISSUE TITLE
Create and edit Rchain  files in Baidupedia, Interactivepedia, 360pedia and other mainstream Chinese encyclopedia platforms.

### ISSUE THREAD

**Issue by jiyuxuan1944** [rchain/Members#276]
Now, it's not easy to find out about Rchain in China's mainstream search engine. But if we create entries about Rchain on a variety of Chinese encyclopedia websites, things get a lot easier. Because  most Chinese people are through Baidupedia（like Wikipedia） and other platforms to understand what they are interested in.And They think these websites to some extent represent the authority. We intend to integrate the texts that have been translated into Chinese, then create Rchain entries at Baidupedia, Interactivepedia, 360pedia and other Major Chinese Encyclopedia platforms so that more people can easily understand Rchain. Once created, these terms are not static and will constantly absorb new content, and we can easily modify the entry.
time:3 weeks
budget:$1800
TASKS:
1.Integration of existing Chinese materials
2.Optimize the way of expression
3.Create entries
4.Translation group review the entries
5.Finish the entry changes.

These are the website addresses where we plan to create Rchain entries.They are China's largest and most influential encyclopedia platform.
https://baike.baidu.com
https://baike.so.com/
http://baike.sogou.com/
http://www.baike.com/

**Comment by Whisker17** [comment]
good idea,it sounds interesting.we can do it together!

**Comment by jiyuxuan1944** [comment]
@Whisker17 Welcome！This is a big project！

**Comment by JieL314** [comment]
Just do it!

**Comment by hcl3** [comment]
This is very meaningful to promote RChain！

**Comment by jiyuxuan1944** [comment]
After a dozen attempts, we found that it is not yet possible to set up an encyclopedia for Rchain, as encyclopedia websites in China need enough references (reports from mainstream Chinese media), but Rchain has not yet been reported by the mainstream media and can not be approved. So we turn off this problem. Hope Rchain can be covered by mainstream Chinese media in the future！
