### ISSUE TITLE
M> Fix the English (Original) Transcript Mistakes of "Rchain Exclusive chat Lawrence Lerner & Nash Foster"

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/Members#292]
The original, English transcript has many mistakes that need fixing.

**Completed:** 100%
- [x] Download the video
- [x] Download the English (original) transcript.
- [x] Fix the following issues:
- - [x] Grammar
- - [x] Spelling
- - [x] Syntax
- - [x] Remove redundant words
- - [x] Add specialized words
- [x] Review each other's work
- [x] View video with the English transcript and review
- [x] Upload the English (original) transcript, [here](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)
- [x] Have it reviewed by others with knowledge of English

**Collaborators Work:**
- @ICA3DaR5: 40%
- @zero-andreou: 30%
- @thiefinshadows: 30%

**Suggested Budget:** $1000

Google Document: https://drive.google.com/open?id=1cq8hWLLrdlT6W_t07sFqYanXEwwbjBSvcJv92aoKO5s
SRT File: https://drive.google.com/open?id=1nl5ctTmA9FNK_uS6K2nN2m3gyzZJCIgY

**Comment by Viraculous** [comment]
please post the the original link of the English version being worked on

**Comment by ICA3DaR5** [comment]
I am almost done, I'll upload it as soon as I am done!

**Comment by Viraculous** [comment]
OK. @ICA3DaR5.

**Comment by BelovedAquila** [comment]
@ICA3DaR5 would love  collaborating with you guys on this

**Comment by ICA3DaR5** [comment]
@BelovedAquila We are almost finished. Perhaps on another issue? :)

**Comment by ICA3DaR5** [comment]
@BelovedAquila [Here's the file](https://gist.github.com/ICA3DaR5/857d0b884b857671c77603df809243e7)

I'll finish some minor details tomorrow.

**Comment by BelovedAquila** [comment]
@ICA3DaR5 I see you have done a good work on it but I can still review it, I sited some few things needing corrections, if you don't mind?

**Comment by ICA3DaR5** [comment]
@BelovedAquila Sure.

**Comment by ICA3DaR5** [comment]
@Tonyprisca13 I see you self-assigned this. Why is that?

**Comment by BelovedAquila** [comment]
@ICA3DaR5 send me an access link friend.

**Comment by ICA3DaR5** [comment]
@BelovedAquila I've put it on a GitHub Gist for the moment. https://gist.github.com/ICA3DaR5/857d0b884b857671c77603df809243e7

Me, @thiefinshadows and @zero-andreou are working on this. It's almost ready. Be a little patient. We are working on this all night and day.

**Comment by Tonyprisca13** [comment]
can I collaborate with u

**Comment by ICA3DaR5** [comment]
@Tonyprisca13 We're almost finished and we're doing this by watching the video and fixing the transcript at the same time.

**Comment by BelovedAquila** [comment]
@ICA3DaR5 alright friend.

**Comment by ICA3DaR5** [comment]
I think this is finished.

**Comment by BelovedAquila** [comment]
@ICA3DaR5 I suppose you are done already? Can I have an access to the Doc so as to review it?

**Comment by ICA3DaR5** [comment]
@BelovedAquila Sure I uploaded it. There is a link on the first post.

[Here's the link](https://docs.google.com/document/d/1cq8hWLLrdlT6W_t07sFqYanXEwwbjBSvcJv92aoKO5s/edit) again.

**Comment by ICA3DaR5** [comment]
I'll watch the video with the English transcript, one more time, tomorrow, and I'll call it a day.

**Comment by Mervyn853** [comment]
Can I get the completed .srt file to send to Brad when it’s done? Would prefer it in srt file as there are many google docs that I have to sort through for different languages

**Comment by ICA3DaR5** [comment]
@Mervyn853 Sure, once I finish (in a few hours), I'll also upload the .srt file.

**Comment by ICA3DaR5** [comment]
This is finished as far as me, @zero-andreou and @thiefinshadows are concerned!
