### ISSUE TITLE
info@rchain.coop responses

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#34]
"Good morning,

We would like to host a Q and A feature about Rachin on invesitin.com InvestItIn.com connects investors with investment ideas. We have more than 500 investors visiting our site a day.

Thanks
Mike Thompson"

what do you guys think?

**Comment by lapin7** [comment]
I don't know if I'm the man to promote Rchain for Investors. We could go through the [already visible start-ups](https://www.investitin.com/) and see what they say. Then we could set up a paper for investors for Rchain. Greg and Ed have to be involved in this. We need also more hands to do this kind of work. Let's propose a bounty :-) in Slack.

**Comment by lapin7** [comment]
There is a Private Sale set up. No need for this anymore.
