### ISSUE TITLE
Video Summary - RChain Roadmap Overview

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#38]
It would be great to have a text summary of video's, for example:
- explaining the [Roadmap overview](https://www.youtube.com/watch?v=z6RXHsH_JOc&feature=push-u&attr_tag=bj2PZsdealBop0xc-6)

**Comment by patrick727** [comment]
I agree. This helps for alot of different reasons and can be consider into the "Curation/Aggregation" Project board

**Comment by lapin7** [comment]
I hope this problem of "tax payments and invoicing" is pretty soon solved.
Then we can put bounties on these kind of tasks. Like 100 USD per summary
(can be teamwork as well).

Probably it's best to withhold like 30% tax on each payment and that RChain
pays it to the tax office. That would guarantee also a continuous flow of
RHOC to the market. RChain is then obliged to convert big amounts of RHOC
into BTC and then USD.




--
Cheers,
HJ
