### ISSUE TITLE
RChain - Jobs Post - Content

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#39]
I have contacted Nash and Greg about providing job descriptions for job postings to link to. 

If someone with more technical depth like to draft up some job descriptions that would also help. 

Language developer
Comms
Cryptographer
API developer
Contract developers

**Comment by patrick727** [comment]
Confirmed that Nash is working on this. 

I am going to create another post about highly qualified places to link the job posting to make sure we get the best candidates.

**Comment by lapin7** [comment]
Nash and Pyrofex are working on this
