### ISSUE TITLE
"Likely Linkers" Game. 

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#40]
This is the first draft to an outline for a "Likely Linker" game. 

The goals are to leverage swarm intelligence to find the highest quality opportunities for potential inbound links to RChain related content. 

Many of us are networking around freely and are coming across these opportunities without even realizing it. I wanted to start this game to get in the habit of continually posting these opportunities to a map in which I can then reach out to the sources for the link. 

Linkbuilding is a key to building SEO over time and with the communities help we could growth hack our SEO efforts! 

First we still need to iron out some of the game guidelines and mechanics and then we can start the actual experiments if you'd like

[](https://docs.google.com/document/d/1knZqRlmg45J44irfzEojOrLWMnrj40BZ4NPp9wK0RQs/edit# )

**Comment by patrick727** [comment]
https://docs.google.com/document/u/1/d/1knZqRlmg45J44irfzEojOrLWMnrj40BZ4NPp9wK0RQs/edit?usp=drive_web

**Comment by patrick727** [comment]
I started inputting some likely linkers into the spreadsheet. will spend sometime at the end of the week reaching out. If anyone knows of awesome sources they have a contact too, please let me know thankyou!

**Comment by kitblake** [comment]
Looks good @patrick727. I could contribute some resources. 

As a test I just added a link, to the bounty list of a frenemy initiative, in the "Likely Linker Game - Content" spreadsheet.

**Comment by patrick727** [comment]
thanks @kitblake so what we are looking for is places where we can add a link to RChain content.

An example would be the university of Denmark computer science program. They may want to link to RChain's educational resources such as the platform documentation or the "Intro to RChain" Video 

I don't believe that we can add a link to RChain content from that eternity post. Where do you think that we could? 

I appreciate you engaging with this game because it is in the early stages. Great feedback!

**Comment by patrick727** [comment]
Email outreach template for 1st contact with Computer Science / Mathematics Programs

https://docs.google.com/document/d/1pb9qKa4pLRA36A8Em0_IKdXFCj_Ed4P4WN00HvwaCF4/edit#

What do you guys think?

**Comment by patrick727** [comment]
@lapin7, Joseph said that the "Rholang Turorial" will most likely be created around the 26th of June.
