### ISSUE TITLE
How to deal on exchanges like Oasis or EtherDelta

### ISSUE THREAD

**Issue by magicmirage** [rchain/Members#45]

**Comment by lapin7** [comment]
Great.
Let's first define a kind of script for the video.
And let's think about a campaign how to make RHOC listed on Exchanges a succes.

**Comment by magicmirage** [comment]
Is below from @kdvalentine along the lines of what you are looking for @lapin7? 

1. Install Google [Chrome](https://www.google.com/chrome/)

2. Install the [MetaMask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en) Chrome Extension

    1. Click "Add to Chrome" to Install MetaMask as Google Chrome extension.

    2. Click "Add Extension" to confirm and MetaMask will be added

    3. Create a new wallet by clicking the MetaMask logo and agree to the MetaMask terms and Conditions

    4. Click "Create a new vault" with a strong password and click "OK"

    5. Metamask will show you your seed. Copy and store those 12 worlds, without them you cannot restore your wallet.

    6. In the upper right corner, change to the "Ethereum Main Net" & fund your account

    7. You will need to be logged into MetaMask to use either Oasis or EtherDelta

3. For OASIS

    1. Go to [Oasis](https://oasisdex.com) 

        1. Before you trade you will need to "deposit" ETH. Because ETH does not follow the EIP-20 standard the token needs to get 'wrapped' in a special smart contract first to turn it into an EIP-20 token. This is because ETH existed before the EIP-20 standard existed. 

            1. Go to wrap/unwrap and wrap ETH to turn it into W-ETH.

            2. Go to Trade and place new orders or trade existing orders by clicking on an open order on the order book to buy/sell into it.

            3. The first time you make a transaction you will be prompted to set your allowance. 

        2. The RHOC market is [https://oasisdex.com/#trade/W-ETH/RHOC](https://oasisdex.com/#trade/W-ETH/RHOC)

4. For ETHERDELTA

    1. Go to [EtherDelta](https://etherdelta.github.io/)

    2. In the Upper left frame titled "Balance" deposit ETH

    3. In the frame below titled "Volume", select the [ETH/RHOC](https://etherdelta.github.io/#RHOC-ETH) Pair

    4. Place Buy or Sell order in the "New Order" Frame

5. Caveats

    1. Low Liquidity

**Comment by jimscarver** [comment]
Vely good! Parity had more functionality than metamask so we probably want instruction for parity as well.  You install and run parity on your machine and can use with or without the browser plugin by browsing to dapps within parity. It keeps an address book and runs contracts so you can use it to send rhocs and run other contracts we may use for rewards etc.

**Comment by lapin7** [comment]
Parity works a lot better than meta mask. 
Great experience.

**Comment by lapin7** [comment]
@kitblake is this manual also in the FAQ

**Comment by kitblake** [comment]
Good idea, I added it.

**Comment by kdvalentine** [comment]
1. Install Google [Chrome](https://www.google.com/chrome/)

2. Install the [MetaMask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en) Chrome Extension or the [Parity Ethereum Wallet](https://parity.io/parity.html)

    1. Install MetaMask

        1. Click "Add to Chrome" to Install MetaMask as Google Chrome extension.

        2. Click "Add Extension" to confirm and MetaMask will be added

        3. Create a new wallet by clicking the MetaMask logo and agree to the MetaMask terms and Conditions

        4. Click "Create a new vault" with a strong password and click "OK"

        5. Metamask will show you your seed. Copy and store those 12 worlds, without them you cannot restore your wallet.

        6. In the upper right corner, change to the "Ethereum Main Net" & fund your account

        7. You will need to be logged into MetaMask to use either Oasis or EtherDelta

    2. Install Parity

        1. Download the installer that corresponds with your operating system

        2. Once installed, Parity will prompt you to install the [Google Chrome extension](https://chrome.google.com/webstore/detail/parity-ethereum-integrati/himekenlppkgeaoeddcliojfddemadig)

        3. The first time Parity runs it will open a browser window at [http://127.0.0.1:8180](http://127.0.0.1:8180) and you will be prompted to create a new Ethereum account. After account setup, the blockchain will need to fully sync before using a decentralized exchange. Ethereum clients use a listener (TCP) port and a discovery (UDP) port, both on 30303 by default. To speed the discovery of nodes, make sure port forwarding for UDP/TCP is enabled on port 30303

        4. Fund your account

        5. Parity must be running (the Chrome extension will be ‘green’) to trade on the decentralized exchange

3. Oasis Dex

    1. Go to [Oasis](https://oasisdex.com) 

        1. Before you trade you will need to "deposit" ETH. Because ETH does not follow the EIP-20 standard the token needs to get 'wrapped' in a special smart contract first to turn it into an EIP-20 token. This is because ETH existed before the EIP-20 standard existed. 

            1. Go to wrap/unwrap and wrap ETH to turn it into W-ETH.

            2. Go to Trade and place new orders or trade existing orders by clicking on an open order on the order book to buy/sell into it.

            3. The first time you make a transaction you will be prompted to set your allowance. 

        2. The RHOC market is [https://oasisdex.com/#trade/W-ETH/RHOC](https://oasisdex.com/#trade/W-ETH/RHOC)

4. EtherDelta

    1. Go to [EtherDelta](https://etherdelta.github.io/)

    2. In the Upper left frame titled "Balance" deposit ETH

    3. In the frame below titled "Volume", select the [ETH/RHOC](https://etherdelta.github.io/#RHOC-ETH) Pair

    4. Place Buy or Sell order in the "New Order" Frame

5. 0x OTC

    1. Go to [0x OTC](https://0xproject.com/otc)

    2. Place a Buy order by choosing the ERC20 token you want to purchasing by clicking the icon. Choose the option to add "Other ERC20 Token"

        1. Add the token name: RChain

        2. Add the token symbol: RHOC

        3. Add the contract address: 0x168296bb09e24a88805cb9c33356536b980d3fc5

        4. Add the Token decimals: 8

    3. Enter in the amount you want to sell & buy

    4. Sign the transaction hash to place your order

6. Caveats

    1. Low Liquidity

**Comment by kdvalentine** [comment]
I updated the information to include how to use Parity. I also included directions for placing an order on the 0x OTC. I don't know what the trading liquidity is but it may be a platform that will gain traction given the popularity of the ICO.
