### ISSUE TITLE
O> Donating earned RHOCs 

### ISSUE THREAD

**Issue by plantether** [rchain/Members#46]
It would be great to be able to donate earned RHOCs to a project or cause we like. If RChain is willing to match donations, that would create more incentive for people to donate and spread more RHOCs around.

For example, I would like to see a fund set up to help finance Vlad's work.

**Comment by patrick727** [comment]
@plantether so you'd like a formal process for being able to donate your earned rhocs, such as a section on the SOW? 

I like the idea, but there could be an infinite amount of things to donate too and who would manage that distribution. To me this could be performed autonomously and added to a signature or github board. 

IT would make sense for certain pools to form that RChain would want to back, such as Vlads research, but my assumption is that those would need to be specific and each deal done individually with the coop.

**Comment by plantether** [comment]
I don't think a formal process is necessary to donate earned RHOCs because I can just put any ETH address I want on my SOW. 

I agree that each recipient that would receive matching funds would require a separate deal with the co-op. What I would like to see is certain RChain-approved funds with matching. If people like the idea, I see it working something like this. We could present a resolution that would be voted on by members/activists, and if the majority agree or don't disagree, it would be presented to the board, or to HJ if he has authority to approve them. 

This is something that can also be publicized to encourage others to do the same.

**Comment by kitblake** [comment]
@plantether @patrick727 Nice idea. I could imagine the same process for collectively choosing startup initiatives to support (other DAO-like initiatives are doing this). 
It's also reminds me of the optional "I want to pay for my carbon footprint" opt-ins when booking travel tickets.

**Comment by lapin7** [comment]
@plantether I suggest that activists publish a RHOC-receive address for sponsoring by others.
