### ISSUE TITLE
Website - Edits & Updates

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#47]
Keeping the conversation ongoing about building out the next generation of RChain's websites and web presence.

**Comment by Rafkraft** [comment]
Hello everyone,

I'm Raf, 23, I've been javascript developer (Node / React / Redux) for three years now,. Worked on some high-audience public website and some private spatial-sector related javascript apps (desktop and web).

I think RChain is a great project and a fresh rebranding of the website(s) could be a key step towards wider public knowledge, support and adoption.

Nothing new here, some key aspects would be:
- Very good-looking, clear and user-friendly design
- Ultra-fast response time, easy navigation, universal-rendering
- Dynamic content, social related sections (Twitter, Medium etc...)
- Good and intelligent SEO optimization
- Easely editable pages (to minimize intervention of the developper for basic updates, .MD files for example, representing each static page of the site)

All this could be powered by a Node JS server, using some last technologies such as facebook's React JS, Next JS (100% open source), and a modern CSS library like semantic UI.

Both http://www.rchain.io and http://www.rchain.coop/ shoulg get a refresh in my opinion.

I'm not a designer though, could be great if someone with good design skills work on some maquette. If not I can totally make a demos in the first place, and we'll see ;-) .

Let me know what you think

**Comment by patrick727** [comment]
@Rafkraft thank you very much for the input. 

Do you have connections for designers that you work well with? They'd be a great addition. i reached back out too hannah adams and have not heard back yet. 

Some scoping and/or a demo would be a great place to start and we can continue the discussion on the next community hangout. 

Cheers

**Comment by Rafkraft** [comment]
Hey

I'm afraid I do not know a designer for this.
A cool logo + visual identity could be very cool indeed.

Ok I'll try to build a demo, 3-4 days to get something decent (sunday / beginning of next week).

**Comment by patrick727** [comment]
Great!

I reached out to my old friend I used to work at an agency with. I gave him some Ether back in the day so I know he's happy about that now and may be willing to do some work with RChain lol. We'll see if he has some time but ill stay on the lookout. 

The logo+visual identity stuff you can find in the original style guide. 
https://github.com/rchain/style_guide_and_files

If you are suggesting something totally different, that will open up a large community discussion, as there are many parties considering branding, including the token logo's for RHOC and REV, etc. 

The best bet (although risky when considering your available time) would be to hammer out some sort of demo/mockups and propose it the community meetings. If it attracts enough attention it will be opened up to some sort of voting and then we can make the updates after a considerable amount of the influence s weigh in on it.

**Comment by Rafkraft** [comment]
Hey first maquette here http://37.139.30.113 for http://rchain.io
Nothing definitive though. Any advice / idea is welcome :)

I took an image from [pexels.com](https://www.pexels.com/) (license free)

Still a lot to implement, I'm working on provinding a as simple as possible page addition/edition/removal. (directly using github edition tools ideally).

All the metatags (image, title ant content for twitter, facebook and google visuals) will also be easily editable for each page. I'll put the code on github soon, easier to follow.

**Comment by patrick727** [comment]
Nice stuff @Rafkraft will give some feedback tomorrow!

**Comment by kitblake** [comment]
Something is off with the Contact page, I'm getting: 

iframe.contentWindow.document.querySelectorAll(...).forEach is not a function

Maybe it's not implemented yet..

**Comment by Rafkraft** [comment]
http://37.139.30.113/ version 0.2

New header, and title. **Much faster rendering**, taking full advangate of next js capabilities :-) 

To do:
- Responsive rendering (mobile, tablet...)
- Favicon
- Implement meta tags and images for each pages (images and texts appearing when sharing on twitter / facebook / other...)
- "Share on ..." buttons
- **Need for a designer**, could be good to have nice (maybe our own) icons like lykke's website for example https://www.lykke.com/
- Find image to illustrate the points, I'll try to do something cool.


A big part of the work is on the editorial side, need for more content. A medium account could be great for posting articles, it could be linked to the "Media" section of the site.

I'll work on most of this points in the next days

Have a nice weekend !

@kitblake I removed the piece of JS code responsible :-) thanks

**Comment by patrick727** [comment]
Thanks for putting this together. @Rafkraft 

The team at shoottothrillmedia.com (work at a co-work i frequent) also have engaged me about helping to build a new website for rchain.coop moving forward towards mercury release. 

It be nice to lay out the criteria with some examples for the layout/function/theme of each website(coop+holdings) moving forward so they can compliment each other in design and use. 

Also we need to take a patient approach because there are some rebranding considerations going around. 

Such as the mercury release and the potential for the token name to change from REV. 

Either way this is great groundwork and we appreciate that engagement. 

We should meet with navneet and ed soon to discuss these topics.

**Comment by Rafkraft** [comment]
Ok, so I guess I'll let development aside for now.

If shoottothrillmedia takes care of rebranding/design/theme and integration that's cool, as I said, my skills are on the integration/user experience//easy content-editable side.

I'll be glad to keep on helping RChain coop so I'll wait for update from you if RChain website integration/maintenance needs developper :-)
slack -> @lamouette

**Comment by patrick727** [comment]
@Rafkraft perfect great! and thank you for your patience. 

@nathanwindsor and I will be coming up with a branding document that we can build on top for both websites. 

Please stay engaged in the conversation around design/theme and user experience, we'd love your input continually. 

Cheers

**Comment by patrick727** [comment]
Another interesting thing to explore is community channels and how to design UX to be the most productive per sentence written. I always believed looking at the daohub.org during there height that the discourse instance with upvoting and downvoting of posts was a good way of accomplishing that. But there may be more tools and process underway now. @Rafkraft that would be another area we would like to figure out in the near future.

**Comment by patrick727** [comment]
[Website Ideation Document](https://docs.google.com/document/d/1jyYV9CAYs8LhfwCwcsf8D-Z8sez71hSGepf_NfmRIus/edit#heading=h.g3t6czwfq9op )

Here is the document that we are working on, @Rafkraft thanks for your help earlier on in the year. 

Currently top-level branding is also being worked out which will inform the design and messaging further. 

I'd like to see the new site up before new year, once budget it worked out we can set better deadlines. 

Contributions will be noted and appreciated!

**Comment by patrick727** [comment]
@Rafkraft are you still around?

**Comment by patrick727** [comment]
Hey guys, here's an update on the website design process. 

1. had a meeting with Valeria to discuss some style options. [This is a first draft presentation](https://trello-attachments.s3.amazonaws.com/587793d71b049b0c4f1af9d8/59838a951e02ea781158081e/2ffa0d76c9a34a7971e73bc881d19dd6/R_CHAIN.pdf) for some of the ideas discussed. 


2. Went ahead and [mocked up a look for the website](https://docs.google.com/drawings/d/1n4OUyO12irUdNRgC1Sxh90I0aHIQfW2S_dqx-5Gc9qU/edit), heavily inspired from makerdaos website. keep in mind the color scheme, graphic placement and design elements are all subject to change, this is the first iteration. 

I'd like to get some user journeys done, the more granular the better too because the personas can be used across all of our R&D. the key personas are Developers and Investors and they can become as specific as possible. 

Feedback welcome, as I am to follow up with her on Friday most likely.

**Comment by patrick727** [comment]
[Existing Style Guide: ](https://github.com/rchain/style_guide_and_files/blob/master/rchain_style_guide_r1v2.pdf)

[Resource for color schemes](http://www.colorhunt.co/c/71918) 

[Brand guidelines example](http://6b73c1981cbfc5df9840-995bb1ec94e14bbd8f89f23fee4d0b6a.r66.cf2.rackcdn.com/YMCA/Brand_Guidelines_Graphics/graphic_standards.pdf)

There is discussions during the relogo design for new colorscheme. nathan and I are working to reach consenus about some of the colors, so far the attached two colors schemes have been suggested

1 - https://ourchain.slack.com/files/nathanwindsor/F6NSP1L01/screen_shot_2017-08-16_at_11.21.08_am.png

2. - https://ourchain.slack.com/files/patrick727/F6PEQCGLC/organe_blue_green.jpg

**Comment by lapin7** [comment]
@Rafkraft needs probably a reward for his work.

**Comment by Rafkraft** [comment]
Hi all !

I'm here, just came back from vacation, I'll read the documentation that has been uploaded, and come back with comments.

Still 100% available to work on the website.

As you can see here http://37.139.30.113/ I'm still working for some cool template that might be adopted for the website.

Raf

**Comment by patrick727** [comment]
Cool work @Rafkraft thank you for your patience. I have been talking witha  designer as well too so we may be able to work out something together. 

Can we set up a time next week to talk more about this? 
What is your handle on slack? 

Cheers

**Comment by Rafkraft** [comment]
Improvements:
- RChain blue theme (can be changed easily to another color)
- Brought content from rchain.io and rchain.coop
- Technology section, I just copy & pasted the first part of the whitepaper

I just replicated the content, even though I think paragraphs and sections should be 100% rebuilt after reflexion and studies ;)

https://rchain.fabcon.tech

**Comment by lapin7** [comment]
That looks great. Who is deciding for the switch to the new layout?

--
Cheers,
HJ

**Comment by lapin7** [comment]
Dear @Rafkraft,

To my knowledge you didn't fill out the form Activist Registration
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg%2Fviewform&si=5281391242641408&pi=b02c6623-1db5-4a4e-afda-f9e5f949a3e5>.
This is necessary for getting rewards in RHOC for your TIME.

You may also allocate a budget and a reward for the month of September for
issue #47 through form Budget allocation and - spending
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA%2Fviewform&si=5281391242641408&pi=b02c6623-1db5-4a4e-afda-f9e5f949a3e5>

--
Cheers,
HJ

**Comment by Rafkraft** [comment]
Thank you for these infos, I'm taking care of that today ;)

**Comment by lapin7** [comment]
@Rafkraft 
Currently the [allocated budget](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1634773129) for issue #47 is:  ⍴ 15,666.67


Issue # | Link | Status | Project / Issue |   | ⍴ AVG
-- | -- | -- | -- | -- | --
47 | https://github.com/rchain/Members/issues/47 | In progress | Website - Edits & Updates | Set | ⍴ 15,666.67
 
It is set by @patrick727 , @kitblake and myself. However this budget setting may change during the month of September. Because more Activist can set the necessary budget to their best knowledge.
Your reward is not yet approved or set by another Activist then me. I've set the amount of work done to 25%. You need at least one more setting, done by yourself or somebody else who's also assigned to this issue.

Github Issues |   |   | ⍴ Budget | ⍴ To Pay | ⍴ Delta | $ Budget | $ To Pay | $ Delta | Activist | AVG work
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
47 | [url](https://github.com/rchain/Members/issues/47) | Website - Edits & Updates | ⍴ 15,667 | ⍴ 3,917 | ⍴ 11,750 | $ 1,567 | $ 391.67 | $ 1,175 | Rafkraft | 25%

In October the Budget and Reward are frozen and the payment process will start.

**Comment by patrick727** [comment]
@Rafkraft this is great work! Please lets be patient because id like to get the designer that I am working with involved with this process as well. It will make things work better in the long term. 

@lapin7

**Comment by lapin7** [comment]
@Rafkraft 
Please add yourself as a collaborator to this Repository RChain/Members.
Then you can be assigned to this Issue and get RHOC as a reward for your TIME.
[Sign up](https://github.com/rchain/Members/invitations)

Thx

**Comment by Rafkraft** [comment]
- I assigned myself to this issue
- To be a contributor of the project, I must have at least one commit on this repo, I don't have anything to commit on this repo, I'm working on another one (private one) for now.

I filled up the form to became RChain activist, didn't receive any update on my status so far, am I ok or did I miss something ?

By the way, the url changed -> https://rchain.fabco.tech

@patrick727 noted, I'm waiting for news from you to work on the website.

**Comment by patrick727** [comment]
@Rafkraft i believe its comment not commit. 
@lapin7 should be confirming your activist submission in no time. Lets also get you to registrister as a member of the cooperative if that is something you are interested in. 

Thank you for waiting for the designer, you will recieve rhocs rewards for the work done up until this point and then going forward as well. 

cheers!

**Comment by patrick727** [comment]
Hey @Rafkraft ! Here is the first draft back from the designer on the website https://preview.webflow.com/preview/rch-35ecec-60ff624c600ad0-fa626c6d317d3?preview=a195789934c854a0f0c52675a6259724 

What does everyone think? 
Are there activists on here that want to have a working idea session for the website moving forward, would be a nice exercise at the members meeting as well. 

Cheers

**Comment by Rafkraft** [comment]
Very cool draft

My main concern about it: too much colors, first page is orange/green, second is green/blue, bottom is all blue, plus the pink of the logo. There is too much color. The general tone and color is interesting but I think it could be more focused on 2/3 max main colors (I vote for the dark green as main color).

**Top section:**
- Cool header
- The image is cool, but maybe a bit complex. Rchain's technology is complex, but the platform, when released, should work smoothly and organically. The image does not express this in my opinion, it looks like a complex stuff on first sight.

On the website's homepage and first top-section, things must be presented in a more simple way IMO.

**"Dive into the tech" section:**
The images are great, my opinion on each of them:
- Concurency: cool schema
- Rholang: here I think we could simply have a logo for Rholang (every langage has its logo)
- Namespace: The image should express the same thing as scope/section
- Multichain: here I'm visualizing a web divided in 2/3, each sub-web is linked to the others, they could be distinguishable by their color.

**Footer:**
Cool !

**Comment by patrick727** [comment]
@Rafkraft thanks for the feedback. 

I like the color scheme, but would be interested to see what you do with it based on the feedback that you gave. 

Would you like for me to pass this feedback on to the designer? maybe give me a couple more action items, or you could take this and run with it to see what you come up with? 

These discussions are the "ideation" and super important so please do include this time in your considerations of the budget for this and I will back it.

**Comment by Rafkraft** [comment]
I can run with it since there is some changes to code, I think it will in fact be faster too have a mockup -> code -> mockup -> code workflow.

So I'll work on the implementation of this mockup for now, and we will probably have a clearer view of what needs to be improved. I think I will have something online in 4-5 days.

PS @patrick727 : I sent a PM on slack, asking for direct contact to chat with the designer.

**Comment by patrick727** [comment]
@Rafkraft nice i got your message and sent you the email. 

I agree about the workflow so we should coordinate through email about dates and times to chat about the iterations. 

thanks again!

**Comment by sportshark** [comment]
@patrick727 @Rafkraft here we go! I can help translate the website to chinese The new site should have multiple language interfaces.And I know a litte of NODEJS

**Comment by patrick727** [comment]
@sportshark awesome for taking the initiative. One thing I have to wonder is how I will verify that it is correct? 

You can collaborate with us in this issue but for your own bounty reward we will assign to the translation issue. 

Cheers

**Comment by patrick727** [comment]
Hey Guys, im going to close this issue because we now have a dedicated project to website updates.

Thank you everyone for your input. lets continue to collaborate!!!
