### ISSUE TITLE
Rchain email addresses and calendar

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#5]
Maybe there's already an 
hello@rchain.coop 
email address that can handle incoming mail from stakeholders.

**Comment by lapin7** [comment]
DrBloom proposed this.

The .coop email server has a limited number of addresses available and we are each using addresses based on our roles rather than our names.

For example:
president@rchain.coop is for Greg
director1@rchain.coop is for Ed
admin0@rchain.coop is for Ian
Each of these accounts is set to forward to our personal emails.
admin0 forwards to drbloom@gmail.com
director1 forwards to livelygig

Currently info@rchain.coop is set up as a GROUP email address, meaning that several of us can send and receive emails using info@rchain.coop

Unless there is a better name, I propose that we set HJ up with the email account:
ops@rchain.coop and that ops account be added to the info@rchain.coop GROUP.

**Comment by lapin7** [comment]
Drbloom (Ian) says: 
I don't expect any problem other than the hassle of setting up forwarding between your .coop email and your personal email.
None of us has _personal_  .coop addresses. We are sticking to roles.
You will have to set up the forwarding yourself and will have access to a zoho email portal from which you can change password and adjust settings (forwarding).

**Comment by drbloom** [comment]
OK. I set up a public (group) calendar for info@rchain.coop

While logged in to ZOHO you can access your calendars at:

- https://calendar.zoho.com/mycalendar#

The public link to the info@rchain.coop calendar is:
- [info-html](https://calendar.zoho.com/group/embed/801addb658739c25ad897aa0008b4d9c0a7b48d630127a8ce87f6b2af3a3e91a053bc93dc939854ea6712b4753ab7c16)

The ICAL link to the info@rchain.coop calendar is:
- [info-ical](https://calendar.zoho.com/group/ical/801addb658739c25ad897aa0008b4d9c0a7b48d630127a8ce87f6b2af3a3e91a053bc93dc939854ea6712b4753ab7c16)

Many templates are available for embedded (widget) versions of the calendar, suitable for websites.

The info@rchain.coop distribution group currently has 2 members:
- admin0@rchain.coop
- ops@rchain.coop

Both of these members are set up as 'moderators' for the group.
Only group members are able to create & edit events.
All emails sent to info@rchain.coop are routed to these members.
