### ISSUE TITLE
M> Social Media Calendar - Automation Tool

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#53]
M> Indicates that this task is in the "Marketing" Category 

Goal:

Weekly Scheduling of content 

[Tweet Sheet](https://docs.google.com/document/d/1sCQTU9aIPwuk6uomRrP6McqUepULkjLvmuhvlucXinE/edit#heading=h.64d7j8g4smww)

Facebook Posts
No Document

Linkedin Group Messages
No document

[Content Sharing Spreadsheet](https://docs.google.com/spreadsheets/d/1n7xKBt_uwe343G1WxCpqKrySTmjH8PL4GKTlWCv_9Hg/edit#gid=0)

If you guys would like to make RChain's Social media presence robust and inclusive, please share ideas and resources for more curation, automation and targeting for these platforms and any others that you see fit.

**Comment by patrick727** [comment]
This project is dependant on the completion of and Editorial calendar with themes and messaging plotted out.

We can use something like a hootsuite free account or buffer to automate social messages, right now im personally managing the twitter, facebook, linkedin and linkedIn group and it's not too bad to schedule through each of their independent interfaces. 

For getting the community to share content through their social networks I recommend leveraging the slackbot and [auto-share links](http://www.sharelinkgenerator.com/) with some preloaded copy, or suggested copy.

**Comment by lapin7** [comment]
@dckc I'm not working on the [CoopCalendar](https://github.com/rchain/Members/wiki/CoopCalendar), however that would be very useful. Please pick it up.

**Comment by dckc** [comment]
I was referring to work you had already done.

Is there more work to do? If so, what is it? And how would someone like me pick it up?

**Comment by patrick727** [comment]
So this is actually going to get picked up by Alberto most likely. 

He is in discord and will get him into github soon.

thanks

**Comment by lapin7** [comment]
With concern to that wiki page:
2017-11-29 >> @lapin7 thinks that this calendar in ZOHO is obsolete. There's a Google calendar in place. One can find that calender #calendar of Discord.

@dckc the wiki page has to be updated with:
- link to the iCal
- who can update, add events and so
- where to publish

**Comment by patrick727** [comment]
@lapin7 he is not on github yet. i will get him on soon, he is a member though on discord @alberto jauregui

we will most likely use a combo of airtable, meetedgar and hootesuite

**Comment by lapin7** [comment]
@patrick727 You can invite @alberto as a collaborator on Github/Members through https://github.com/rchain/Members/settings/collaboration

**Comment by alberto** [comment]
please don't @ me.

**Comment by kitblake** [comment]
This is off-topic but the Collaborators list is almost full. There's one seat left. However there are many unaccepted invitations, so if it's full, delete the oldest invitations at the bottom.

**Comment by patrick727** [comment]
@lapin7 that is not the same alberto. 

@kitblake collaborators to what?

**Comment by kitblake** [comment]
@patrick727 Collaborators in the /Members repo. You'll see it when you add someone.
