### ISSUE TITLE
The link at the bottom of this paragraph is broken.

### ISSUE THREAD

**Issue by entropee** [rchain/Members#54]
In the architecture document at  http://rchain-architecture.readthedocs.io/en/latest/execution_model/rhovm.html , the link to github is broken. This may be because the rate limiting code has gone dark, but the link should be fixed. 

"Rate-limiting Mechanism
The compilation pipeline will implement a rate-limiting mechanism that is related to some calculation of processing, memory, storage, and bandwidth resources. Because the rho-calculus reduction rule is the atomic unit of computation on the RChain platform, the calculation of computation complexity is necessarily correlated to the amount of reductions performed per contract. This mechanism is needed in order to recover costs for the hardware and related operations. Although Ethereum (Gas) has similar needs, the mechanisms are different. Specifically, the metering will not be done at the VM level, but will be injected in the contract code during the analysis phase of compilation.

For more details join the #rhovm channel on the RChain Slack here. Compiler work can be seen on GitHub."

**Comment by entropee** [comment]
Related to this issue, the links at the top of the #rhovm channel on slack are broken.

 "We've pledged to do a modernization of Rosette VM to achieve the concurrent RhoVM. Rosette found here: https://github.com/OurChain/Rosette-VM.git"

**Comment by lapin7** [comment]
I've made an issue at the page it self.
https://github.com/rchain/architecture-docs/issues/9
Maybe that helps

**Comment by JosDenmark** [comment]
Fixed

**Comment by lapin7** [comment]
@entropee please in [Gsheet RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=1970624799) allocate a budget and a percentage amount of work spend on this issue
