### ISSUE TITLE
Summaries and Transcripts of hangouts and other videos

### ISSUE THREAD

**Issue by entropee** [rchain/Members#59]
If anyone else is doing this, please let me  know. I have taken a stab at summarizing the latest hangout. The audio was bad when it was live. I have also provided a transcript (loaded with errors but still searchable.) Please let me know what you think. This took me about two hours but I could cut it down a lot. I have provided time keyed links to each summary.

Streamed live on Jun 14, 2017
Rchain Community Debrief 29
The rest of the content has been deleted by @lapin7 and you still can find it [here](https://github.com/entropee/rchain-transcripts/compare/master...lapin7:patch-1)

**Comment by patrick727** [comment]
@entropee this is great thanks! Will be of valuable use in the next newsletter draft!

Do you want me to go ahead and assign yourself to the other summaries?

**Comment by entropee** [comment]
Where should I put the other summaries when I get them done?

**Comment by patrick727** [comment]
A summary google doc would be nice that you could link to in here!

**Comment by patrick727** [comment]
@entropee did you get a chance to review/summarize last weeks hangout that I missed?

**Comment by lapin7** [comment]
Is it possible to do the summary in MD format?
And get it as an item on a blog of RChain?

**Comment by entropee** [comment]
@lapin7 Yes, I am working with @jimscarver using github pages to have a way to access the transcripts and caption related files. here is the link:  https://entropee.github.io/rchain-transcripts/ @patrick727 I have backpeddled a bit with development side of things. I will work on the most recent debriefs, first. I'm hoping that people that watch videos can either enter the corrections on github, or provide me with instructions on what needs changing.  Any suggestions or ideas are appreciated.

**Comment by otomplodomo** [comment]
I intend to utilize github's version control system to keep everyone up to date on the most current version of all the critical files related to summaries, captions, and transcripts. I will need help with this. It would be cool to let people correct captions from slack channels.

**Comment by patrick727** [comment]
@entropee no worries Gary, I did some brief summaries for the newsletter.

**Comment by lapin7** [comment]
@otomplodomo I think you made a lot of progress. I saw some nice things. Are they implemented now?

**Comment by entropee** [comment]
This github issue has enlarged to encompass more than just transcripts and summaries. It is now being referenced from the [Video Production Group domain on Mattermost.](https://chat.divvydao.net/video-team/channels/transcripts)

 I encourage anyone interested in finding interesting things that they can do which will contribute to the success of the RChain project to join us there. You can learn the Social Ledger, help us build a bounty system, and potentially earn bounties.

**Comment by dckc** [comment]
I just discoved this issue; is #79 a dup of this one? I did most of my work there.

Then there's #48, which is specific to one event. I prefer the style of #48... I'm inclined to reduce the scope of #79 to "hangout summaries thru October" and close it.

**Comment by patrick727** [comment]
@dckc yes we can go ahead and close this bad boy down and work through #48
