### ISSUE TITLE
F> 90 Day Marketing Budget

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#66]
Figure out a reasonable budget for Marketing related activities through the private sale.

**Comment by patrick727** [comment]
@lapin7 when you have the time, could you and Lisa and I go over some of the financial projects made throughout the end of the year in regards to Marketing, so I have a better idea when drafting up a proposal for co-op activist marketing activities such as web design, graphics, copywriting, editing, forum moderation, paid guest posting, etc.

**Comment by lapin7** [comment]
@patrick727 Iet's try to make a set up together. IMHO funds in RHOC are unlimited. We've only an approval problem. 
But maybe it works better with a detailed planning and budget forecast.

**Comment by patrick727** [comment]
@lapin7 I agree, and for the sake of cooperative accounting a detailed budget will benefit them. I was wondering if one had already been projected by Lisa and Greg, in terms of RHOC and/or Fiat? I can work with that.
