### ISSUE TITLE
M> Forum Engagement

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#68]
M> Indicates that this task is in the "Marketing" Category 

Goal:

We need a person, or a group of individuals to engage on forum channels such as slack, reddit, steemit,.. bitcointalk(albeit less). 

Jacob has been doing a great job of greeting new slack users, this is an example of the type of activities they would facilitate. 
More would be, 
- Reserving RChain profiles in forums, slacks, etc. 
 - Learning and engaging with new DApps(being some of the first users in there slacks). 
 - Newsjacking articles, reddit posts, steemit by commenting with well thought out positions
 - Posting content to forums(reddit, steemit, hacker news, lambda the ultimate, etc.) 
 - Curating knowledge base and reference sections
      - Clarifying language in regards to RHOC, REV, ICO's etc
 - Whatever else that you propose would be worth trying. 

This role could roll into a "Community Manager" type position, which will become more clear once the budget gets worked out, but we would like to start getting those channels covered asap.

**Comment by patrick727** [comment]
the assignees are kind of random for this but feel free to nominate someone for the role

**Comment by llerner** [comment]
We need to curate the comments a bit. There is mention in one of the channels about an ICO. It's key that we refer to this as a sale of assets or property. Anything else will get us in trouble.

**Comment by ervin-lemark** [comment]
Hello, friends.

Is there a list of names / handles which should be created / reserved for our current and future use? And a budget to fund the creation of these profiles if they have to be paid for.

At steemit, for example, rchain profile does not exist - yet: https://steemit.com/@rchain.

PS: yes, I volunteer for slack and bitcointalk coverage.
PS2: some guidelines for us as curators and commenters would be great :) 

Have a great day, everybody.

**Comment by patrick727** [comment]
@llerner agreed, we should get the messaging guidelines complete as fast as possible, do you have word from Ed, Evan and/or the Otto team on that?

@ervin-lemark as many handles as possible 
Bitcointalk - https://bitcointalk.org/index.php?topic=1747033.new#new
Twitter - https://twitter.com/rchain_coop
Github - https://github.com/rchain
Email - info@rchain.coop
Slack - ourchain.slack.com - slack.rchain.coop
Website - rchain.coop
Redemption Page - http://rchain.madeby8020.com/#!/
Youtube - https://www.youtube.com/channel/UCSS3jCffMiz574_q64Ukj_w
Medium - https://medium.com/@rchain_coop
Facebook - https://www.facebook.com/rchaincooperative/
Reddit - r/Rchain (unknown creator, probably synereo) we could get r/rchaincooperative r/rholang r/rchainofficial, etc
Google + - 
LinkedIn - https://www.linkedin.com/company-beta/24997313/
Vimeo -
Dropbox -
steemit - 
lambda-the-ultimate - 
daohub.org -

**Comment by patrick727** [comment]
also slacks lik coinfund, blockchain education network, the-etherian, etc

**Comment by llerner** [comment]
I’m going to track it donw. 



========================
Lawrence I Lerner
o/m: 630.248.0663
lawrencelerner@gmail.com

Blog: lawrenceilerner.com
 <http://www.lawrenceilerner.com/>twitter: RevInnovator <https://twitter.com/#!/RevInnovator> 



On Aug 9, 2017, at 06:17 , patrick727 <notifications@github.com> wrote:

@llerner <https://github.com/llerner> agreed, we should get the messaging guidelines complete as fast as possible, do you have word from Ed, Evan and/or the Otto team on that?

@ervin-lemark <https://github.com/ervin-lemark> as many handles as possible
Bitcointalk - https://bitcointalk.org/index.php?topic=1747033.new#new <https://bitcointalk.org/index.php?topic=1747033.new#new>
Twitter - https://twitter.com/rchain_coop <https://twitter.com/rchain_coop>
Github - https://github.com/rchain <https://github.com/rchain>
Email - info@rchain.coop <mailto:info@rchain.coop>
Slack - ourchain.slack.com - slack.rchain.coop
Website - rchain.coop
Redemption Page - http://rchain.madeby8020.com/#!/ <http://rchain.madeby8020.com/#!/>
Youtube - https://www.youtube.com/channel/UCSS3jCffMiz574_q64Ukj_w <https://www.youtube.com/channel/UCSS3jCffMiz574_q64Ukj_w>
Medium - https://medium.com/@rchain_coop <https://medium.com/@rchain_coop>
Facebook - https://www.facebook.com/rchaincooperative/ <https://www.facebook.com/rchaincooperative/>
Reddit - r/Rchain (unknown creator, probably synereo) we could get r/rchaincooperative r/rholang r/rchainofficial, etc
Google + -
LinkedIn - https://www.linkedin.com/company-beta/24997313/ <https://www.linkedin.com/company-beta/24997313/>
Vimeo -
Dropbox -
steemit -
lambda-the-ultimate -
daohub.org -

**Comment by ervin-lemark** [comment]
@patrick727
Great for the list of networks. We're moving forward :)

What about building the list of handles too?

Then we can correlate these two lists in a spreadsheet, check the handles that we should create and create them.

Also - passwords, private keys, urls...? We need something to keep this private and yet accessible to dedicated members. 

I don't want to create 20 steemit profiles and disappear and then you will chase me for the private keys :)
