### ISSUE TITLE
Whitepaper Outreach + Feedback

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#69]

**Comment by patrick727** [comment]
The whitepaper should be coming soon and we should get ready to blast it out to the community at large. 

Some helpful materials for this would be

- Email list of DApp developers(*contact ethercasts)
- Email list of syllabus 
- HARO - Crypto-currency writers can essentially right there verzion of "[intro to rchain](https://blog.coinfund.io/an-introduction-to-rchain-d5fe303e9fe1)" and provide feedback/link to article. 
- Thunderclap.it campaign, or other micro-influencer marketing tool
- AMA on subreddit, or Coinfund Q&A
- Auto-share workflow prepared for slackbot

- Physical prints(quality) for sharing at local blockchain meetups***

**Comment by patrick727** [comment]
The physical prints I like a lot. It may end up being a bit pricey, but I believe that it will be worth it.

**Comment by llerner** [comment]
Could someone send me a link to review before it gets wide distribution? 

Thanks

**Comment by patrick727** [comment]
@llerner that's up to Greg at this point. i'm sure he'd provide access if you want. What has happened in the past is that they just publish stuff with no warning besides the vague "coming soon" so preparing as much as possible is what this issue is for.

**Comment by kdvalentine** [comment]
@patrick727 I think it makes sense to share this with the blockchain community and have it 'peer reviewed'. It could be shared with blockchain projects that would benefit from building on RChain. Perhaps focus on the part of the infrastructure stack (IPFS, IPDB, Polkadot, IOTA, Zcash) that is state machine agnostic.

**Comment by patrick727** [comment]
@kdvalentine it does, so we can pay to have feedback through 21.co, I can reach out to ethercasts to see if they are willing to do an email to there dev email list. do you have an email list built, or know of one available in order to get this to quality eyes

**Comment by lapin7** [comment]
@llerner Could you please register as Activist through form [Activist Registration](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform)

You could then be also assigned to this issue and receive RHOC for your TIME participation.

Thx
