### ISSUE TITLE
Google Group Setup

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#7]
Setup a mailing list through

http://groups.google.com/group/rchain

**Comment by jimscarver** [comment]
I added the group, added HJ and Planteater as owners. Any setup needed before we announce the group?

**Comment by lapin7** [comment]
Great, And the epic is moving in the project board.
I suggest to use this form to add members to the google group. Members can fill out with as much personal data as they want. Some items are mandatory: email, github, slack, name, address, gps

https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform

**Comment by lapin7** [comment]
It's now under the Top epic Onboarding .....

**Comment by dckc** [comment]
This is done to my satisfaction.

If there is more to do, let us know and re-open it.
