### ISSUE TITLE
M> Blockchain meetup group Schedule + Materials

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#70]
M> Indicates that this is a project within the "Marketing" category

Goal:

Let's map every available meetup group related to Ethereum, Bitcoin and blockchain within major metropolitan cities(or just an active group) across the US. Then we can coordinate with the groups for events, presentations, etc. 

Here is a list of delieverables that I would like to see in order to make sure that RChain is professionally represented at these meetups. 

1. Standardized Pitch Deck so that: see this as an example (https://drive.google.com/file/d/0B89Hsy8OYAnUN1h5STJha2kzbms/view)

2. Printed handouts (1 Pager, Whitepaper, Arch Document): Budget = 100-200USD for spiral bound print outs with RChain logo. see (http://www.fedex.com/us/office/manual-printing.html)

3. Business cards. see Ether.cards for RHOC loadable cards - cost = 284.22 GBP + P&P for 15 working day lead time

4. Recording equipment = by approval only. 

5. live support = zoom room with leaders for Q&A portion = by approval only

**Comment by kdvalentine** [comment]
**New York City Metro Area Meetups**

[RChain: Blockchain 3.0](https://www.meetup.com/RChain-Blockchain-3-0-Intro-Meetup/)

[NYC Ethereum](https://www.meetup.com/NYC_Ethereum/)

[Blockchain For Social Good](https://www.meetup.com/Blockchain-for-Social-Good/)

[BitDevs NYC](https://www.meetup.com/BitDevsNYC/)

[Cosmos NYC](https://www.meetup.com/Cosmos-NYC/)

[Hyperledger NYC](https://www.meetup.com/Hyperledger-NYC/)

[Blockchain NYC!](https://www.meetup.com/Blockchain-NYC-Start-Up-Tech-Events/)

[฿itcoinNYC](https://www.meetup.com/BitcoinNYC/)

[Bitcoin Center NYC](https://www.meetup.com/BitcoinCenterNYC/)

[Blockmatics](https://www.meetup.com/Blockmatics/)

[New York IOTA + Tangle Meetup](https://www.meetup.com/New-York-IOTA-Tangle-Meetup/)

[Women in Blockchain](https://www.meetup.com/meetup-group-mQkKWfuU/)

[Brooklyn Futurist Meetup](https://www.meetup.com/BLKNY30/events/240580804/)

**Comment by patrick727** [comment]
Nice work @kdvalentine! Will throw that on a calendar when I get the chance, been a bit swamped lately. 

What do you think would be a good package for 

1. Being an ambassador at an existing meetup
2. Hosting an RChain specific meetup?

**Comment by patrick727** [comment]
Here is a draft proposal for local meetups. 
https://docs.google.com/document/d/1V8mMfYBS9ubXpm5gz18dmLGSyxS-Xmih5Jmb9SByQ-s/edit?ts=59cab4d2

**Comment by patrick727** [comment]
This is a search for all blockchain meetups groups

https://www.meetup.com/find/?allMeetups=false&keywords=blockchain&radius=Infinity&userFreeform=united+states&gcResults=United+States%3AUS%3Anull%3Anull%3Anull%3Anull%3Anull%3A37.09024%3A-95.71289100000001&change=yes&sort=recommended&eventFilter=mysugg

**Comment by pythonical** [comment]
@patrick727 Access to the draft?

**Comment by pythonical** [comment]
it looks like there are 2 'main' blockchain groups in my area. one Ethereum focused and the other generic. a dedicated rchain group would be awesome.

**Comment by patrick727** [comment]
@pythonical where are you located? 

Do you think that there are enough interested devs to warrant a dedicated RChain group, or maybe is that participation in the ethereum/blockchain groups may work best?

**Comment by pythonical** [comment]
@patrick727 i think i will have to see about playing 'Paul' and spreading the good news to see who is interested. it's Austin so i imagine there are many who might be (or already are i just don't know about them)

**Comment by djrtwo** [comment]
I run the ethereum meetup and ethereum dev meetup in New Orleans. I'm not
certain we have enough demand for another meetup in town, but I'm
interested in informing them about rchain. I'd also be interested in
hosting a one off talk or series about rchain if we think that'd be a
valuable format.

Lisk is pushing hard and doing new sponsored "blockchain" Meetups in a
bunch of cities. The meetups are on blockchain topics in general but always
have a sponsor (lisk) update at the beginning. Might be an interesting
model to pursue either now or when mercury drops.

**Comment by patrick727** [comment]
Here is the calendar that I will be filling in with all related RChain speaking engagements. 
https://calendar.google.com/calendar?cid=cmFyZnVuZzRndnE2c3A2NWY3Y2JvbmpzbzhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by llerner** [comment]
The link is taking me somewhere else. My own calendar. @MParlikar also has a speaking calendar. Can we consolidate? I have four events that I will be speaking at in January and the rest of the year is filling up. I'll add ASAP.

I want to give away RHOC cards at each to help make our brand message sticky.

**Comment by patrick727** [comment]
yes lets definitely do that. please link to me the calendar that you want it all consolidated under

**Comment by llerner** [comment]
https://docs.google.com/spreadsheets/d/1WCwsVoV02wqvgDzPYBn2BVLPsen_tKl7IdMpxTVH7Ls/edit#gid=0

Let’s please reduce to one place where we keep all of our events. @MParlikar Can you give @patrick727 access and close down this second one? Thanks

**Comment by MParlikar** [comment]
I think I need more clarity, which sheet is redundant and which to keep.
Both links are taking me to the same sheet.  Confused.

On Fri, Dec 29, 2017 at 7:33 AM, Lawrence I Lerner <notifications@github.com

**Comment by patrick727** [comment]
@llerner, @MParlikar I thought that timeline link was being used for different purpose(internal coordination) I was intending to have a public calendar in which members can view all of the events in a given time that they may engage with.
