### ISSUE TITLE
M> Influencer marketing program setup

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#72]
M> Indicates that this task is in the "Marketing" Category 

Goal:

We want to tap into our network as effectively as possible, Nathan will be providing access to a micro-influencer software(don't remember the name but will) in which we can better manage relations we have with community members that can boost our visibility. 

We can start by listing out current and potential influencers that we can start to solidify relationships with as we progress our go-to-market plan.

**Comment by jbassiri** [comment]
List influencers and track outreach (avoid duplicate outreach) via the "Ecosystem" Sheet: 
https://docs.google.com/spreadsheets/d/1nYq9eHUGNr-N9n7WwfmssDPePU4O3J-tY9N2IeVe6DM/edit#gid=1565346490
