### ISSUE TITLE
DApp ideas & partnerships

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#74]
This is a fun one. In anticipation for the hackathon, lets start listing out potential DApp ideas, feature sets, problem/market fits that we think RChain can capitalize on. 

This thought exercise could end up to be very valuable for all that participate.

**Comment by jbassiri** [comment]
#72, #74, #75, #76, #91 are duplicative. Are we opening issues and getting nothing done? 
BD/developers/events/bus. plans/ etc. should be tracked in one sheet. It lowers coordination costs and friction... Again, the "Ecosystem" Sheet: 
https://docs.google.com/spreadsheets/d/1nYq9eHUGNr-N9n7WwfmssDPePU4O3J-tY9N2IeVe6DM/edit#gid=1565346490

**Comment by patrick727** [comment]
@jbassiri the only real duplicate there is 91 from 76, which was what you created in order to introduce your sheet and maybe be more specific towards devs. I noticed you changed the comment to "narrowly defined" yes we want to get more specific and track all in the appropriate place. 

How to track: 

#72 - Nathan has software to track and engage with micro-infleuncers, working on getting that and setting it up. Feel free to list out yours in your spreadsheet and then we can copy it over at the right time. 

#74 & #75 are meant to start conversations, if you want to drive those conversations then do so. If nobody is commenting on the issues then that means nobody has DApp or Community ideas worth sharing and/or being rewarded around. I assume that campaigns leading up to hackathon will inspired better engagement and may end up closing these issues. 

#76 - this can be tracked in your sheet if you like, but would prefer the micro-influencer software when @nathanwindsor gives it to me. 

"are we opening issues and getting nothing done?" That style of communication bothers me.

**Comment by JediJuice** [comment]
I am late to the party, so are we commenting on the Dapps here or which number?

1. I did startup weekend in Boston in 2013, the theme was sensors. We might be able to do a co-branded thing like " Startup Weekend - BlockChain with Rchain " ? Off the top of my head I do not see a downside for their brand, so maybe they might go for it? Also, TechStars has no blockchain partners that I am aware off and this will change shortly!
2. Sramana Mitra runs a virtual incubator and we could partner with her to get devs working or maybe fork her business model with a YouTube show? I know she does co-branding and sponsorships. 
3. I might be able to fire up my failed start-up called HaveOneOn.Me (site is down) and pass it off to some hot shot MBA's looking for an idea? (https://twitter.com/haveoneon)
