### ISSUE TITLE
Outreach - Team Building

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#76]
Anyone in mind for specific positions for RChain Cooperative or Holdings Company? 

Let us know and we can reach out to the candidate or provide you with guidance where it fits. 

Looking for talented and passionate individuals in various roles.

**Comment by jbassiri** [comment]
I send out business/investor/developer/influencer development emails. I've sent out ~15 let's say.

I will post here only ones I hope to get reimbursement for my time and energy. I only feel it is fair to do so IF it leads to a unique successful outcome, such as a phone call. Here is the first such case:

1. David Mazieres (Stanford professor) discovery, email outreach, and phone call with Nash Foster discussing a wide range of technical, business, and philosophical blockchain and RChain related issues. Next step is a follow up call with Greg Meredith and Mike Stay to go even deeper. 

More on David Mazieres: 
http://www.scs.stanford.edu/~dm/
Founder of [Stellar.org](https://www.stellar.org/)

Potential outcomes: 
RChain platform brainstorming & feedback; Stellar.org collaborations; Stanford research/development collaboration; influencer support from David M.

Activities: 
Discovering potential influencers
Email back and forths
Phone call with Nash F and David M: 1 hour and 22 min

**Comment by patrick727** [comment]
yeah, i'd suggest we could pay per lead on this. Lead = call with leadership team. 
I suggested a total budget for this issues experimentation https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=1970624799 

might be best to break this up or specify PPL, @lapin7 put $50 or 500 RHOC as the budget maybe that could be the basis for a lead?

**Comment by jbassiri** [comment]
@lapin7 has created a new issue #91 Acquisition of Developers that more directly addresses this issue. I will continue the thread over there.
