### ISSUE TITLE
M> Wikipedia Pages

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#77]
[Wikipedia Draft Google Doc](https://docs.google.com/document/d/1t6mYKmobHnY0KBsedy75Nt-UJBkf7uU-bFEdHZTg2_I/edit?ts=5988d045)

Jacob Bassiri has begun a wikipedia draft for Rchain, 

Please contribute to the editing process by suggesting within this document. 

Thank you

**Comment by kdvalentine** [comment]
Should a Rho-Calculus have it's own wiki as well? Content could be derived from the various papers already written.

**Comment by patrick727** [comment]
@kdvalentine yes that's a good idea! and so should rholang

**Comment by patrick727** [comment]
@jbassiri any news on the wikipedia submission?

**Comment by jbassiri** [comment]
Not yet! It's been a little over 3 weeks so expecting something soon.

**Comment by patrick727** [comment]
OK thank you!

**Comment by dckc** [comment]
The only source in that draft looks like a self-cite. It doesn't look appropriate for Wikipeidia. cf. https://en.wikipedia.org/wiki/Wikipedia:No_original_research

What are some good 3rd party sources? i.e. other people writing about rchain?

**Comment by patrick727** [comment]
Everything in the reference: 
https://github.com/rchain/reference 

n-category cafe posts:
 https://www.cs.auckland.ac.nz/~msta039/ 

Articles:

https://www.geekwire.com/2017/seattle-based-rchain-takes-bitcoin-ethereum-new-blockchain-tech

https://blog.coinfund.io/rchain-series-introduction-985a05804ab

**Comment by dckc** [comment]
Everything in the reference is original research, no? msta039 likewise.

The geekwire piece looks appropriate.

The coinfund article is borderline; it bears "Disclosure: The author of this article received compensation from RChain ..."

**Comment by dckc** [comment]
I'm not aware of a wikipedia submission process that takes 3 weeks. Edits are instantaneous, no? Somebody clue me in?

p.s. the fact that this issue is tagged Marketing suggests pretty strongly that this whole effort goes against https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest . You're not supposed to write about your own work.
