### ISSUE TITLE
M> github.com/rchain/reference restructuring 

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#80]
M> Indicates that this task is in the "Marketing" Category 

Goal:

Our Github references has been a go to link for some time now, i'd like to get it updated and structured some more with all the new information that we have and how we'd like to present it. this task shouldnt take much time but will require edit access to the reference page.

**Comment by kitblake** [comment]
Just updated the Slack Etiquette doc with some minor fixes. It's in /reference but not yet listed in README.md), @patrick727 I assume you'll fix that with your renovation.

**Comment by patrick727** [comment]
@kitblake great stuff!

Ill need the proper access in order to renovate the docs but can get that soon

cheers!

**Comment by dckc** [comment]
I'm intersted to contribute to this; I'm new around here, and fresh eyes can help with this sort of thing.

I would appreciate a refinement of the issue title that tells what the goal is in a way that we can judge whether it's finished. The documentation can always be restructured.

**Comment by patrick727** [comment]
Hey @dckc Dan, thanks for showing your interest and I edited the title to be more specific. 

The goal quite literally is to make the restructure the /reference github in such a way to reflect all of the new information RChain has, in a digestable manner. 

So right now its: 

Platform:
Talks: 
Co-op: 

maybe we can make it more detailed such as : 

Research: 
Platform: 
Co-op:
Community: 

and then itemize all of the information within something like that. 

what do you think?

**Comment by dckc** [comment]
Ah... so the scope here is /reference. As I was trying to get myself oriented, that was one of the more useful pages. While I'm sure it can be improved, it's not clear to me that it's broken in any critical way.

As to that particular outline... I doubt Research should go first. After the architecture document and the FAQ, the weekly community update is perhaps the main thing to know about. And for a new person, the prospect of watching some 40 of them to get up to speed is overwhelming. The "missing link" was the index of topics in the newsletter. Once I found that, I could make informed choices about which parts to watch and I could tell which ones I had already watched. That's why I have invested in https://github.com/rchain/Members/wiki/Weekly-Update-Index

**Comment by kitblake** [comment]
> As I was trying to get myself oriented... And for a new person...

@dckc, this is illuminating feedback. Please continue to post your impressions - especially the bad ones – as you explore. We know the onboarding experience needs to be much smoother. In terms of larger goals, that's what a lot of us are focusing on. The comments you're making are like light in the forest.

**Comment by lapin7** [comment]
This week I want to invite Activist, that have gone through the
PRE-membership registration and paid a fee of $20, to become a Member and
get access to Discord.
In issue #93
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fissues%2F93&si=5281391242641408&pi=1fdc5a0b-e142-4338-8a08-eafa1573b1cc>
you will find more details.

A personalised email will be send. The content is drafted in Gdrive:
RChain/Members/Identification/Template Activist to Member
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F16szs0_Obml8x6gm3MO1fas8S4p1V7pbweiMeqjq2L6Q%2Fedit&si=5281391242641408&pi=1fdc5a0b-e142-4338-8a08-eafa1573b1cc>

Please help to get a nice email.

--
Cheers,
HJ

**Comment by patrick727** [comment]
@dckc @kitblake yes this is not the most critical of tasks, hence "should not take much time"

That feedback is great thankyou. So how about lets comment are proposed new /reference that includes the weekly update. Something that someone with proper access can just copy and paste over
