### ISSUE TITLE
M> RChain User Persona and Journeys

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#81]
M> Indicates that this task is in the "Marketing" Category 

Goal:

As detailed as possible for 

Developers

Architecture
 - older dev with years in distributed systems (Greg)
 - newer devs who will only know decentralized tech (Kent, Joe)
 - mathematicians looking to apply to computer science(LADL)

Rholang
 - newer dev who doesn't know solidity
 - newer dev who is currently learning solidity
 - experienced dev who is learning about smart contracts

Casper
 - Miners who are currently participating in PoW and not PoS
 - Miners who are currently participating in PoW and PoS
 - Developers who are building prototype PoS (tendermint)
 - Dev who is interested in exploring Casper specifically

as many as we can think of and as detailed as we can think of. 

Investors
 - Experienced traditional VC's new to crypto
 - Inexperienced accredited investors new to crypto
 - Experienced traditional VC's familiar with crypto
 - Inexperienced accredited investors familiar with crypto
 - Enthusiasts who trade on exchanges. 

http://optinmonster.com/how-to-create-a-concrete-buyer-persona-with-templates-examples/ 

If/when we do create these docs, i'd prefer they are not made public, so we will need to establish private channels

**Comment by patrick727** [comment]
These are the new persona examples that we will need to fill out entirely

Developer 
   Blockchain Architect
   Blockchain Sr. Developer
   Blockchain Jr. Developer

Educators  
  Mathematics
  Economics
  Governance 3.0
  Business Applications
  Educational Institutions

Entrepenuer  
  Successful - Blockchain Exp.
  Successful - Blockchain Noob
  Newer - Blockchain Exp.
Enterprise 
  Modernization
  Incubation
  - Kicking the tires
  - FOMO (Fear of Missing Out)
Investors  
  Angels
  ICO lovers(Crypto-enthusiasts)
  Institutional
  Private Equity
  Venture Capital
  Government Funds

**Comment by dckc** [comment]
I have been searching for user stories, so I'm interested to contribute to this; [StoryTellingAndTestCases](https://informatics.gpcnetwork.org/trac/Project/wiki/StoryTellingAndTestCases) is my preferred way to organize software development.

That's quite a long list of personas to fully flesh out; I expect we'll want to split this ticket into some more manageable targets. But we'll see.

Any suggestions on where to start? I can try to mine existing documents for user stories. Or I could interview somebody. If anybody has a bullet list of two to five stories they **know** are important, I could start there.

**Comment by patrick727** [comment]
@dckc  great stuff again! I typically just fill them out into a spreadsheet or doc based on a template like this one https://blog.hubspot.com/marketing/buyer-persona-examples feel free to use whatever format suits you. 

So long as we get a basic idea of

demographic 
roles
goals
challenges
story 

yes, this is a big list, you can start with an interview if you so choose, also tune into hangouts to get ideas of why people are attracted. Anytime there is a new person the guys tend to greet them and ask them why they are here. 

if you want to start with the developer stories that would be awesome, mike stay and nash foster of pyrofex handle the hiring and may be willing to help you flesh out the persona and story for that as it would help them out too.

**Comment by dckc** [comment]
Oh. That template is for personas / roles, which is a pre-requisite to what I had in mind: an [User Stories in Extreme Programming](http://www.extremeprogramming.org/rules/userstories.html). So they're related, but not the same. Now I can see why your list looks like it does. I'll have to mull it over some more.
