### ISSUE TITLE
M> Proposal: Support Projects in "Kickstarter" Fashion

### ISSUE THREAD

**Issue by drbloom** [rchain/Members#83]
How about hacking a kickstarter-like tool, allowing us to support each-others projects with RHOC?

RHOC will be exchangeable for utility on the coming RChain Platform. The Coop can support RChain Projects by distributing RHOC to members, who in turn **send those RHOC to the projects they support**. Many of these projects will rely on RHOC to fuel the bandwidth, compute, and storage needs of the apps they are developing.

[Jake Gillberg](https://ourchain.slack.com/team/jake_gillberg) demonstrated a web3/metamask Chrome Extension that enables us to use RHOC to [vote on GitHub](https://github.com/Jake-Gillberg/git-vote) issues. Could the same hack be done to a project management platform, enabling RHOC to be transferred?

**Comment by kitblake** [comment]
At the moment it seems like most holders of RHOCs are hodlers (myself included). This doesn't bode well for liquidity in the market. The Co-op is also not distributing RHOCs. A few thousand have gone out as bounties but – if you 'do the math' – after a few months it'll still be a few thousand. Being hodled. 

"...distributing RHOC to members..." with the intention that they put them into play is a great idea.

**Comment by lapin7** [comment]
I would be ready to trade a bit more.
Get the RHOC's rolling. When we pay out more RHOC to activists, there will
be more people interested in liquidating those RHOC's.
IMHO the first community driven pay-outs of 100,000 RHOC will be just the
start. Let's spend it quickly. Show the results to the board and ask for
more.

Jake's system looks to me a great tool. It's excellent for cleaning up the
issues in GitHub. And I think that GitHub is good enough for our project
management.

--
Cheers,
HJ

**Comment by traviagio** [comment]
Just added Jeroen van Dijk in the spreadsheet. Will be looking for more
