### ISSUE TITLE
Newsletter Drafting - September 2nd

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#86]
The last newsletter just went out linked here: http://archive.sendpulse.com/shc4c/b25789bf/?_ga=2.241582279.432853737.1503506489-455718163.1494599085

Some stats to date: Open Rate = 27.12%, 1 Unsubscribe, Most Clicked link = series introduction. 

special thanks to @kitblake who is really becoming a rhoc in the activist community, and a newer face @jbassiri on slack. of course @plantether, @jimscarver for their continual contributions.

Here is the link to the next drafting document for September 2nd looking forward to keeping this thing rolling.

https://docs.google.com/document/d/1sW_E5HAi5jf3XEfLhah7e5UuHY8x0_KPvmN0-c6r024/edit#heading=h.lflfpanhqvmj

Cheers

**Comment by kitblake** [comment]
@patrick727, I made some minor fixes in suggestion mode in the Gdoc. You can probably manually fix them in the newsletter, e.g. the paragraph about Kenny Rowe has a split sentence.

The yellow "Purchase RHOCs" button block is kinda ugly with that brownish background. Would be good if you can match the background-color of the sale site: #222e2e.
