### ISSUE TITLE
RChain Dictionary

### ISSUE THREAD

**Issue by patrick727** [rchain/Members#88]
[Google Document - RChain Nomenclature ](https://docs.google.com/document/d/1AOApb9Up_rZ10eb08lpj8nI4k96-DIyX32XFR2SEnQg/edit) we'd like to get a markdown page with RChain vocabulary and links that we can refer to with the messaging. 

Cheers

**Comment by patrick727** [comment]
@kitblake if you could drive this it would be great. what we need is a github page in markdown, for the RChain vocabulary including a definition and linking documents.

**Comment by kitblake** [comment]
Sure, I can pick this up. Doing it like the FAQ in Github means everybody can edit. Maybe we'll keep it in /Activists as opposed to moving it to /reference where we don't have checkin rights. 

This could also become a slash command bot in Slack. So when a noob writes, "WTF is a phlogiston?" then someone types:
```/dict phlogiston```
Which makes the Def Bot come up with a definition. What do you think @entropee?

**Comment by patrick727** [comment]
thanks, yes it should eventually get published to a place that is only open to pull requests. and the integration with definition-bot would be a great move. 

Thanks a bunch guys!

**Comment by Jake-Gillberg** [comment]
+1 to a place only open to pull requests

**Comment by lapin7** [comment]
Please set a budget for #86 in [RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=1970624799)

**Comment by kitblake** [comment]
Made a start, @patrick727. 
• I think some of the section headings will also need to be definitions. 
• Not sure about grouping of the techy terms, someone will have to check/adjust.
Contributions welcome :) I think it would be cool if the definitions were largely our content – in the context of RChain – as opposed to quoted defs from external sources. But those can be a seed.

**Comment by entropee** [comment]
This is great! I am looking at in now. I think the section called Pi-Calculus might better be called Formal Methods. Also, Lambda Calculus should be in this section. The definitions in this section need to be artfully crafted so they paint the picture that a dev needs to be able to understand RChain. I want to play with these for a bit.

**Comment by dckc** [comment]
I encourage the development of a [pattern language](http://wiki.c2.com/?PatternLanguage) in [the wiki](https://github.com/rchain/Members/wiki) rather than a dictionary / glossary such as this.

This is based on my experience trying to do an [index of terms in Web Architecture](https://www.w3.org/Architecture/Terms.html) over a number of years vs. [a trac wiki for an informatics team](https://informatics.kumc.edu/work/wiki/HERON) for the last few years.

**Comment by patrick727** [comment]
@dckc sorry I don't really understand your point. 

Maybe you can work on a wiki and demonstrate the superiority of this pivot.  

If you can make the dictionary obsolete, then so be it. 

I like the idea of the simple dictionary, especially as we create new language , acronyms etc to be used in later content.

**Comment by lapin7** [comment]
This issue has a bit of budget allocated to it, is this enough?
And no rewards have been distributed yet. Although the issue has already several participants and assignees. 
Please go ahead and use form [Budget allocation and - spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform) to fill it out 👍 before the end of the month.

The sheet [Pub Activist Budget Allocation-Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1168839067) is constantly updated.

**Budget Allocation**

Link | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/88 | New | RChain Dictionary | Marketing | 3 | $ - | $ - | $ 800.00 | kitblake patrick727 lapin7

**Budget Spending**

Github Issues | URL | Description | Category | Set | Set | ⍴ Budget | ⍴ To Pay | Activist | AVG work | Votes | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
88 | https://github.com/rchain/Members/issues/88 | RChain Dictionary | Marketing | 3 | New | ⍴ 8,000 | ⍴ - | kitblake | 0% | 0 |  
88 | https://github.com/rchain/Members/issues/88 | RChain Dictionary | Marketing | 3 | New | ⍴ 8,000 | ⍴ - | drbloom | 0% | 0 |  
88 | https://github.com/rchain/Members/issues/88 | RChain Dictionary | Marketing | 3 | New | ⍴ 8,000 | ⍴ - | kdvalentine | 0% | 0 |  
88 | https://github.com/rchain/Members/issues/88 | RChain Dictionary | Marketing | 3 | New | ⍴ 8,000 | ⍴ - | plantether | 0% | 0 |  
88 | https://github.com/rchain/Members/issues/88 | RChain Dictionary | Marketing | 3 | New | ⍴ 8,000 | ⍴ - | patrick727 | 0% | 0 |

**Comment by plantether** [comment]
@dckc I don't understand either. Could you ELIF for us, please?

**Comment by dckc** [comment]
No, I can't think of a simple way to convey several years of experience. And maybe this context is different.

But I'm curious: what's the intended audience of the document? What situations are likely to cause someone to read / consult it? What are triggers to maintain / update it?

**Comment by kitblake** [comment]
The dictionary/nomenclature is meant for clarifying RChain-specific jargon for people who are not indoctrinated insiders. While many of the words listed, like "Tuple Space", are generic concepts the intention is to flesh out the definitions with RChain context. Other words, like "RhoVM", will be RChain-only.

Since they're Github headings the words are URL-addressable. If someone asks "What's that LADL acronym?" they can be pointed to:
https://github.com/rchain/Members/blob/master/projects/dictionary.md#ladl

The doc can also can function like a FAQ when someone ends up perusing it. Another idea that's been floated is a forum bot that can retrieve a definition on demand.

Maintenance will need to be a proactive effort where people note noob confusion and, like the "Scan Discord for issues" issue, make a note of it.

**Comment by dckc** [comment]
FYI, I just ran across another pattern language via lobste.rs: https://martinfowler.com/eaaCatalog/

**Comment by patrick727** [comment]
@dckc I get it now, based on that example. Thanks for that. 

That would require a catalog of pages for each word and definition. 

Is this doable in github? 

I like the simplicity of the dictionary so far. 

Audience would be 1. a bot to pull definitions from. 2. an RChain researcher that wants to become accustom to the nomenclature and how it is used within the documentation.

**Comment by dckc** [comment]
I can see the chat bot scenario working well. (In fact, I have seen it work well...) The bots I have seen use some sort of database that isn't published as a web page, but using a page in git as the db makes as much sense as anything else.

But for researchers, I'm less confident; for them (i.e. us; I count myself as an occasional researcher), seeing the terms used in context is essential, with each term defined in terms of already defined terms. Articles, specs, slides, and presentation recordings are the way to go for that audience. If you want to help us find stuff, traditional title / author / date / publication venue citations work pretty well; bonus points for abstracts.

**Comment by kitblake** [comment]
@dckc, I'm trying to find that IndieWeb bot.. is it in their Slack? 

```<off-topic>```
They have all the channels bridged:
"Join the #indieweb discussions via the web, IRC, Matrix or Slack!"
```</off-topic>```

**Comment by dckc** [comment]
@kitblake I don't know. But they're very friendly and responsive. Head over and ask!

**Comment by dckc** [comment]
oh... and actually, I think that indieweb bot does publish its DB on the web - in their wiki.

**Comment by kitblake** [comment]
I inquired. The DB is the wiki itself: https://indieweb.org/User:Loqi.me
Storage questions aside, it's a nice bot that does a lot of stuff. 
Also it's working in all their chat channels, because all their channels are bridged, including irc, Slack, Matrix, riot.im.

**Comment by entropee** [comment]
[Agent] - In computer science, a software agent is a computer program that acts for a user or other program in a relationship of agency, which derives from the Latin - agere (to do): an agreement to act on one's behalf. Such "action on behalf of" implies the authority to decide which, if any, action is appropriate.

[Agent-based model](https://en.wikipedia.org/wiki/Agent-based_model) - Agent-based model, a computational model for simulating the actions and interactions of individuals

[Bisimilarity](https://en.wikipedia.org/wiki/Bisimulation) - In theoretical computer science a bisimulation is a binary relation between state transition systems, associating systems that behave in the same way in the sense that one system simulates the other and vice versa. Intuitively two systems are bisimilar if they match each other's moves. In this sense, each of the systems cannot be distinguished from the other by an observer.

[Bot](https://en.wikipedia.org/wiki/Internet_bot) - An Internet bot, also known as web robot, WWW robot or simply bot, is a software application that runs automated tasks (scripts) over the Internet. Typically, bots perform tasks that are both simple and structurally repetitive, at a much higher rate than would be possible for a human alone.

[Chatbot](https://en.wikipedia.org/wiki/Chatbot) (also known as a talkbot, chatterbot, Bot, IM bot, interactive agent, or Artificial Conversational Entity) is a computer program which conducts a conversation via auditory or textual methods.[

[cyborg](https://en.wikipedia.org/wiki/Cyborg) (short for "cybernetic organism") is a being with both organic and biomechatronic body part. Cyborg from "cybernetic organsim". Cybernetic from the greek kybernetes which means steersman, governor, pilot, or rudder.

RChain

RChain Platform 

RChain Blockchain

The RChain Cooperative

The RChain Holdings Company

Process Algebra - An algebra is a mathematical structure with a set of values and a set of operations on the values. These operations enjoy algebraic properties such as commutativity, associativity, idempotency, and distributivity. In a typical process algebra, processes are values and parallel composition is defined to be a commutative and associative operation on processes.

Process Calculi

Mobile Process Calculi


Lambda Calculus - Lambda calculus (also written as λ-calculus) is a formal system in mathematical logic for expressing computation based on function abstraction and application using variable binding and substitution.

Pi Calculus

Rho Calculus

Rho API

Language Bindings

[Formal Methods](https://en.wikipedia.org/wiki/Formal_methods) - In computer science, specifically software engineering and hardware engineering, formal methods are a particular kind of mathematically based techniques for the specification, development and verification of software and hardware systems.

Rho-Calculus

Reflection

Behavioural Types 

LADL

Rholang
 
Actors, Tuples, and Pi

Rosette 

Tuple-Space

RhoVM

Concurrency

	Concurrency vs Parallelism

Staking Tokens



Namespace Logic

	Composable Namespaces

Application Tokens

Milestones: 

Compiler Complete
Node Complete
Mercury Complete

**Comment by kitblake** [comment]
A link to the Dictionary draft has been posted in the comm channels. Any inputs?
https://github.com/rchain/Members/blob/master/projects/dictionary.md

**Comment by dckc** [comment]
I saw this interaction in discourse chat (I presume it's OK to share). This would have been a perfect time to use a chat bot:

> sportshark: what is the meaning of  Rchain, "chain" means blockchain,but what about "R"?
>
> jbassiri: Reflective higher order calculus, rho calculus, is a variant of pi calculus. They fall into the category of mobile process calculi, a framework for analyzing concurrent processes that communicate like biological cells or different namespaces (identities) on a blockchain (blockweb)

The answer given isn't very close to the one in dictionary.md, though the one in dictionary.md does match [the official FAQ](https://github.com/rchain/reference/blob/master/faq.md).

I like the bit about biological cells.

As a small investment in the wiki-powered chat bot approach, I just made https://github.com/rchain/Members/wiki/RChain

**Comment by dckc** [comment]
Maybe #63 is more relevant to the chat bot approach...

**Comment by dckc** [comment]
What does the "MatterMost Migration" tag mean?

Is the MatterMost stuff publicly available? I much prefer to collaborate in public.

**Comment by patrick727** [comment]
@dckc thanks great job, yes building out a wiki is one the to-do list, integrating the discord chatbot would be really cool.

**Comment by entropee** [comment]
@dckc MatterMost migration was a tag that I put on quite a few issues to remind me which need to be addressed by the RChain MM team. Yes, everything on MM is open. Except for things like tags and links, I see MM as a supplement to github rather than a replacement. We can remove the tags if they are confusing. BTW, I'm all in with your pattern language idea. I'm reading up on it now.

**Comment by dckc** [comment]
MM stuff is open? Do you have an example of a URL I can access without logging in? I looked around buy could not find any.

**Comment by kitblake** [comment]
The MMs in the Mattermost Social Ledger trial (#108) and RChain MM working group (#113) are not open to the world. Could be others are.

**Comment by kitblake** [comment]
That was an inspired answer @jbassiri. You changed the definition of RChain! I like the biological cell metaphor too.

Now that @dckc put his edit in a wiki page, someone could implement a bot that'll search for wiki pages where the page title matches the term to be defined (see the existing example from IndieWeb pioneers in the [above message](https://github.com/rchain/Members/issues/88#issuecomment-330625080)). 

This also means we have a content feedback loop. The RChain definition in the wiki is now in [dictionary.md](https://github.com/rchain/Members/blob/master/projects/dictionary.md). Contributors can edit in whatever environment – or markup language – they choose.
