### ISSUE TITLE
Translate medium post to chinese

### ISSUE THREAD

**Issue by Lizen0512** [rchain/Members#882]
### Benefit to RChain

- [x] [RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a) 1970 words
- [x] [RChain update (Debrief 88), 1st August, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-88-1st-august-2018-8058f8f94527) 1855 words

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[765]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [ ] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #761, #828, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by v56700** [comment]
They have been translated, please check
http://www.rchain.site/?p=745
http://www.rchain.site/?p=757

**Comment by yuhuanmocmoc** [comment]
@v56700 they are just Google translations, please be serious.

**Comment by v56700** [comment]
@yuhuanmocmoc  You can find a professional translation team to review, or ask the Chinese community for advice.

**Comment by yuhuanmocmoc** [comment]
@v56700 please  remember that the review work is for checking your spelling, grammar, specific-term and so on, but the article you translated doesn't make sense at all!

**Comment by v56700** [comment]
The Chinese community wants to see timely news, not outdated news.
The old news on July 25th needs to be translated now?

**Comment by v56700** [comment]
I use machine translation + post editing
I don't think there is any problem with this translation. I don't need a cooperative to provide a budget, and I have done a good job.

**Comment by v56700** [comment]
Do you have a certificate from a professional institution?

**Comment by Ojimadu** [comment]
@will You recently joined the translation guide can have a look here?

**Comment by yyh1102** [comment]
@rjl493456442  is the member of Ethereum Go team, and he definitely has a super professional knowledge and experience of blockchain. @v56700

**Comment by v56700** [comment]
Please note that we are talking about whether budget should be paid for outdated and repetitive work.
