### ISSUE TITLE
Social Ledger Prototype Demo and Trial

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#89]
the social ledger mattermost slack alternative integration we are building in diglife facilitates organic growth of the organization while fostering cooperation and coordination. RChain will be more or less participating in the trial and demo of the social ledger.https://docs.google.com/document/d/1v7JaVwJUhWix52y7piNqlpAYiVCtNhim2I0KvJyE16M/edit#heading=h.9elnran28cug

Sponsored RHOC bounties are available for help facilitating the trial.

**Comment by lapin7** [comment]
Please set a budget for #89 in [RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=1970624799)

**Comment by patrick727** [comment]
@jimscarver  i believe that this is a duplicate issue
