### ISSUE TITLE
Which platform to use for finance/bookkeeping/email

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#9]
Currently @edeykholt is using [Intuit](https://qbo.intuit.com/) for finance/bookkeeping. 
Rchain is also using ZoHo freeplan for Rchain-roles email addresses.
[ZoHo Books](https://www.zoho.eu/) has maybe more interesting features. And ZoHo does also CRM. Tracking Rchain stakeholders is also a necessity.

**Comment by drbloom** [comment]
Rchain's ZoHo free plan only allows for 25 email accounts.
@rchain.coop email addresses are not being assigned to individual users, but to official roles.
@rchain.coop emails are for coop business and reflect the bona-fide voice of the coop.

**Comment by jimscarver** [comment]
there is a [Zoho CRM QuickBooks Integration(https://www.zoho.com/crm/help/quickbooks/) if we were using that.

there are  [googlesheets quickbook integrations](https://www.google.com/webhp?sourceid=chrome-instant&rlz=1C1CHFX_enUS702US702&ion=1&espv=2&ie=UTF-8#q=googlesheets+quickbooks&*) we might use.
and there is [google script for google apps](https://developers.google.com/apps-script/) we use.

**Comment by drbloom** [comment]
We should decide on a bulk email service to handle a large mailing list. Rchain.coop's current email server can only send 250/day. The limit can only be upped to a max of 2250, and we have several times that number of recipients if we include all of our lists.

[Mail Chimp](https://mailchimp.com/pricing/growing-business/) would charge us $60/month, and their service has all of the bells and whistles. SendGrid is cheaper, but has been experiencing support issues regarding their mailing lists.

Necessary features are
- Low failure rate (servers have high send score)
- Multi-User accounts for shared admin
- Tracking
- HTML templates
- Easy _unsubscribe_ for recipients

**Comment by drbloom** [comment]
What service for mass email?

**Comment by lapin7** [comment]
I like http://www.aweber.com 
With that we can set up a huge marketing mail campaign.
Have to figure out the cost.
And a friend of mine can set it up for Rchain.

**Comment by patrick727** [comment]
I'm fine with aweber or sendgrid, im most comfortable with mailchimp. 

I'd like to know more about aweber from HJ when he gets a chance but would default to mailchimp.

**Comment by lapin7** [comment]
I propose to have the weekly Member Meeting one hour before the Greg Hangout on Wednesdays. After the Greg Hangout is not possible because of the Dev Standup.
There are lot's of things to discuss, to decide and to assign. 
Ian could you schedule that on the ZoHo calendar? And change the hour of the Greg Hangout? I did it wrong because of different global times. BTW maybe it's better to use UTC -2 +8 -5 instead of EST or CET or things like that.

**Comment by drbloom** [comment]
@lapin7 - I changed the calendar times for the Community Hangout and RChain Member meeting.
Zoho adjusts the calendar times to match each client's preferences.

RE: Mailing lists & campaigns - If we can find reliable code for a self-hosted mailing list service we could do this for practically nothing, just the price of an Amazon EC2, IP, and some bandwidth. [Mautic](https://github.com/mautic/mautic) and [Mailtrain](https://github.com/Mailtrain-org/mailtrain) are two such projects that might do the job.

**Comment by lapin7** [comment]
@drbloom Could you set up a budget and a proposal for "Mailing lists & campaigns".
Then we can discuss here about the approval and get started.
There's also a spreadsheet draft for the approval proces and reward process (made by @jimscarver ) [RChain Community RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=0)

**Comment by lapin7** [comment]
ZoHo is used and QBO for bookaccounting
