### ISSUE TITLE
O> Email templates for payment process

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#90]
The communication about allocating budgets and burning budgets goes through the add-on "Mail Merge" and Gsheets:

- [RChain Activist RHOC Distribution](https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM/edit#gid=2044445250)
- [Declaration (Responses)](https://docs.google.com/spreadsheets/d/19Y5aEZelHa2JISCXB6jViTiRx9H0cCmha8arYz7vbg0/edit#gid=702641561)

The email templates are:

- RHOC distribution August, 2017
- RHOC payment August, 2017
Let's first edit the templates in this file and some copying and pasting. Later we can experiment with editing this [draft](https://github.com/rchain/Members/edit/master/Invoice%20preparation)
Don't know what works best. [HTML Email](https://htmlmail.pro/) is also a nice tool

**RHOC distribution August, 2017**

Dear {{Github Name}},

Thanks for your help in getting a decentralized governance model working for allocation of budgets to Github issues and setting the percentages for rewards in ["RChain Activist RHOC Distribution"]().

Through the add-on "Mail Merge with Attachments" you see here an overview of your reward for working on issue {{Github issue}}.
Your reward for this month is {{$ To Pay}} on issue {{Github issue}} or {{⍴ To Pay}}.
This reward is {{AVG work}} of the budget.
If this information is not correct then please say so.

The transfer will be done after you've made a declaration through the ["Declaration Form"](https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform) with a Gdrive link to your invoice in PDF format. If that doesn't work, then please send the invoice in PDF format to ops@rchain.coop.

You can use ["Template Invoice"](https://docs.google.com/spreadsheets/d/1v_mdcabsCsRTB4hR4GIHvkZrB2k9Ddp3LQcu8rsL5zU/edit#gid=1989342494) or you can make an invoice yourself, containing the following info: 

First name, Last name / Company name, 
Address, 
City, 
Postal code, 
State, 
Country, 
ETH address, 
Due date, 
Invoice date, 
Service description: I've worked for {{AVG work}} on issue {{Github issue}} during the period from August 1, 2017 to August 31, 2017
Extra comment is useful for improving this way of working.

If your payments during this year are above $500, then the Coop needs a tax form to be filled out by you.
If your work for the Coop is on a regular basis, then the Coop needs also a Statement of Work.

Let's see how this goes and I hope that the first transfers will happen this month.
--

Cheers,
HJ

**RHOC payment August, 2017**

Dear {{Github Name}},

{{Remark}}

Thanks for having used the [Declaration Form]((https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform)) and the [Template Invoice](https://docs.google.com/spreadsheets/d/1v_mdcabsCsRTB4hR4GIHvkZrB2k9Ddp3LQcu8rsL5zU/edit#gid=1989342494). This increases the efficiency of the decentralized accounting enormously.

The {{⍴ To Pay}} RHOC has been sent to ETH address: {{ETH address}} with this TxID: {{TxID}}
If this is not correct then please say so.

Your invoice is stored in Gdrive: [Rchain/Contracts/Contractors](https://drive.google.com/drive/folders/0BwX0krsxHncTc2pHRVBpZTR6cDQ)/{{Github Name}}/Invoices
{{Invoice}}
Please keep an eye on the Access Rights of this document, because it may be visible to anybody. Because of different Ownerships these settings can probably only be set by yourself.

Let's see how this goes and I hope that the first transfers will happen this month.
--

Cheers,
HJ

**{{Remark}}**
Please find herewith the correct issues that you've worked upon and the corresponding rewards. The previous mails had the same message and were sent several times. 

Please add on your invoice a row for each issue and add the corresponding amount in USD.

Sorry for the inconvenience. It's like prototyping and improving the overall system.

**Comment by kitblake** [comment]
@lapin7, if you also checkin the payment email template I'll make some minor corrections.

**Comment by lapin7** [comment]
Thx.
Where did you edit the template?

**Comment by kitblake** [comment]
Now I've edited it. Changed a bunch of minor stuff, like send->sent and such.

**Comment by patrick727** [comment]
@lapin7 is this issue complete?
