### ISSUE TITLE
Integration of process Member - and Activist Registration

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#93]
The introduction of Activist was a temporarily move to get things going. Now we have the Private Sale running and a process for formally registering Members. 

IMHO Activists are the same as Members, so we have to integrate the process invented under the supervision of the Board and the process invented under supervision of the Activist community.

**Comment by kitblake** [comment]
This is true, but we need to wait at least until the end of the sale. Then we need to determine how much of the KYC process to require. 
Another detail, membership fee payments are currently only possible with BTC. We gotta have an ETH payment. Preferably it'll be the only option.

**Comment by lapin7** [comment]
How is the access to the Discord group arranged and how does one get access?
If Activists have to go through the Member register procedure then they have to pay $20
This is a bit strange because about more then 30 Activists have paid already $20.

I suggest a check on TxID in the Member register procedure, in order that those Activist don't have to pay again for becoming a formal Member.

I hope the problem owner @fweilih will join the Github/Members and will help with the request.

**Comment by kitblake** [comment]
Yes, if we can honor the previous payments that would simplify things for the Activists. However in order to register for the sale it was necessary to pay again (Ed said that the co-op would then have to pay the earlier payment back).

The registration was guided by a Javascript-driven form with multiple tabs. In the last tab at the end of the process, when KYC and payment was complete, the user received a personal invite link to Discord.

**Comment by jbassiri** [comment]
There should be 2 workflows for on-boarding activists:

1. MEMBERS: anyone becoming a member is invited to also be an activist (embedded within membership workflow right after you get your discord account imho)

2. PRE-MEMBERS: those looking to dip-their-toes and explore activism without becoming a member. This includes people in the slack-universe who are prospective members or entrepreneurs who are not interested in membership but want to be activists/evangelists because they plan on building on RChain in the future or whatnot. Here we can have a lower standard. Perhaps anyone can become an activist after sharing some key info - @lapin7 what do you think is the minimum set of information

**Comment by lapin7** [comment]
I suggest one workflow.
First question: I wanna be actively involved or I just want to be informed.
Actively involved leads to membership and points members to GitHub\Members
Activists are becoming or treated as Members
Activists don't exist anymore. It was just meant as a temporarily invention.
Consequently we delete everywhere the term Activist in folders and so and
in speaking language.

--
Cheers,
HJ

**Comment by lapin7** [comment]
This week I want to invite Activists, that have gone through the PRE-membership registration and paid a fee of $20, to become a Member and get access to Discord.

A personalised email will be send. The content is drafted in Gdrive: RChain/Members/Identification/[Template Activist to Member](https://docs.google.com/document/d/16szs0_Obml8x6gm3MO1fas8S4p1V7pbweiMeqjq2L6Q/edit#heading=h.iznzyifbq2y3
)

Please help to get a nice email.

**Comment by dckc** [comment]
oops... "Activist" is passe? I didn't realize that in the update of README and CONTRIBUTING that I just did.

**Comment by lapin7** [comment]
Activist is not passé yet. I'm in the process of converting Activists into
Members. Respectively:

   1. Activists that have paid $20 and/or are collaborator on Github/Members
   2. Activists that are a collaborator on Github/Members
   3. Collaborators on Github/Members that didn't go through a registration
   process
   4. Members that have paid $20 in order to become a member and have
   participated in the Private Sale, will get an invite to become a
   collaborator on Github/Members
   5. Members that have paid $20 in order to become a member, will get an
   invite to become a collaborator on Github/Members
   6. People that are just interested in News will get a follow up
   invitation to become a Member

Therefor the Readme file is important, because it would make the mail, to
be send to all above persons, more simple. The content that is now in
the Template
Activist to Member
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F16szs0_Obml8x6gm3MO1fas8S4p1V7pbweiMeqjq2L6Q%2Fedit%23heading%3Dh.iznzyifbq2y3&si=5281391242641408&pi=4c5bf952-5ca4-45e0-fc2a-e3a9e94f9268>
could
just be a reference to the Readme.


--
Cheers,
HJ

**Comment by drbloom** [comment]
**FOUR MEMBERSHIP REQUIREMENTS**
1. Affirm Membership agreement
2. Photo of current govt issued ID
3. Verified payment of membership fee
4. Verify face on live video

The private-sale portal will be modified to support this process and I've asked for items #1 & #2 to be expedited to help us collect data from activists who have already paid.

The process can be expedited further for those who have already paid, by affirming the Membership Agreement via email and uploading the ID to the Live Interviewer using a service like https://send.firefox.com/

**Comment by lapin7** [comment]
Please edit [Invite Activists to become Member.md](https://github.com/rchain/Members/blob/master/Invite%20Activists%20to%20become%20Member.md) ASAP.
The MD formatting needs some adjustments.

**Comment by lapin7** [comment]
@drbloom @navneet @kennyrowe @dckc @kitblake 

Hi guys,
Is [this file Contributing.md](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md) the correct process and is it well explained?
Then we can tweet it as a reaction on the Vlad tweets.

**Comment by jimscarver** [comment]
The message looks good @lapin7. I do miss not being able to comment and
suggest edits with the ease of google doc.

I lament the end of Activists as there will always be an rchain community
beyond members who we want to engage so they may ultimately become
members.  Some will never join because they wish to remain anonymous.

**Comment by drbloom** [comment]
@jimscarver - I agree with you, especially regarding anonymous members. Every RChain Cooperative member gets one vote, necessitating strong proof of individuality. This is not compatible with anonymity unless we had a trusted 3rd party handling identity.
It would be easy, however, to accept **anonymous membership** allowing full privileges, with the exception of voting rights. There is also the question of whether an anonymous member should be able to collect on their yearly RHOC rebate. I think they could.

**Comment by dckc** [comment]
>  I do miss not being able to comment and suggest edits with the ease of google doc.

What prompted the move toward github? A lot of what's going on seems easier to do in google docs.

**Comment by lapin7** [comment]
I will move it back. Source is Google doc and it will be copied to the .MD
file.


--
Cheers,
HJ

**Comment by dckc** [comment]
I mean in a larger sense - why is there a `/rchain/Members/` github repo at all?

It's not a software development project. It's not even one coherent document development project where version control is cost-effective. A github repository has a very strong sense of what's inside and what's not inside: git keeps a cryptographic history of every change to any part of the repository. Any change to one part impacts the commit checksums of all other parts, for example. Collecting loosely related materials in one repository is asking for trouble. Also: while github's web user interface makes git considerably easier to use, collaborating without a pretty good understanding of what's going on underneath is also asking for trouble. If the goal is to help people work together on loosely related tasks, sticking to stuff more people are familiar with (spreadsheets, docs) seems easier.

**Comment by lapin7** [comment]
You're right but for the moment github suits fine.
We've tried another project management-tool, Taiga, before. It became a mess. Probably we're moving towards Mattermost. Google docs, sheets and forms are extensively used. We've created bridges to other environments.
The tool discussion is not so important. On-boarding people is the most important and we will see where the most interaction is taking place and concentrate then further on that place.

**Comment by lapin7** [comment]
Process of converting Activists into Members. Respectively:

   1. Activists that have paid $20 and/or are collaborator on Github/Members
10 persons

   2. Activists that are a collaborator on Github/Members
   3. Collaborators on Github/Members that didn't go through a registration
   process
   4. Members that have paid $20 in order to become a member and have
   participated in the Private Sale, will get an invite to become a
   collaborator on Github/Members
   5. Members that have paid $20 in order to become a member, will get an
   invite to become a collaborator on Github/Members
   6. People that are just interested in News will get a follow up
   invitation to become a Member

Process starts today (2017-09-27) with batch 1:


Email Address | Name | GithubName
-- | -- | --
ethnosentientist@gmail.com | Leah McKelvie | plantether
lapin7@gmail.com | HJ Hilbolling | lapin7
gary@oxide.net.au | Gary Stephensong | stephensong
kdvactmgmt@gmail.com | Kevin Valentine | kdvalentine
realtyanddesign@gmail.com | Kendall Williams | Ken-dahl
grospic@gmail.com | Grospić, Tomislav | tgrospic
rcbhux@protonmail.com | Brian Huxley | rcbhux
andrewvam@gmail.com | Andrew Vamvakaris | vamvari
takksplace@gmail.com | Joshua Williamson | Takksplace
stephen.a.prior@gmail.com | Stephen Prior | stprior

**Comment by kitblake** [comment]
Made some minor adjustments in the mail template. 
As the Private Sale ends tomorrow, that will make some of Contributing.md obsolete. Which is good because that section was overly complex. HJ, if you move the content back to the Gdoc we can modify accordingly.

**Comment by lapin7** [comment]
Kit,

Thx for the adjustments. But Ian did some work on it as well. And I'm using
now this template.
We can see how this one evolves in further direct mailings.

TEMPLATE
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F16szs0_Obml8x6gm3MO1fas8S4p1V7pbweiMeqjq2L6Q%2Fedit%23heading%3Dh.xqzty2i6nt5t&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>


Dear {{Name}},

Thanks for having gone through the PRE-membership procedure and being an
active collaborator on Github/RChain/Members
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2F&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>
 as *{{GithubName}}*. As you know, the term activist was used temporarily,
because the process for becoming a formal member of the Cooperative was not
yet in place. The term activist will not be used anymore. We now invite you
to become a member of the RChain Cooperative, i.e., moving from activist to
member. It just needs an extra verification to make sure that each member
is one real person.

If you agree with the Coop Membership Agreement
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2Flegaldocs%2Fblob%2Fmaster%2FCoop%2520Membership%2520Agreement.pdf&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>
and
the Coop's Privacy agreement
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2Flegaldocs%2Fblob%2Fmaster%2FForm%2520of%2520Privacy%2520Policy.pdf&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>,
please proceed to join the RChain Discord server.

*How to join RChain Discord:*

   1. Obtain a Discord account from https://www.discordapp.com/
   2. Save your username and password to somewhere safe
   3. Use the INVITE LINK below to join the RChain Server. The link can
   only be used *once*, so please don't make the mistake of removing
   yourself from RChain by clicking "Leave Server"!

*READ THIS EMAIL BEFORE CLICKING THIS LINK*: *{{DiscordInvite}}*

*Member Verification on Discord:*


After joining the RChain Discord server you need to be *promoted* to MEMBER
by a moderator.
Reach out to @ian: or @kennyrowe: and introduce yourself. (Make sure that
you see a colon*:* at the end of their name)
To verify that you are YOU, the moderator will ask you to:


   1. upload a current government issued photo ID (Firefox provides a safe
   upload service here
   <http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fsend.firefox.com%2F&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>
   )
   2. appear briefly on *LIVE VIDEO*
   3. provide your secret Discord invitation code (the last seven
   characters of your invitation link)


*Member Signup Portal*

The Coop is developing a website that will automate new member
registrations and payments. When the site is finished, we will provide you
a username and password so that you can access your member profile.


Member participation and VOTING is essential to the success of the
Cooperative. Slack is being overrun by impostors and phishing attacks, so
Greg Meredith started this RChain Discord. It need not be our only tool for
chat & collaboration, but it would be great for us all to be on the same
platform.

*One more thing. *Please don't forget to set your own reward on the issues
and your opinion of the rewards for your collaborators. You can do it by
giving a comment on the issue or by using the form
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA%2Fviewform&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>.
An overview of the issues is here
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o%2Fedit%23gid%3D1168839067&si=5281391242641408&pi=4f3a84a0-373f-445f-bb36-e1fb9d3cc6e4>
.
{{Remark}}

See you on Discord and Github
Ian, HJ

--
Cheers,
HJ

**Comment by jimscarver** [comment]
I think I paid only $10 in bitcoin before the amount was changed to 20. If
I remember a few people paid only $10. Now I paid $20 in the real
registration so I guess I will get the $10 back. It will be a lot less ETH
than I paid. I wonder if it would be better to just refund the exact amount
of btc or eth they paid. It does not matter to me.

**Comment by lapin7** [comment]
I suggest to keep calculating in $.
At the time you paid $10 so you get $10 back. It doesn't matter if BTC or ETH have gone up or down during that timeframe. Otherwise RChain would take the risk of speculative actions. That's not wise.

**Comment by lapin7** [comment]
Batch 2 has been emailed.
Criteria: Fee paid with TxID, Collaborator on RChain/Members

Github ID
--
optictopic
ervin-lemark
magicmirage
kirkwood
jnicolau
jimscarver
kitblake
niwaa
yenda
hierophantos

@drbloom I need more Discord ID invitations

**Comment by jimscarver** [comment]
My understanding is the member signup is now working per this slack announcment yesterday.
ian [1:31 PM] 
This is a big project and there will be many related projects with their own communication channels.
If you'd like to become a *MEMBER* of the RChain Cooperative you may signup here:
https://presale.rchain.coop
You will get access to the Co-op's Discord channel and have an actual *vote* in Co-op governance.

**Comment by jimscarver** [comment]
And @drbloom provided a better link in mattermost going to the page.
Please help us sign up members to the RChain Coop.
http://member.rchain.coop

**Comment by drbloom** [comment]
I worked with a Scala programmer this past weekend to make several updates to the member registration website. The changes are being reviewed this morning by N., and hopefully go live in a few hours.

- Payment is still collected in BTC by BitPay.
- There is an additional payment button for both those who have previously _pledged_ payment and also for people whose transaction with BitPay failed completely.
- The document upload function has been repaired so that members can upload their photo ID.
