### ISSUE TITLE
RChain pool for small participants in NL

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#95]
Create an ETH address for small participants in the Private Sale.
@kitblake represents the group
@lapin7 fills up to 50K if needed
RHOC's are distributed according to the ETH participation
Chats through Telegram #rchainpool (invite only)
[Overview](https://docs.google.com/spreadsheets/d/1ZJtxYSNNpR5WfdGth_Yb-1tR2oW1Rsa1JvcjOPrrP0w/edit#gid=0)

**Comment by Sprkz** [comment]
hi guys can I get a Telegram invite ?  please , thnx - - I am   @sprks

**Comment by kitblake** [comment]
Done.

**Comment by kitblake** [comment]
The pool worked out and is now closed.

**Comment by optictopic** [comment]
Can I get a Telegram invite too?  @optictopic

**Comment by lapin7** [comment]
Yes can. But the speaking language will be mostly Dutch, NL. Does that
still interest you.
HJ

--
Cheers,
HJ

**Comment by vishyim** [comment]
@kitblake - i missed this... any chance this opening up again shortly?? thx

**Comment by kitblake** [comment]
It's done and delivered. If another opp shows up I'll find you in this issue and let you know.
