### ISSUE TITLE
O> Define Members github issue reward system; promote in Discord

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#96]
Let's scan the issues that are talked about in Discord.
And let's them solve here in Github.

**Comment by lapin7** [comment]
Let's explain to Discord Members how RChain does Support in the most general sense. Support means activities around: Marketing, Communication, Finance, Legal, Logistics, Production.

Everybody can create support issues through [Github\RChain\Members](https://github.com/rchain/Members/issues/).

If somebody wants to participate in handling those issues then following actions are needed:

- [ adgag] adgag



Eerst een Github account aanmaken
Inschrijven bij RChain via Activist Registration
Ik nodig je vervolgens uit om Collaborator te worden bij de repository Github\RChain\Members
Het vertaal issue is al gemaakt. Zie #100
Je kunt een budget voorstellen via form Budget allocation and - spending
Dat voorstel wordt op dit moment nog door een aantal key activist verwerkt in Pub Activist Budget Allocation-Spending
Vervolgens maak je bekend dat je aan het issue gaat werken door assignment in Github
En gedurende de maand bepaal je hoeveel elke collaborator krijgt van het budget voor het gedane werk. Via form Budget allocation and - spending
Ik maak dan aan het begin van de maand een factuur voor je aan in een Gsheet en die kun jij weer aan mij geven via het form Declaration. De factuur moet dan in als een Google PDF file opgeslagen worden.
Zodra ik de factuur ontvangen heb, zend ik de RHOC naar de gespecificeerde ETH-adressen.

**Comment by jbassiri** [comment]
Too many issues, there is issue creep. There should be 10 max

Tough to keep track of and overwhelming

Not everything needs an issue. If someone is doing something well, take it off the issues and pay him her in a weekly monthly stipend



-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by lapin7** [comment]
We can assign a different state to an issue and consolidate issues in a hierarchy. That takes some time of course.
@jbassiri could you make the process of becoming a collaborator known in Discord?

**Comment by jbassiri** [comment]
Yes, thanks for clarifying and explaining the process.

**Comment by lapin7** [comment]
I found a new issue:
Cleaning up (the behavioral-types section of the rholang spec](https://github.com/dckc/rholang-spec/blob/grammar-markup/specification.rst#behavioral-types) by @dckc 
Don't know yet where and how to place it.

**Comment by dckc** [comment]
Not every issue goes here, does it? Issues in that spec can go in the `rholang-spec` repo, no?

Oh... I guess in order to show up in the budget process it should be represented here somehow. Hm.

**Comment by kitblake** [comment]
If this is something a core developer should fix then it needs to be tasked within that team. Note that there is also a Jira which is only accessible to the core developers. Putting the issue in the rholang-spec repo is probably the right place. Budget only applies if someone from the community spends time on it.

**Comment by lapin7** [comment]
The whole process of Budget Allocation and Spending is now prototyped in
Google sheets, - forms and a Chrome extension for Mail merge.
Spreadsheets are a pain to maintain and the process should go to a kind of
database construction or let's try to give it a go in Rholang, if that's
already possible.

Soon I will have finished the functional spec which is independent of
implementation. The technique of DEMO is used (a Dutch invention, by Jan L.
G. Dietz, Design and Engineering Methodology for Organizations). I think
this translates one to one to Rholang.

--
Cheers,
HJ

**Comment by dckc** [comment]
@lapin your https://github.com/rchain/Members/issues/96#issuecomment-329787842 seems to be the best description of how things actually work. I used it to update CONTRIBUTING in 69d02c4

I orgainzed it in a way that I think is more clear, though there were some parts I didn't completely understand, so I just copied them verbatim.

**Comment by Lapin** [comment]
Wrong reply buddy :)

**Comment by lapin7** [comment]
Yes apparently we have @Lapin and @lapin7. The last one is me: HJ

**Comment by dckc** [comment]
I'm updating the summary to match the work that got done here.

And does seem to be done.
