### ISSUE TITLE
M> Discord Bridge

### ISSUE THREAD

**Issue by drbloom** [rchain/Members#99]
I'm hosting a service that connects channels in Discord, Mattermost, Slack, & Gitter.
Each connection can be unidirectional or bidirectional.
Current Bridges:
```
Discord #mattermost ⇄ Mattermost ~discord-bridge
Discord #rholang    ⇄ https://gitter.im/rchain/Rholang

(testing)
Discord #playground ⇄ Slack #Community
```
Goals:
* Encourage Coop membership.
* Utilize the strengths of each platform
* Comply with Discord TOS (unclear for bots like this)

RHOC bounty - I have an unsigned SOW pending with the Coop. If accepted, rewards should be distributed to others, especially the dev of the bridge software.

**Comment by lapin7** [comment]
Great !!

For the SoW and Issue rewards.

My idea for the SoW rewards is that the amount of SoW is stable and that
the issues your working on are subtracted for their part. So if your SoW is
for example 100,000 per month then your invoice would be something like
this:

SoW Bus.Admin 70,000
Issue 40       5,000
Issue 89      15,000
Issue 94      10,000
              ------+
Total        100,000
====================

The SoW amount won't be public.

Finally the SoW becomes 0


My goal is to have all work being done, listed as an issue in GitHub.
My feeling at the moment is that the Board initiates issues without much
transparency.


--
Cheers,
HJ

**Comment by entropee** [comment]
[This is a link to the Discord Bridge channel in Mattermost](https://rchain.divvydao.net/community/channels/discord-bridge)

**Comment by dckc** [comment]
@drbloom I was about to close this as done, but a couple things seem worth thinking about:

  - [ ] Reward for ongoing operation / maintenance. This service involves ongoing care and feeding. I would like to see that rewarded.
  - [ ] Operator redundancy. At least one other person should know how it works
     - [ ] public documentation would be ideal

**Comment by drbloom** [comment]
Thanks @dckc I'll follow up with @n10n about more robust hosting options. I'll also have a go at documentation, although the config is pretty straightforward. As for reward, I feel that my work on this is covered by my SOW with the Co-op. I've already asked @lapin7 if he might instead send any reward to the developer behind [matterbridge](https://github.com/42wim/matterbridge)

He is accepting tips at:
eth: 0xb3f9b5387c66ad6be892bcb7bbc67862f3abc16f

**Comment by lapin7** [comment]
@drbloom You don't have to claim a reward for yourself, but you could add a percentage reward for @dckc and @entropee. If you would however claim a reward, then you wouldn't get it anyway, because you've an SoW that gives a monthly reward.
BTW I don't accept tips at the ETH address mentioned.

**Comment by Keaycee** [comment]
@drbloom You can only set a percentage reward for the participants and yourself only when you don't have a SoW.  Also not advisable to make your eth address public

**Comment by lapin7** [comment]
@keaycee in fact SoW and working on issues are integrated in the invoice.

_BTW (it was not @drbloom 's ETH address, and to my knowledge: public ETH addresses can do no harm. Just pay attention that for each transaction you use a different ETH address)_

If one has an SoW then the person will never get a reward from working on issues, but the issues and rewards are anyway listed on the invoice. That's just to give the person an idea on which issues s/he has worked upon. And therefore it's important to give also percentages to SoW-persons.

In my opinion, we could get rid of SoW's completely, and have payments covered only by working on issues. Like that we've a dynamic system for payments, everybody knows what others do and how they get rewarded. And peers can influence in a detailed manner the rewards.

I'm figuring out with the CFO if expenses could be integrated into rewards. Like that we would have an excellent system for buying hardware, paying for travel and lodging and whatever. For the book accounting of RChain it would become more simple. But it may have some side effects with concern to paying taxes.

**Comment by Keaycee** [comment]
When you give a percentage to a person who has an SoW, will he or she been able to get a reward?

You said "If one has an SoW then the person will never get a reward from working on issues, but the issues and rewards are anyway listed on the invoice. That's just to give the person an idea on which issues s/he has worked upon. And therefore it's important to give also percentages to SoW-persons" I take No as an answer to that.

How will the given percentage be of use to the cooperative member who has an SoW? OR was it meant only to give the person an idea on which issues she/he has worked upon?

**Comment by lapin7** [comment]
See inlines HJ>

--
Cheers,
HJ

On Tue, Jan 16, 2018 at 11:54 PM, Keaycee <notifications@github.com> wrote:

> When you give a percentage to a person who has an SoW, will he or she been
> able to get a reward?
>
​HJ> YES​


> You said "If one has an SoW then the person will never get a reward from
> working on issues, but the issues and rewards are anyway listed on the
> invoice. That's just to give the person an idea on which issues s/he has
> worked upon. And therefore it's important to give also percentages to
> SoW-persons" I take No as an answer to that.
>
> How will the given percentage be of use to the cooperative member who has
> an SoW?
>
​HJ> To give him/her insight in the work been done.​


> OR was it meant only to give the person an idea on which issues she/he has
> worked upon?
>
​HJ> YES​

**Comment by drbloom** [comment]
**Bridge Configuration**

Configure [matterbridge](https://github.com/42wim/matterbridge
) with the following config. (obtain valid tokens). Further instructions are available on matterbridge GitHub. On RChain Discord, Owners and some channel Admin's have permissions to set up webhooks/tokens.

matterbridge.toml
```
[slack.ourchain]
Token="xxxx"
RemoteNickFormat="['Pub-Discord'] <{NICK}> "

[mattermost]
[mattermost.rchain]
Server="rchain.divvydao.net"
Team="community"
Token="xxxx"
PrefixMessagesWithNick=true
RemoteNickFormat="<{NICK}> [{PROTOCOL}] "
#RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[discord.pubchain]
Token="xxxx"
Server="pub-RChain"
UseUserName=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[gitter.rchain]
Token="xxxx"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[telegram.rchain]
Token="xxxx"
RemoteNickFormat="[{PROTOCOL}] <{NICK}>"

[[gateway]]
name="discord ⇄ telegram"
enable=true

        [[gateway.inout]]
        account="discord.pubchain"
        channel="telegram"

        [[gateway.inout]]
        account="telegram.rchain"
        channel="-1001123521235"

[[gateway]]
name="discord ⇄ gitter"
enable=false

	[[gateway.inout]]
	account="discord.rchain"
	channel="rholang"

	[[gateway.inout]]
	account="gitter.rchain"
	channel="rchain/Rholang"

[[gateway]]
name="gitter ⇒ discordTEST"
enable=false

	[[gateway.in]]
        account="gitter.rchain"
        channel="rchain/playground"

        [[gateway.out]]   
        account="discord.rchain"
        channel="playground"

[[gateway]]
name="slack ⇄ pub-discord"
enable=true

	[[gateway.inout]]
	account="slack.ourchain"
	channel="community"

        [[gateway.inout]]
        account="discord.pubchain"
        channel="slack"

[[gateway]]
name="mattermost⇒discord/mattermost"
enable=true
	[[gateway.inout]]
	account="mattermost.rchain"
	channel="discord-bridge"

	[[gateway.inout]]
	account="discord.pubchain"
	channel="mattermost"
```
